### ISSUE TITLE
Acacia ID Mismatch

### ISSUE THREAD

**Issue by SonyUSA** [EssentialsX/Essentials#1000]
A [Buy] sign selling 17.4 produces an invalid graphic (purple block) Acacia wood that CAN be sold back to the server for the proper amount (4).

A [Buy] sign sellin 162.0 produces a proper Acacia wood but it can NOT be sold to the server.

**Comment by SupaHam** [comment]
Can you please post the exact text displayed on the Buy sign.

**Comment by SonyUSA** [comment]
[Buy]
1
17.4
p1

[Buy]
1
162.0
p1

p is my currency (potatoes) just switch for $1
Then try to "/sell hand" on both

**Comment by SonyUSA** [comment]
On the same token, Cocoa Beans and Ink Sac are the same base item number (different damage value), but when you sell the Cocoa Beans it tells you that you've sold Ink Sacs  :) Also, this may be economy breaking for Chocolate farms since you can't set Cocoa Bean price separately?

**Comment by SupaHam** [comment]
The issue with Acacia Logs is that the idea is actually `162` not `17:4`. I'm not sure why `17:4` gives you an item name of Acacia Wood, I suspect that might be a bug on Minecraft's part.

Anyways, /sell uses the `worth.yml` file in the Essentials plugin folder. So you need to specify a price for item id `162`.


RE: Ink Sacs, that's probably because the cocoa beans is of the same item id as ink sacs but different data value. It should not be any different economically.
