### ISSUE TITLE
Pay confirmation config toggle.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#1032]
RE: https://github.com/drtshock/Essentials/pull/1002#issuecomment-268830789

**Comment by Kakifrucht** [comment]
up+enter too much for them?

**Comment by mibby** [comment]
I guess so. :P Seems kind of redundant to force on everyone though if you don't want a confirmation dialogue.

**Comment by boredhero** [comment]
I strongly agree with this! It should be optional!

**Comment by smmmadden** [comment]
I think we're missing the point of the handling of international currencies regardless of origin.  This should IMO be handled using locale settings where the server is located.  Software companies try not to dictate the formatting of currency for this reason.  The whole premise around localization is to support multi-language, multi-currency and multi-timezone issues to name a few.  Imposing a confirmation dialog solely because of currency differences makes zero sense.  Java supports all this very easily, many plugins have locale settings and this is exactly where it should be.  Not forcing a confirmation of a command that doesn't warrant it.

**Comment by boredhero** [comment]
I agree with the above post. I have multiple countries on my server and none of them even have a problem with the USD. Besides, I don't do donations so there is no real monetary tie to the economy. Players on my server use the shop signs to make money and buy things and then buy ranks using money. For the amount of money that flies around my server, high ranking players with spawning farms loaning  money to players to get them the first two ranks and stuff, it's just a hassle to have to confirm. This should be enabled by default if it must exist, but should be optional.

**Comment by Kakifrucht** [comment]
I don't agree with @smmmadden's post. When moving money around in the real world, you always confirm before sending after typing amount and stuff. There is much room for error with missing a '0', or typing a different character than the localized decimal seperator due to confusion with international systems. Having a confirmation dialogue is the right way to handle it. I'm not saying that it shouldn't be toggleable though.

This has been discussed in #977

**Comment by boredhero** [comment]
Also, why do we really need commas and separators. I think it's simplest to just have $900.00.  I'd say the only necessary separator is a decimal to indicate forms of currency less than 1, which can actually be disabled a believe. Anyone will know that 9000 is 9,000 regardless of currency. My server doesn't use any thing besides the  decimal to indicate currency less than <1. Been doing it this way since 1.6.4 and I haven't had a single player with an issue of not having a comma....and I've had people from China, Russia, Brazil, Netherlands, and Germany on my server. They all don't speak super great English and their currency obviously isn't the US, but they seem to have no problem :/. I feel like this whole thing, including the reason this was implemented is a non-issue. On the contrary, I've had players complain to me already about the new confirmation.

**Comment by mdcfe** [comment]
@boredherobrine13 We have comma and space separators for readability. If you read 2501749173810 in words out loud, it would take much longer than 2,501,749,173,810. When the unseparated figure is read, it is difficult to read aloud as the digits have to be counted. However, when the comma-separated figure is read, counting the commas (4) and knowing how base 10 works is enough to read it. Clearly this separation doesn't translate well to every single locale, as some languages count differently, and many people prefer a space separator, but it is still recognisable to anyone who is roughly familiar with common currencies and numbers.

**Comment by smmmadden** [comment]
at the end of the day, we're still talking about a game with no real valuation to the monies being paid.  I fully understand the real world application of using a confirmation of transferring funds, paying vendors, merchants or others and that makes perfect sense.  If the goal of "EssentialsX" is to apply real world standards, then having a **/pay confirm** makes perfect sense.  Some plugins already apply this model of repeating the command used followed by the word **confirm**.  I wouldn't be opposed to that either as long as we can all use the same method/process for similar actions.  There is nothing worse than having 30, 40 or even 80 plugins with conflicting standards of how to handle this scenario.  It is a real problem with no one person or entity dictating software standards.

**Comment by boredhero** [comment]
I still just wish I could have the option  to disable it. Not even just for me, for the players who are complaining.

**Comment by mdcfe** [comment]
@smmmadden There isn't any need for a "standard" way of handling confirmation. In my opinion, the "traditional" way (running `/command `**`confirm`**) is more cumbersome than simply asking the player to repeat the command (press the up key), but at the end of the day, I have only ever come across three (or four at the most) plugins which have command confirmation, and considering the ~100 plugins I have had to work with, that's nowhere near enough to warrant agreeing on a uniform way to implement confirmation. Not just that, but every plugin I have seen with confirmation has given clear instructions on how to confirm the command.

**Comment by smmmadden** [comment]
@md678685 I only mention standards because in my 35+ years in the computer industry it has guided many projects to completion quicker and more effectively for its users.  One thing I've seen from the many plugins I've been using and fielding questions on is an inconsistency in approach, naming conventions, UI and many other areas that make a difference to their users.  Some only to provide a couple options and never supported as the game matures leaving users/server owners scrambling to find something better or one that actually works.  I'm not saying that about this plugin, complete opposite and have always been impressed with the quality of Essentials and recommend it to others.  So whether it is /command confirm or something else, I was merely suggesting we consider setting a precedent and perhaps standard way of handling scenarios like these to benefit everyone.  So I meant no disrespect to anyone on this thread - just providing my experience doing this full time for many years. :-)

**Comment by boredhero** [comment]
I ultimately just hope this is optional eventually. Otherwise, I will roll back. Because honestly, my players hate it, and they are what matters.

**Comment by SupaHam** [comment]
I'm a little busy at the moment. I expected very little complaints towards this feature, where it would get more praise.

I will be adding a toggle in the future when I get a chance, but it will be player based. So they can toggle this confirmation feature.

**Comment by boredhero** [comment]
@SupaHam that sounds fair to me, I'm satisfied

**Comment by Kakifrucht** [comment]
> Been doing it this way since 1.6.4 and I haven't had a single player with an issue of not having a comma....and I've had people from China, Russia, Brazil, Netherlands, and Germany on my server. They all don't speak super great English and their currency obviously isn't the US, but they seem to have no problem :/. I feel like this whole thing, including the reason this was implemented is a non-issue.

@boredherobrine13 I'm running my server for 5 years now, it has happened plenty of times that a player typed */pay whoever 100,4*, paying 1004 instead. This was 100% an issue.

**Comment by boredhero** [comment]
@Kakifrucht yes while that does happen it's a rarw occurrence and people generally know to pay people back any extra they received, because they know if they try to keep it staff will intervene

**Comment by Kakifrucht** [comment]
Well, then you should think about other gamemodes where staff won't intervene in such cases...
In most cases players were fair to each other and paid back, but it did cause some issues, and staff does not always want to read logs because a player typed the correct amount in his language, but the software thinks it's a good idea to just strip the character.
Try to be a bit more open minded on this.

**Comment by boredhero** [comment]
@Kakifrucht honestly I was only mildly annoyed by it. I didn't think to complain until my players did. But I think @SupaHam s solution is good because that way the players who complained can just disable it. I don't deny that there are scenarios where this is necessary, I'm just glad it will be optional on a per person basis in scenarios where it isn't.

**Comment by SupaHam** [comment]
This has been fixed in 5f83766. You can grab the fix from [build 461](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Edit: wiki https://github.com/drtshock/Essentials/wiki#pay-confirmation-toggle

**Comment by mibby** [comment]
Appreciate the addition. Though I'd personally like an option to keep it disabled for everyone by default with the ability to enable it if they so desired, as you would be artificially limiting what server owners can tweak and many players may not know about the toggle . But I suppose this is better than having it forced on always regardless.

**Comment by CheatSupport** [comment]
can we add in config.yml to make it off by default?

**Comment by mrfloris** [comment]
I rather have the confirmation a config setting that is off and actually an opt-in. 
I just went through a dozen (actually 14) servers and they have it all customized and turned off by default. It seems it's not a real preference to have it on by default. I wish it was an easy global setting

**Comment by mibby** [comment]
I too would like to see an option to opt-out by default in the main config, but alas I do not think it will be happening.

**Comment by boredhero** [comment]
Time to fork I guess?
