### ISSUE TITLE
Auto cancel-afk-on-move & freeze-afk-players incompatible

### ISSUE THREAD

**Issue by Coniface** [EssentialsX/Essentials#1081]
The cancel-afk-on-move doesn't seem to work. Plus, I'd like to use it with the freeze-afk-players setting but it doesn't work.

**Comment by mdcfe** [comment]
If this is still an issue, could you paste your config on [Gist](https://gist.github.com/), and post the link here along with the **full output** of `/ess version`?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.

**Comment by Konpaku-LVX** [comment]
@mdcfe hello i can't reopen this but i am having a similar issue. although this is years later. when i go afk and try to move it keeps teleporting me back to that spot instead of cancelling. jumping is the only way to get out of it.
 EssentialsX version: 2.21.2


is there maybe a config option that just makes them invincible instead? i just want to avoid people coming back and they are dead. https://gist.github.com/autoteelar/1f2595658ee0534db356c7307489de20

**Comment by Konpaku-LVX** [comment]
it does mark it right here

\# The player must use the /afk command to leave AFK mode.

but i want one where they are invincible, and can exit without having to type /afk. in fact i have that disabled. otherwise it would be an easy godmode cheat.
