### ISSUE TITLE
Essentials.afk permissions

### ISSUE THREAD

**Issue by Coniface** [EssentialsX/Essentials#1082]
Would it be possible to have two afk permissions ?

Like:
essentials.afk.enable
essentials.afk.disable

If I don't activate the cancel-afk-on-move, then user need to type /afk to unafk.
I don't want them to be able to /afk other than the auto-afk that works great.
As you may know, you can /afk when falling not to die and be put on the ground. You can /afk when you're dying to become invincible and get help [...]

**Comment by pop4959** [comment]
Closing because I don't see any purpose to this suggestion. The entire point of the AFK feature is to accurately track who is away or not. It makes sense for people to toggle AFK status when they need to. If you are concerned about invincibility features, turn them off! It's a setting already! :smile:

**Comment by Coniface** [comment]
But here's the whole point of my demand. I want people to be invincible when they're AFK, not *when they want to be* (in a dangerous situation for them).
So if they can't type the /afk command themselves, they won't be able to go invincible on demand. But the auto-afk will do its job and set invincible anyone who's actually away.

**Comment by pop4959** [comment]
Ah I see. Fair point. I think I might have misunderstood that. In that case, in light of the clarification, I will leave this issue open. Forgive me as I've been going through a large number of old issues and trying to clean them out.

I'm also going to assume you still want this feature since you responded. :smile:

**Comment by JRoy** [comment]
This can be accomplished by selectivally granting `essentials.afk` to admins and giving normal players just the `essentials.afk.auto` permission.
