### ISSUE TITLE
No Tab-prefix with build #462 and up

### ISSUE THREAD

**Issue by mfnalex** [EssentialsX/Essentials#1085]
Unfortunately, build 462 implemented something wich broke the prefixes in tab while using EssentialsChat. It worked before. I had to switch back to 461 to get it working...

**Comment by vemacs** [comment]
https://github.com/drtshock/Essentials/commit/7973f544fff0c01e174f9833df98ae6b90b87d5c

**Comment by Maxetto** [comment]
Something is wrong behind some Essentials settings (default values, maybe?), if you use "||" (OR) it shows prefixes and suffixes in Tablist even if "add-prefix-in-playerlist: false" and "add-suffix-in-playerlist: false";
if you use "&&" (AND), they seem to get removed anytime...

**Comment by Maxetto** [comment]
The Logic behind my fix was right.
If "withPrefix" is false (because "add-prefix-in-playerlist" is false, otherwise is always true), then it doesn't proceed.

With "||" instead, if that is false, then it checks the other value and that is always true, because it's an option that defaults to true and is not documented.


So let's try to understand why you don't have prefixes in tab: This is probably due to the fact you have "add-prefix-in-playerlist: false" or "disablePrefix: true"

**Comment by Maxetto** [comment]
An easy solution for everything is to remove the undocumented "disablePrefix" setting (why is it even there?).

**Comment by mfnalex** [comment]
neither "disablePrefix" nor "add-prefix-in-playerlist" does appear in my config. I only have "add-prefix-suffix: true" and "change-playerlist: true". Are you sure the correct the name is add-prefix-in-playerlist?

EDIT: it's working with "add-prefix-in-playerlist: true". I don't know why it was not part of my default config, maybe because it was generated  with the normal version of essentials. Thanks for your help!

**Comment by Maxetto** [comment]
Yes, it is correct. If you don't have it, it defaults to "true".

This is strange because I tested it with both options before sending a Pull Request :/

**Comment by mfnalex** [comment]
Sorry, I'm new to github, this topic is closed right, I don't have to delete it or something right?

**Comment by Maxetto** [comment]
Yes, it is closed, you don't have to do anything.

I'm just trying to understand why my fix didn't work correctly for you, because basically https://github.com/drtshock/Essentials/commit/7973f544fff0c01e174f9833df98ae6b90b87d5c has reopened my issue.

**Comment by mfnalex** [comment]
As I said, I started using "normal" Essentials, then switched to EssentialsX. Maybe the "add-prefix-in-playerlist" option is not included in the original config and defaults to false?

**Comment by Maxetto** [comment]
Correct, it defaults to "false"!

Ok, so... My fix was right, (@vemacs please unrevert it)

You were just missing "add-prefix-in-playerlist" because of the update of EssentialsX.

I suggest you to copy and edit the new config, as I did when I switched too: https://github.com/drtshock/Essentials/blob/35388c3b19b691a8551bbc7c30f87969be47214b/Essentials/src/config.yml
