### ISSUE TITLE
Trade Signs

### ISSUE THREAD

**Issue by drtshock** [EssentialsX/Essentials#11]
Need to either deprecate trade signs or look into storing additional blockdata, new signwidth and json data possibly opens more avenues.

**Comment by SupaHam** [comment]
Can you elaborate? What kind of features does this present, what kind of data would be stored?

**Comment by drtshock** [comment]
I believe I was talking about the ability to have extended item data on trade signs.

**Comment by SupaHam** [comment]
If we're talking about line length, I don't know tbh. A sign line's maximum characters depend on the characters present,  which at times can be 15 maximum.

Sign events are a thing. We could maybe have an Essentials command (e.g. `/createsign buy verylongitemname:withdata $123123`) that constructs and inserts a command event in the sign.

**Comment by pop4959** [comment]
Closing this since it is not much of an issue in more recent versions of Essentials, due to the updated ItemDB. Short names for items generally exist (and if they don't, they are added). Metadata don't really fit on signs, and I think it would probably be awkward / confusing no matter how you'd try to implement that.
