### ISSUE TITLE
Interact with players inventory

### ISSUE THREAD

**Issue by TomberWolf** [EssentialsX/Essentials#1160]
Hey,

we have the invsee command. What we could need is an openinv or invopen command to give / remove items directly to players inventory.

Do you think you can add something like this?

**Comment by smmmadden** [comment]
There is a plugin to do that already Open Inventory: https://dev.bukkit.org/projects/openinv

**Comment by mdcfe** [comment]
This is already an EssentialsX feature - make sure you have the `essentials.invsee.modify` permission. However, you can't directly manipulate the armour slots at the moment.

**Comment by smmmadden** [comment]
correct - invsee is in EssentialsX, and has 3 permission nodes (essentials.invsee.modify, essentials.invsee and essentials.invsee.preventmodify) but also does not support open inventory of offline players, searching for an item, opening inventory chest silently, cross-world support, opening any chests (chest, trapped chest and ender chests) and other features depending on what the user needs.

So depending on his needs are for his server configuration, he can use OOTB EssentialsX or use a more advanced extension to the command.  As a BungeeCord server owner, opening offline players chests is required since all servers run in offline mode.

**Comment by mdcfe** [comment]
@smmmadden Offline mode players are not offline players, and the `/invsee` command fits the scope of the original post. If the OP clearly wanted cross-**server** support (there is no *cross-world* limitation), I wouldn't have suggested the EssentialsX command.

**Comment by Advanced-Punish** [comment]
E
