### ISSUE TITLE
Can interact, when vanished

### ISSUE THREAD

**Issue by Kixot14** [EssentialsX/Essentials#1164]
Need add 3 permissions:
1.  **noInteractWithLoot.permission**: to prevent pickUp drop/exp, when u vanished. 
2. **preventOutgoingDamage.permission**: to prevent unexpected outgoint damage from vanished player.
3. **preventAgressionMobs.permission**: to prevent agression of mobs on you, when u vanished.

and ideally, silent chest opening (+ open blocked chest)...

**Comment by pop4959** [comment]
This is somewhat fixed in current versions, with mobs no longer targeting vanished players. Some of the other stuff requires packets, which is not really something that Essentials is likely to add. You might want an alternative plugin such as VanishNoPacket, etc, if you want a more full fledged vanish.
