### ISSUE TITLE
How i can dowload the plugins ?

### ISSUE THREAD

**Issue by stepkrep** [EssentialsX/Essentials#1208]
Sorry for my bad inglish.
Hi, i don't know how download this file:
	EssentialsX-2.0.1.jar	
	EssentialsXChat-2.0.1.jar	
	EssentialsXProtect-2.0.1.jar	
	EssentialsXSpawn-2.0.1.jar

I tried to download it from here https://ci.drtshock.net/job/EssentialsX/  but the site is offline....
Can someone help me ?

**Comment by smmmadden** [comment]
try again - could have been a momentary issue with the site as I couldn't load the page either earlier today.  I've checked and it is up and you can download from that page.

**Comment by stepkrep** [comment]
I try.... but nothinc.... Maybe can u upload the fail ? Pls

**Comment by Kakifrucht** [comment]
Seems to be down at the moment, see #1201.

**Comment by dlaverick** [comment]
I really need EssentialsXChat-2.0.1.jar also, anyone have a copy they could send/upload?

**Comment by stepkrep** [comment]
Guys the download:
https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild/artifact/Essentials/target/EssentialsX-2.0.1.jar
Don't work .-. Pls Can someone upload the files?

**Comment by smmmadden** [comment]
**The issue is with the https://ci.drtshock.net server, not the download of the jar.  The server is offline:** 
This page (https://ci.drtshock.net/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare | Hide this Alert

**And there isn't any option to report the issue so not sure who owns the server or who to reach.  Been up/down all weekend.**

**Comment by Pokechu22** [comment]
They're aware in irc.  There's a temporary mirror at https://ci.lucko.me/job/Essentials/.

**Comment by mathuin** [comment]
EssentialsXProtect-2.0.1.jar is not included at that mirror.  Is it no longer built as an artifact?

**Comment by Pokechu22** [comment]
Looks like it wasn't.  @Luck: can you check that?

**Comment by RikoDEV** [comment]
Website now working. https://ci.drtshock.net/job/EssentialsX/
