### ISSUE TITLE
Jail and mute are passing when player is offline

### ISSUE THREAD

**Issue by DisTrugator** [EssentialsX/Essentials#1243]
Why the temporary mute and jail are passing when the player is offline ? 
For example , if i want to jail a player for , 2 Hours for example , he disconect , and after 2 hours reconect again and jail time was passed.
Why someone want this ?

**Comment by molor** [comment]
Also have this problem. This can be fixed if Essentials consider only the time spent by a player in the game.

**Comment by DisTrugator** [comment]
I think is necesary

**Comment by mdcfe** [comment]
To me, this doesn't matter, because if they get jailed then they can't play on the server and if they get muted then they can't chat. In the same way, if they leave then they can't play on the server and they also can't chat.

Why would someone log on for two hours to pass jail time but not actually play? If they had to wait two hours after they logged back on, they would probably leave and not return.

**Comment by virtualdxs** [comment]
I agree with @md678685. What are you trying to accomplish with this?

**Comment by mdcfe** [comment]
Closing as there doesn't seem to be much point in adding this.
