### ISSUE TITLE
Not working with Essentials?

### ISSUE THREAD

**Issue by kingnicolas27** [EssentialsX/Essentials#1251]
Alrighty so basically I read it to be a "fork" of essentials. Does this means it needs to be installed by itself?
Or that you need to install essentials, then EssentialsX to branch off of it?

I've installed both but only Essentials pops up when I type in /pl, is this right?

**Comment by mdcfe** [comment]
You install this instead of Essentials, and any additional plugins over their respective Essentials plugins (eg EssentialsXChat over EssentialsChat). GroupManager isn't supported, though.

(By "fork", it means that the source code for EssentialsX branches off from the Essentials source code - it is based on the Essentials plugins but has lots of improvements over the original plugins, such as 1.11 support. The README also states that it is almost a *"drop-in replacement"* for the original Essentials plugins.)
