### ISSUE TITLE
Time before next teleport: now

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#1275]
Hello. It is possible to remove this message and process player teleport if remaining time is "now"?
Because this "now" is really now, then there is no need to wait, but the players are often faced with this problem, and they have to run the command again.

In addition, the word "now" in this message is impossible to translate into another language (it is present in file messages_xx.properties, but in chat still displays "now" in English).

**Comment by SupaHam** [comment]
The "now" issue has been fixed in 8fd532c. You can grab the fix from [build 480](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

It says now because now is any moment now. I'm not sure at the moment of a better way to reword it. The teleport cooldown must not be skipped because it waits exactly that long to finish the cooldown.
