### ISSUE TITLE
command /condense is buggy

### ISSUE THREAD

**Issue by Zefferis** [EssentialsX/Essentials#1298]
In EssentialsX Build: 2.0.1-b481 running in Spigot 1.12 R1 (what I have loaded on my multiplayer server)

Using the command /condense prompts the response:

"You have no items that can be converted into blocks."

This prompt occurs when trying to condense: gold ingots, iron ingots, diamonds into their respective block counterparts.

Redstone, Lapis and Coal function fine.

EDIT: I'm not versed in any type of coding but apparently NBT info changed in 1.12? Dunno if that's part of the issue.

**Comment by mibby** [comment]
I can confirm that redstone, lapis, and coal work fine for condense. However players are not able to condense iron, gold, and diamonds.

**Comment by DevonPalma** [comment]
Along with mibby 

condense works with
 - redstone
 - lapis
 - coal
 - emerald

but not
 - diamond
 - redstone 
 - lapis

**Comment by NinjaSlatz** [comment]
I also have this problem too.

**Comment by Momshroom** [comment]
Additional info: IN 1.12 Spigot

if you force it to /condense gold ingots or diamonds by doing /condense hand it turns them into gold boots instead of blocks

If you do the same with iron ingots, it turns them into trap doors

Coal, redstone, lapis, wheat, melons and emeralds work properly for me

**Comment by SupaHam** [comment]
This has been fixed in 3831464. You can grab the fix from [build 489](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Sorry for the delay on this fix and I hope the inconvenience was not too much.

With regards to the actual issue. Essentials' `/condense` would get the first best item and condense that. It never did a comparison over which of the "best items" are actually best. This fix stores all the best condensation forms and applies the most efficient.

This should fix all condense issues that have been mentioned in here.
