### ISSUE TITLE
Issue with item names

### ISSUE THREAD

**Issue by CoolLord22** [EssentialsX/Essentials#1306]
There's weird issue with colored item names, they get these weird symbols in front of them. It adds this A sorta symbol in the name and lore. Image attached below:
http://imgur.com/a/wCPi5

**Comment by SupaHam** [comment]
This is due to file encoding. You need to save the file as UTF-8. This can be done using more advanced editors such as [Notepad++](https://notepad-plus-plus.org/) and [Sublime Text](https://www.sublimetext.com/).

**Comment by CoolLord22** [comment]
The thing is that the item was given by a different plugin, which has a config file edited by Notepad++. When it's given, the name and lore are fine. However after a while (usually after the server restarts a few times or the player swaps worlds) the name changes

**Comment by CoolLord22** [comment]
(Dumb question but how do I reopen an issue?)

**Comment by SupaHam** [comment]
The issue at hand is still an encoding one. Not EssentialsX's fault. This is commonly caused because the file is not saved in the expected format, which is UTF-8. Set this JVM argument `-Dfile.encoding=UTF-8` and see if it fixes the problem.

`java -Dfile.encoding=UTF-8 -jar Server.jar`

In the bottom of this comment box there should be a button that says Reopen.

**Comment by CoolLord22** [comment]
I don't see the reopen button, but I'll try out the JVM argument and see if it happens again. Thank you for your help!
