### ISSUE TITLE
Spawner delay only affects the first spawn

### ISSUE THREAD

**Issue by ChanceSD** [EssentialsX/Essentials#1332]
Spawner delay only seems to work for the first spawn.
Example: /spawner polarbear 5000
Takes a long time for the first spawn but spawns after that take the default delay.
Not sure if it's an issue with Essentials or maybe PaperSpigot which is what i'm using.

**Comment by mdcfe** [comment]
What server version are you using? `/version`
What EssX version are you using? `/ess`

**Comment by ChanceSD** [comment]
Paper version git-Paper-1155 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
Essentials 2.0.1-b499
Still happens on those versions.

**Comment by pop4959** [comment]
Confirmed bug.

```
[21:15:12 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-192 (MC: 1.15.2)
[21:15:12 INFO]: EssentialsX version: 2.17.2.54
[21:15:12 INFO]: LuckPerms version: 5.0.72
[21:15:12 INFO]: Vault version: 1.7.2-b107
```

Debug info from F3-I after `/spawner ghast 5000`:
```
/setblock 350 68 -779 minecraft:spawner{MaxNearbyEntities:6s,RequiredPlayerRange:16s,SpawnCount:4s,SpawnData:{id:"minecraft:ghast"},MaxSpawnDelay:800s,Delay:4964s,SpawnRange:4s,MinSpawnDelay:200s,SpawnPotentials:[{Entity:{id:"minecraft:ghast"},Weight:1}]}
```

As you can see, it sets `Delay`, however `MaxSpawnDelay` and `MinSpawnDelay` are unaffected. When the delay expires, it chooses a new value between the two latter values. Since Essentials does not change these, it only affects the first spawn.
