### ISSUE TITLE
Essentials Sign Shop not working at all.

### ISSUE THREAD

**Issue by MYCQ-Projects** [EssentialsX/Essentials#1395]
As stated above in the title Essentials sign shop wont work at all even when making a brand new Config

EssentialsX version (`/essentials`): Essentials 2.0.1-b156

Server software (`/version`): Craftbukkit version git-Spigot0044d9280e8c6403 (MC: 1.8.6)

EssentialsX config (if applicable):  https://gist.github.com/ImJustJamie/82fd91025c71a7350c018ea1b8cb1f44

**Comment by mdcfe** [comment]
Update Spigot to 1.8.8 using BuildTools, and download the [latest version of EssentialsX](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).

**Comment by MYCQ-Projects** [comment]
how do I upgrade using buildtools?

**Comment by MYCQ-Projects** [comment]
Well, I got the spigot 1.8.8 jar file and tried it and the buy signs still don't actually work.

**Comment by smmmadden** [comment]
just curious, have you ever had the signs working and if so, what version(s) were you on when you did?

I'm also surprised that not only are you still on 1.8.x (when the latest is 1.12), you're using Essentials build 156 and not the latest build 498.  At some point in time, you should really think about upgrading to the latest versions including Minecraft Client, Java (1.8.0_131 latest) and take advantage of the thousands of bug fixes between 1.8 and 1.12.  It's only to your advantage to do it sooner rather than later. :-)  I can tell you with 100% certainty, that this issue does not exist in 1.11 or 1.12.

**Comment by MYCQ-Projects** [comment]
Well I'll look into it but the thing is, I run a network of servers and they both run the same version, however, on one server it works perfectly fine but on the other, it just doesn't work

**Comment by MYCQ-Projects** [comment]
and im currently running the latest Java too, I also use ViaVersions and Viabackwards on my server to support versions up to 1.11.2 and all the way down 1.7 I do believe

**Comment by mdcfe** [comment]
@smmmadden Many people have different reasons for remaining on older game versions, and it's unlikely that the Java version is going to cause specific bugs. If it's a config issue (which it looks like) then the Minecraft version will have little to no effect.

@ImJustJamie If you haven't already, update EssentialsX from the link above. The version you're running is incredibly old (~2 years) and isn't supported.

**Comment by MYCQ-Projects** [comment]
@md678685 I have updated to the link you sent above and it still refuses to allow signs to work

**Comment by mdcfe** [comment]
I believe `enabledSigns` should be `enabled-signs`.

**Comment by MYCQ-Projects** [comment]
Okie
Ill try that

**Comment by MYCQ-Projects** [comment]
No It still doesnt work.

**Comment by MYCQ-Projects** [comment]
Anyone help?

**Comment by mdcfe** [comment]
My mistake, it should be `enabledSigns`.

**Comment by MYCQ-Projects** [comment]
Still doesnt work.

**Comment by MYCQ-Projects** [comment]
Anything else?
that could help me?

**Comment by smmmadden** [comment]
@ImJustJamie in an earlier post you mentioned that you have two servers where one works and the other does not and both are configured with the same plugins, same versions and same configuration and permissions files "for all plugins"?  This sounds more like a configuration issue and not a plugin problem.

my previous post I asked if this ever worked on the server having the problems?  Based on your answer, if it did work and now it doesn't - what changed to make it not work or under what conditions does it not work?  If it never worked, then you need to review the configuration files and permissions to make sure you have signs enabled as @md678685 also stated to upgrade tot he latest version which is #499.  Did you upgrade to 499 or some other version? Did you start with fresh configuration files from the most recent build (Highly recommended since you were hundreds of versions behind).  Also, did you download all the Essentials files or certain ones?  Any errors in the console during startup or interacting with the signs?  Any in-game error when trying to interact with a sign?

I am also using BungeeCord Server, Spigot Servers (both 1.12 builds), with ViaVersion (v1.1.1) and ViaBackwards (v2.1 Dev Build 22) and have no problems with signs in 1.11.2 and 1.12 servers.  Make sure you don't have another plugin that is overriding the signs in Essentials and that you are using the latest one for your versions of the servers.  If you're having issues finding updates, [you can go here](https://www.spigotmc.org/wiki/spigotmc-compatible-plugins-by-release/) to find updates for plugins.

**Comment by mdcfe** [comment]
Could you clarify what "not working at all" is?

Could you also run `/ess debug` and see if anything is output when creating or using signs?

**Comment by MYCQ-Projects** [comment]
I upgraded to 498 since that was the latest version yesterday.

**Comment by MYCQ-Projects** [comment]
Ok so when i Debug the sign issue this is what shows.

however it does say its not working however the sign itself does work or turn blue to say its gunna work

[04:44:38] [Server thread/INFO]: ImJustJamie issued server command: /ess debug
[04:44:38] [Server thread/INFO]: [Essentials] attempting to charge user ImJustJamie
[04:44:38] [Server thread/INFO]: [Essentials] calculated command (essentials) cost for ImJustJamie as 0
[04:44:38] [Server thread/INFO]: [Essentials] charge user ImJustJamie completed

[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.color - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.magic - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.format - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.color - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.magic - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.format - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.color - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.magic - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.format - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.color - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.magic - true
[04:44:59] [Server thread/INFO]: [Essentials] checking if ImJustJamie has essentials.signs.format - true

**Comment by MYCQ-Projects** [comment]
Also I stated it above also that it cant be a config issue due to me even remaking the config from fresh by remaking it and it still doesnt work.

**Comment by smmmadden** [comment]
you just said "however it does say its not working however the sign itself does work or turn blue to say its gunna work"
Either the sign is not working or it is.  Nothing in the log above states anything is "NOT" working.  Please provide screenshots of what it is you believe is not working.  We've asked a number of questions, but you haven't answered them.
Please provide a full startup log of your server so we can see what if anything is wrong and a screenshot or video of what you're trying to do that isn't working the way you think it should.

**Comment by MYCQ-Projects** [comment]
Well Make them more clear also when I said it doesnt work i mean this, but like i said it doesnt work meaning you can make the sign the but the bit saying [buy] doesnt turn blue and your not able to buy anything

http://prntscr.com/fwbfac

**Comment by smmmadden** [comment]
my questions to you were very clear - read each one and respond accordingly.  The screenshot you finally provided, shows that the sign can be placed and it can accept text on it.  So that part works.  Two parts of the sign process is working.  So now lets focus on the functional aspect of the sign.
Permissions: do you have access to essentials.signs.* permission nodes (there are 35+ perms)?  If you do, provide a screen shot of which ones.  Also what permission system are you using (GroupManager, PEX, LuckPerms, etc.)?
Startup Logs: please provide a FULL startup log of your minecraft server so that we can see which plugins are being used (not to be nosey, but to ensure there isn't something conflicting with signs) as I asked above.
Essentials config.yml - provide a screenshot of the signs.* Player Commands you have enabled/disabled.
Essentials config.yml - provide a screenshot of the enabledSigns: section of the file.

**Comment by MYCQ-Projects** [comment]
If you scroll up you can see my config already also if you thinking i havnt taken out the # I have taken them out if you check my config in my very first post
I use Groupmanager
Im OP so I would end up having all permissions anyway including * perms as im owner


Startup log:https://gist.github.com/ImJustJamie/56be59864a6a9dbea8e64f6527731042

**Comment by mdcfe** [comment]
@ImJustJamie The old GroupManager plugin is not supported. Can you try disabling SignShop to see if this changes? (As a side note, I don't see why you're trying to use EssX's shop signs alongside SignShop?)

**Comment by smmmadden** [comment]
I saw the config file - but that wasn't the only thing I had asked for.  By you providing the startup log as you did, it confirms my suspicions that the issue is with other plugins.  I stopped counting after 6 issues in your startup logs.  Fix the plugins so they start and enable without warnings/errors/exceptions and using the minimum required plugin versions shown in the startup and then lets go from there.

I agree with @md678685 that trying to use another plugin for the same thing that EssX is doing will only result in something not working properly and why the startup logs were requested.  Many of them are not loading properly and a couple of them you have duplicate files present in the plugins/ folder.

**Comment by MYCQ-Projects** [comment]
Well no the thing is My System admin mustve installed it since i didnt even know it was there

**Comment by MYCQ-Projects** [comment]
I removed SignShops and retested Essentials and it still does not work, and also Even with warnings warnings dont matter all plugins will still run the same and I also dont have any error only some that are showing due to a staff related plugin nothing to do wih essentials.

**Comment by MYCQ-Projects** [comment]
I just went through the start up log and cleaned all warn's and no I barely have any the only ones I have are to do with buycraft but I can't access my buycraft atm

**Comment by MYCQ-Projects** [comment]
Nevermind the help I fixed it

**Comment by smmmadden** [comment]
@ImJustJamie can you let us know what it was that you fixed?  It would help others if they run into a similar problem.  Thanks!

**Comment by MYCQ-Projects** [comment]
Well, It turns out that using Essentials custom messages, can actually cause your signs to bug and disable themselfs, so the way i fixed it simply removing the messages_en.properties file
