### ISSUE TITLE
/condense not work Melon slice -> Melon block

### ISSUE THREAD

**Issue by andris155** [EssentialsX/Essentials#1431]
EssentialsX version (`/essentials`): Essentials version 2.0.1-b501

Server software (`/version`): This server is running Paper version git-Paper-1167 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

EssentialsX config (if applicable):

**Comment by Antivalent** [comment]
I think this is on purpose. /condense will only process items that can be converted back into their original state later without any losses. A diamond block can be turned back into nine diamonds with 100% reliability, but a melon won't always yield you nine lemon slices, so you're potentially losing items. This might also be the reason why it doesn't work on quartz (and some other blocks previously requested), since you can't turn a quartz block back into quartz shards.
