### ISSUE TITLE
Command /gc somewhat broken

### ISSUE THREAD

**Issue by pop4959** [EssentialsX/Essentials#1446]
The command '/gc' displays "Error: null" instead of some of the information that should be displayed.

EssentialsX version (`/essentials`):  Newest, as of this post

Server software (`/version`): Newest, as of this post

**Comment by mdcfe** [comment]
Please post the actual output of the version commands as shown, as these versions can and do change rapidly.

Are there any errors in the console? If so, could you paste them on [Gist](https://gist.github.com) and link them here?

**Comment by pop4959** [comment]
I have the version and output below. No errors are outputted, the command just does not output correctly.

![gc bug](http://i.imgur.com/f906vfC.png)

**Comment by OozeIam** [comment]
I have the same problem.

**Comment by pop4959** [comment]
It works occasionally, but rarely. I've noticed that with other plugins recently there are a lot of errors regarding banner entities. Since the missing stat is counting entities in the world, etc, perhaps that is the problem? @md678685

**Comment by ghost** [comment]
Hi there, 

I happened to stumble across this issue on my server. As @pop4959 said, the issue seems to relate to banners. I tested this with regular banners (straight out of the creative inventory), and the issue did not occur. However, I placed a banner that a player has modified in the world, and the "null" issue persisted. 
Example of before and after I placed the modified banner: http://imgur.com/a/Z4dTK

Hopefully this issue can be fixed. 
Thanks!

**Comment by pop4959** [comment]
This might be fixed on the newest version of spigot. I have not been able to test it yet, but the patch notes mentioned something about banner initializations.

**Comment by ghost** [comment]
Yes, this has been fixed in the newest version of Spigot. I just updated to the latest version and tested it, and it works as expected. Thanks! 
http://imgur.com/a/ran1W

**Comment by pop4959** [comment]
Ok, closing this then. Update your spigot if you have this issue!
