### ISSUE TITLE
[Request] Option to disable essentials respawn listener to preserve vanilla behavior

### ISSUE THREAD

**Issue by chillerkraft** [EssentialsX/Essentials#1472]
for a while i thought there was a bug where setting respawn priority to lowest didn't actually allow multiverse behavior completely, missing out on vanilla bed respawn that multiverse allows, but now i realize that it is not a multiverse feature it is vanilla so now i am here requesting this:
can you somehow have a way for us to have essentialsxspawn and still have the ability to have the vanilla bed respawn feature?

**Comment by NachtRaben** [comment]
//# When users die, should they respawn at their first home or bed, instead of the spawnpoint?
respawn-at-home: false

Set this to true and they'll respawn at their bed, if their bed spawnpoint isn't set it'll go to their first set home, if they have no set home I believe it falls back to world spawn.

**Comment by chillerkraft** [comment]
no. i should have mentioned, i dont want to use the respawn at home/bed feature in essentialsx

**Comment by NachtRaben** [comment]
You should probably set the title to something like "[Request] Option to disable essentials respawn listener to preserve vanilla behavior."

**Comment by chillerkraft** [comment]
Thanks
