### ISSUE TITLE
Feature Request: world generator

### ISSUE THREAD

**Issue by FatmanC** [EssentialsX/Essentials#1477]
EssentialsX version (`/essentials`): 

Server software (`/version`): 

EssentialsX config (if applicable): 
So far i am enjoyiing essentials. It really is the easiest plugin to use. Would it ever be possible to create an addon plugin or add it to essentials, a custom world generator? like being able to set all biomes to extreme? or extra structures? or add in new crazy biomes?? it is the last thing i am looking for, for my server.... and its crazy. Hard to find one that works on a 1.12, let alone a pluging not a mod...

anyway thanks for considering/readin

**Comment by mdcfe** [comment]
A "custom world generator" has a very large scope and to cover even a small number of possibilities that server owners might want, it would require more time and effort than it would be worth, as there are already a number of worldgen plugins on SpigotMC and BukkitDev. Most servers either won't need custom worldgen or will already be using another plugin in which case they'd be unlikely to switch to another generator due to corruption.

Your best bet is probably to generate a single player world with the settings you want and then copy it to your server and load it, or to just give some 1.11-compatible plugins a try.
