### ISSUE TITLE
How do i use EssentialsX with PermissionsEX?

### ISSUE THREAD

**Issue by fuzzyloops** [EssentialsX/Essentials#1482]
EssentialsX version (`/essentials`): 2.0.1

Server software (`/version`): spigot1.12

EssentialsX config (if applicable): https://pastebin.com/pgGT9QDh

So i use PermissionsEX for my permissions plugin and i really need EssentialsX
I could use PEX with Essentials and since i upgraded it doesn't work please help

-Hunter

**Comment by smmmadden** [comment]
@DropSuit you posted the configuration file, but didn't post anything about what the issue is or the version of Essentials you are using.  Did this setup work previously to some update or is this the first time you're trying to get it to work?  Do you have a screen shot of whatever the problem is and a startup log showing what the console is writing out during the startup?

**Comment by mdcfe** [comment]
@DropSuit Please run `/essentials` and `/version` and post the output here. In addition, could you clarify what "doesn't work"?

**Comment by LaxWasHere** [comment]
Due to recent events, I, LaxWasHere recommends the use of [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) instead of PermissionsEx.

**Comment by smmmadden** [comment]
@LaxWasHere why do you say "Due to recent events"?  PermissionsEx works perfectly fine for servers up-to 1.12.x and nothing indicates otherwise.  Once @DropSuit provides more details into what is wrong, we can answer his question to why it doesn't work for him.

**Comment by mdcfe** [comment]
@smmmadden Recent events, as in the state of PermissionsEx's support.

@LaxWasHere I don't think it's fair to suggest people switch permissions plugins due to that incident alone, especially considering that we don't know the issue yet and switching plugins often causes greater headaches for people.

**Comment by smmmadden** [comment]
@md678685 I understand that part, what I don't see in this statement is what's wrong with the support?  I've looked at the plugin page and the developer(s) are actively answering questions on the plugin which means they are still supporting it.  So if someone knows something otherwise, I was asking what 'recent events' are there to make that comment?

**Comment by mdcfe** [comment]
@smmmadden Support for PEX is provided by one individual (*not* a developer) who recently responded inappropriately to an bug report. However, this is **entirely off-topic** for EssentialsX support and I'd rather we stayed on the topic of @DropSuit's issue.

**Comment by smmmadden** [comment]
wow - I agree now after finding/reading that post in question.  Hopefully we can get the details to help @DropSuit which I'm more than happy to pitch in. :-)

**Comment by Stormbow** [comment]
@DropSuit asked this question on the PEX page, received a reply within about 30 minutes, and closed the ticket himself— without comment —11 days ago (as of this post).  He has received a considerable amount of help with PermissionsEx previously— in one ticket containing more than 100 posts —and hasn't been shut out or ignored in the slightest.

**Comment by mdcfe** [comment]
@Stormbow DropSuit did not ask about making EssentialsX itself "work" on the PEX tracker. As far as I can see, the two issues are not directly related. Please don't bring this over here - it's not needed nor wanted.

**Comment by Stormbow** [comment]
> Please don't bring this over here - it's not needed nor wanted.

Interesting that you didn't tell anyone else that in this thread, and you also commented on it unnecessarily.

Unsubscribed.  Don't waste your time replying to me.

**Comment by SupaHam** [comment]
@DropSuit Please ignore most of these replies and reply the @md678685's initial request
>Please run /essentials and /version and post the output here. In addition, could you clarify what "doesn't work"?

**Comment by zml2008** [comment]
why is there drama here im not sure an actual question was even asked yet. if yall cant calm down or find someone to take over the plugin/deal with the drama im just going to fully shut down PEX bc i dont need this in my life.

**Comment by smmmadden** [comment]
EssentialsX is supported by developers and contributors like me and many others who are simply trying to help those who need it.  The same goes for PEX, it is supported by a large community and some of us are more active than others.  We ALL also provide this support for FREE.  👍 

The original post above stated that EssentialsX and PEX were not working, but the user neglected to provide any evidence into what exactly isn't working.  We've asked multiple times for it and if not provided, the issue will most likely be closed (at this point, that's what I suggest).  I can tell you I use PEX with EssentialsX and they both support 1.12.1 BungeeCord and Spigot Servers (my configuration) without any issues.  They work on other servers as well, but I can only attest to this.  Hope this helps.
-Steve

**Comment by fuzzyloops** [comment]
Sorry any one who posted i wasn't getting notifications my problem is when i make a rank example Owner i make a prefix [&4Owner&b] and then when i apply the rank to myself it does not show when i type or any thing else i do

**Comment by fuzzyloops** [comment]
Or another way to say it instead of my name being [&4Owner]&bSoulHunter2005 it is  &fSoulHunter2005

**Comment by LaxWasHere** [comment]
Do you have a chat plugin?
Do you have vault installed?

**Comment by fuzzyloops** [comment]
yes i have vault and pex as a chat plugin

**Comment by smmmadden** [comment]
PEX is PermissionsEx, not a chat plugin.  Can you please post a server startup log so that we can see what plugins are loading, which ones may be in conflict and know if there are other issues that is causing your problem.  Not seeing what the logs are reporting only means we guess as to what the problem might be.  Post the server log to pastebin or some other site and put the link here.  Thanks!

**Comment by fuzzyloops** [comment]
okay i will launch my server

**Comment by fuzzyloops** [comment]
https://pastebin.com/a2gRYCZs here is my start up log

**Comment by smmmadden** [comment]
Thanks - that helps a lot.  Before we figure out why the name is an issue, you need to get rid of all the startup errors.  You have plugins not loading at all and that alone will make your server unstable.
Administration_Panel.jar, AdminPowerTools.jar, Factions.jar, MassiveCore.jar, DynmapPlotMe.jar, Dynmap.jar (you need version 2.5), ProtocolLib (you need 4.30 build 385), Vault (1.66 is latest), NoCheatPlus, LibDisguieses (9.5.0 is latest), AntiCheat, Gadgets, BukkitPlotGenerator, SuperBuildBattle, BedWars, Punishmental and MinigamesLib all have issues at startup.  You need to make sure all the plugins actually match the server and version you are using.  Start [here ](https://www.spigotmc.org/wiki/spigotmc-compatible-plugins-by-release/)with your investigation for getting updates.  Also, the latest Java version is 1.8.0_141, so that should also be updated.

Once you get a clean startup - let us know if the reported issue gets resolved (which I suspect it will). :-)

Steve

**Comment by fuzzyloops** [comment]
okay i have to go to bed i will do this tomorrow

**Comment by mdcfe** [comment]
You need to install a version of EssentialsXChat matching your version of EssentialsX to format chat according to the `Essentials/config.yml` chat format settings. 

You need a chat *formatting* plugin to use Vault prefixes and suffixes - when Vault says that PermissionsEx is a "chat plugin", it's referring to the fact that PEX provides prefixes and suffixes for users that *formatting* plugins like EssentialsXChat can use through Vault.

Also, please update your plugins (ProtocolLib, Lib's Disguises) or switch to either maintained versions of them or alternatives to them. It should help fix other issues you have on your server. However, these are not directly related to the issue at hand and there is little direct help we can provide for them here.

**Comment by fuzzyloops** [comment]
i am using a server host called Aternos it is free and when i installed essentialsx it didn't give essentialsxchat

**Comment by fuzzyloops** [comment]
Never mind i believe i got a fake or reposted essentialsx i will post again if i need help

**Comment by mdcfe** [comment]
To my knowledge, Aternos still doesn't provide EssentialsXChat or other modules, despite multiple requests for it.

**Comment by fuzzyloops** [comment]
they need to add it how ever i did have essentials (the normal older version) and it did work i thought essentialsx and essentials was pretty much the same thing

**Comment by smmmadden** [comment]
installing EssentialsChat is only one small part of the problem.  The main issue based on the logs you provided show that at least 17 of the plugins are failing to start for a variety of reasons.  

Try to get your server startup so you don't have any errors or warnings first.  Upgrade all the plugins that are required for using 1.12.x servers.  That's the first step.

**Comment by fuzzyloops** [comment]
i have a quick question about server hosting is there one better then aternos or is aternos good i don't no much about them but i also don't have the money to pay for one

**Comment by smmmadden** [comment]
I host my own so I have full control over everything without all the headaches or financial costs that go with it.  

Check out other servers and hosting options at https://www.craftservers.net and http://www.minecraftforum.net/servers  There are many sites out there, but this will give you an idea where to go.  These two servers are also two I use for player voting and rewards. :-)

**Comment by mdcfe** [comment]
Aternos has a limited selection of plugins, and they often seem to be out-of-date anyway. For a low budget, I would suggest looking for a cheap VPS, however they are much harder to set up than a shared host with a panel like Aternos.

@smmmadden The only plugins that are causing this specific issue are PEX and EssentialsX. We don't support the other plugins here, and unless we can see a stack trace directly concerning EssX and another plugin there is nothing to suggest they are causing this problem.

**Comment by fuzzyloops** [comment]
i don't have any money (i'm 12) i decided to switch back to the original essentials it actually gives essentials chat

**Comment by smmmadden** [comment]
understood - the advice given to DropSuit was there is more issues going on with the server than just this one.  

DropSuit - If you want to get into how servers work for Minecraft and how to extend them using plugins or mods, you can find a wealth of information on this using google search.  It is very technically challenging even for folks like us that have been doing this for decades. :-)  

Otherwise, you'll need a server administrator who can support you to clear up the problems you're facing with the existing setup so it works properly.  If a server owner cannot get a clean startup (no exceptions or warnings), then that increases the likelyhood of the software not working as you expect.  Start from the top of the logs and work your way down, one plugin at a time.
