### ISSUE TITLE
Resetting balances keeps money in trade signs

### ISSUE THREAD

**Issue by Nikokku** [EssentialsX/Essentials#1494]
When resetting the balances of players in any way with /eco reset, it let's them keep the money that might be left in their [Trade] shops from purchased items.

That makes it difficult if you want to reset the economy because of inflation but then the players just get money from the trade shops which might be more then they should have anymore.

**Comment by mdcfe** [comment]
I believe this would require tracking where all the signs are in the world, like other issues that involve sign management.

**Comment by pop4959** [comment]
I don't really see the validity of this issue, since if you are resetting the economy, you would also need to reset the world or other possessions of players. Otherwise, yes, of course they can take money out of their signs, or just continue to sell what they already have. If you really have some reason to want to track the trade signs, you might be able to do it with another plugin.
