### ISSUE TITLE
EssentialsX protect on emergency mode?

### ISSUE THREAD

**Issue by DrOreo002** [EssentialsX/Essentials#1517]
27.08 09:25:57 [Server] INFO Enabling EssentialsProtect v2.0.1-b527
27.08 09:25:57 [Server] ERROR Essentials not installed or failed to load. Essenials Protect is in emergency mode now.

??, I have installed the essentialsX. But still the essentials protect is not working, and people cant break block on the server. Even me

**Comment by mdcfe** [comment]
Can you run `/version Essentials` and then `/version EssentialsProtect` and paste the output here?

Also, could you paste your config on [Gist](https://gist.github.com/)?

**Comment by DrOreo002** [comment]
Config : https://gist.github.com/DrOreo002/7198b93d232511281151ff092c4422bc
![essentials](https://user-images.githubusercontent.com/26141583/29748074-3ba0fe34-8b40-11e7-9041-463c6a068533.png)

Oh and essentials protect is the same version like the Essentials

**Comment by mdcfe** [comment]
Can you start and stop your server and then [paste the created log](https://gist.github.com/)?

**Comment by UDUT** [comment]
Im currently on version 2.0.1-b528 for all, and is facing the same issue, here is my server log.

Server Log: https://gist.github.com/UDUT/e7425ebb65c11f038ecc4e545447c660

**Comment by mdcfe** [comment]
Thanks @UDUT - this looks like an EssentialsProtect bug. I'll take a look at it.

**Comment by md678685** [comment]
Thanks @UDUT - this looks like an EssentialsProtect bug. I'll take a look at it.

**Comment by DrOreo002** [comment]
well, I'll wait for it to be fixed. Please remind me if its fixed okay?

**Comment by mdcfe** [comment]
For some reason, EssentialsProtect is loading before Essentials. This appears to be an EssentialsX issue, though I don't know why this has only started to occur recently - there are no recent changes in EssentialsX nor Spigot that should affect this.

My only hint is that EssentialsProtect [softdepends on Essentials](https://github.com/drtshock/Essentials/blob/2.x/EssentialsProtect/src/plugin.yml#L9), [unlike](https://github.com/drtshock/Essentials/blob/2.x/EssentialsAntiBuild/src/plugin.yml#L9) [all](https://github.com/drtshock/Essentials/blob/2.x/EssentialsChat/src/plugin.yml#L9) [the](https://github.com/drtshock/Essentials/blob/2.x/EssentialsGeoIP/src/plugin.yml#L9) [other](https://github.com/drtshock/Essentials/blob/2.x/EssentialsSpawn/src/plugin.yml#L9) Essentials [modules](https://github.com/drtshock/Essentials/blob/2.x/EssentialsXMPP/src/plugin.yml#L9) which depend on Essentials. This [is probably deliberate](https://github.com/drtshock/Essentials/commit/5e2123c91e44b9ea0a2aa61ca8d889e506274875#diff-7783aa7e5fe10d7adade0e8b24e01373) so that if something goes wrong in Essentials, EssentialsProtect will go into emergency mode to prevent damage to the server rather than disabling itself and allowing anything to happen on the server.

@DrOreo002 @UDUT Could you both update Spigot and report back if the issue is still present?

@DrOreo002 We still need a console log of starting and stopping the server to be certain that you're experiencing the same issue as @UDUT.

Edit: I haven't yet been able to replicate this on Windows 10 with the following Java version:
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
and with EssentialsX, EssXChat, EssXSpawn and EssXProtect b528 installed on Spigot `git-Spigot-edd0396-2a927e8`.

**Comment by UDUT** [comment]
http://prntscr.com/geecds

@md678685 Mine is currently at the latest ver

**Comment by mdcfe** [comment]
@UDUT What operating system and version of Java (`java -version` in a terminal, *not* your Spigot server console) are you running?

**Comment by UDUT** [comment]
@md678685 
OS: Windows 10 Pro

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by UDUT** [comment]
@md678685 hmm i see that you tested it on a version thats 4 commit behind, how do I rollback to that commit? I could give it a try on that version and see if its working. And is there any off-chance that this might be caused by other plugins?

**Comment by mdcfe** [comment]
@UDUT I've updated to the latest version and added a few plugins from your console log (GUIShop, ServerSigns, SilkSpawners, Vault) and still can't replicate the issue. There is a strong chance it's caused by other plugins, which would be easier to confirm if we get a startup log from @DrOreo002.

AsyncWorldEditInjector might also be affecting the enable order, since StackMob should load after WorldGuard and therefore WorldEdit but instead is the first to be enabled, followed by AsyncWorldEditInjector. Statz also hooks EssentialsX but loads before it, though it doesn't softdepend on Essentials anyway.

**Comment by UDUT** [comment]
@md678685 I think you might be right, I removed both Asyncworldedit and Asyncworldeditinjector.

New Log: https://gist.github.com/UDUT/e941ef56ac88c2594aeb279d9b34762b

**Comment by mdcfe** [comment]
It's likely a flaw with Bukkit's handling of `depends`/`softdepends`, and I don't think there's any "fix" as such for this - it would be best to try removing and readding plugins on a test server until the issue stops, looking at each plugin's `plugin.yml` inside the jar to see which plugins depend on which.

@UDUT As a test, could you try readding AsyncWorldEdit, adding `ZZ` to the beginning of the AsyncWorldEdit jar names and adding `AA` to the beginning of the EssentialsX jar names?

**Comment by UDUT** [comment]
@md678685  New Log with the AA ZZ renames as requested. Seem to work as well.

New Log: https://gist.github.com/UDUT/3494f252a950df7a4f1946bd593ab63c

**Comment by DrOreo002** [comment]
Hey, sorry for the late reply. This is my server startup log : https://gist.github.com/DrOreo002/bb1fb3c703588be68d9aa9ea3c3a6736

**Comment by mdcfe** [comment]
@DrOreo002 As suggested to UDUT, could you try renaming the EssentialsX jars by adding AA to the start of those jars? Alternatively, try removing all your plugins then readding them one by one until the issue reappears.

**Comment by DrOreo002** [comment]
Alright, its working now. Thanks!

**Comment by sOxTw** [comment]
I just solved this problem without removing any plugin from my server, and without renaming anything.

The only thing to do is open with WinRar to `"EssentialsProtect"`, edit **plugin.yml** to add the following line:

`softdepend: [Essentials]`

save the file, wait for it to load in the plugin and start the server.

**Comment by mdcfe** [comment]
@sOxTw This line is already there:

https://github.com/EssentialsX/Essentials/blob/827217823efc9965d68809761bddc5db94a84aad/EssentialsProtect/src/plugin.yml#L9
