### ISSUE TITLE
Inventory duplication bug & enderchest suggestion

### ISSUE THREAD

**Issue by Rukes** [EssentialsX/Essentials#1566]
EssentialsX version (`/essentials`): Essentials version 2.0.1-b525

Server software (`/version`): This server is running CraftBukkit version git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

Well, problem is then if I open own inventory (using invsee feature), I can get any item from copied inventory to real inventory and this cause item duplication. Can you prevent self inventory open?
[Here is video showcase](https://www.youtube.com/watch?v=fCpb8VV2TnI&feature=youtu.be).

And another suggestion, can you add permission "essentials.enderchest.preventmodify" how is it like invsee?

Thanks :smile:

**Comment by Rukes** [comment]
@md678685 how about this?

**Comment by mdcfe** [comment]
I'm not sure that this is something that needs to be fixed since this is intended to be a moderation tool not a player-facing feature, nor does it seem likely that this even can be fixed - the only thing EssentialsX does is ask Spigot to open the requested player's inventory as a chest inventory to the user that ran the command, but all of the inventory handling itself is controlled by Spigot and not EssentialsX.

If someone else could confirm that this bug does indeed happen, it would be greatly appreciated.

**Comment by pop4959** [comment]
Please try replicating this on the latest version of Essentials, without any other plugins (except a supported permission plugin). Seems no one else has come across this issue or reported it since over 2 years ago, so it probably isn't a normal occurrence (or has been fixed already).
