### ISSUE TITLE
teleport cooldown

### ISSUE THREAD

**Issue by seema84** [EssentialsX/Essentials#1578]
the message for teleport cooldown does not always work
if i set a cooldown on 2 seconds, sometime i get the right message with 2 seconds but sometimes i get a message with 1 second (that is false)

EssentialsX version (`/essentials`): 
Build 532
Server software (`/version`): 
Spigot 1.12.2

**Comment by pop4959** [comment]
Please create a new issue on the latest version of Essentials if you are still encountering this issue. We'd need more info to look into this. Also, the time remaining may be rounded so it is very possible that 1.9 seconds is being shown as 1 second (since it doesn't show decimals). This would be normal.
