### ISSUE TITLE
Error on Essentials 2x snapshot paperspigot

### ISSUE THREAD

**Issue by MineServidorCraft** [EssentialsX/Essentials#1617]
Error: https://pastebin.com/PEKQLxQd

EssentialsX version (`/essentials`): Essentials v2.0.1-bSNAPSHOT

Server software (`/version`): Paperspigot b1155

EssentialsX config (if applicable):  https://pastebin.com/TLZmgAL9

**Comment by mdcfe** [comment]
Can this be replicated on both the latest version of Spigot and the latest version of Paper using the latest version of EssentialsX?

**Comment by MineServidorCraft** [comment]
I really do not know, I have the stable version of paperspigot b1155 which is from 1.12. I have had several stable versions of essentialsX but in all of them I got this same error. I also have ViaVersion for users to enter with 1.12.2. Would it have something to do? I can not give much information since this error has been caused when there has been nobody, when there were people and when they used commands. That is, it has happened on many occasions and it seems I do not see that it is executing this error.

**Comment by smmmadden** [comment]
1. What build version of EssentialsX 2.0.1 are you using?  The latest is build 546.  
2. If you're not using the latest, try with that and see if it persists.  It could also be another plugin causing the error making it look like EssX.  
3. Can you provide a startup log so that we can see if:
    a) there are conflicts (some plugins can break other plugins)
    b) if there are failures that would need fixing first (to rule out another plugin)
    c) startup process is good/bad (helps towards finding the root cause)
4. One important question - has this EVER worked and if it has what has changed since that time?
5. Finally, are you using the[ latest plugins for the 1.12.x](https://www.spigotmc.org/wiki/spigotmc-compatible-plugins-by-release/) server(s) you use?  This too can make the server unstable if not kept current.

**Comment by mdcfe** [comment]
Could you try disabling ViaVersion (and ProtocolLib, if installed)?

**Comment by mdcfe** [comment]
Closing due to lack of response; if this is still a problem, please reopen the issue, following the given troubleshooting steps and including the relevant info.
