### ISSUE TITLE
Undo Rather than Confirm

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1644]
Hm, is this the place for feature requests? I don't know. Either way, rather than having to do the clear command twice there should be the ability to undo the clearing of inventory. It would speed up clearing a lot while still preventing loss of important items!

Thanks,
James.

**Comment by mdcfe** [comment]
I don't see the point of this. The confirmation is there to make sure you're absolutely certain about wiping your inventory, so that's your chance to make sure you don't lose important items. If that *really* takes too long, you can toggle the confirmation, but then you have even less of a chance to check your inventory before you clear it.

I'm not saying undo functionality will never happen, but it's unlikely to be worked on.

**Comment by ghost** [comment]
Well it's not like implementing such feature would be time consuming. Just a simple Map (probably with an expiration) containing the Player (or UUID) and the ItemStack[] they once had before clearing. Undoing would simply swap out the two ItemStack[] contents again. It would just be a nice feature and a fairly useful one at that.

**Comment by Kosyne** [comment]
I'd like at least a `/clearinventorynoconfirmation` so I could still use the original behavior on things like commands tied to items/buttons. That's wordy enough that no one would accidentally use that.

**Comment by mdcfe** [comment]
Closing as this isn't something we're planning to implement.
