### ISSUE TITLE
Clear command

### ISSUE THREAD

**Issue by partydragen** [EssentialsX/Essentials#1667]
Hey can there be a config option to disable clear confirmation command?

It have broke my DeluxeMenus shop :/ since its no longer able to run clear 
And i plan to release in 1 hour RIP

guess i need to change back a version before the clear update

**Comment by smmmadden** [comment]
have you tried to add a command alias in your commands.yml file?

**Comment by MineServidorCraft** [comment]
I have the same problem. I have some problem but i don't know what plugin give me this command. A month ago users could change bedrocks (which cost 20k in the sv) per permissions, the elevator etc ... we used several blocks of commands, to detect the bedrocks and delete them, then we gave permission. To erase we used the clear @p 7 N (N = number of bedrocks). Now he does not let us use the clear and the users get the permissions for free. And this is because the clear now needs to be confirmed or deactivated. It can be deactivated by individual but not in general. Does anyone know how to remove it or in some config put by default that no confirmation is needed? https://imgur.com/a/DSomA

**Comment by DrewAMitchell** [comment]
https://github.com/EssentialsX/Essentials/issues/1676 Duplicate

**Comment by mdcfe** [comment]
Use the [vanilla `minecraft:clear` command](https://minecraft.gamepedia.com/Commands/clear) instead - you can optionally alias `clear` to `minecraft:clear` in your `commands.yml`, though this doesn't seem necessary for this particular use case.

**Comment by partydragen** [comment]
the minecraft clear command don't have {amount}

So it break DeluxeMenus shop,

**Comment by SupaHam** [comment]
If the player is running the command, they will get the confirmation request. They can individually toggle this behaviour by using the `/clearinventoryconfirmtoggle` or any of its aliases. This behaviour is similar to `/pay`s confirmation security, making it standard across all servers for safety against malicious intent.

If you want to avoid the confirmation, run the command as console and feed the player name to operate on.

**Comment by partydragen** [comment]
This not helps, Them bypass the shop from removing peoples items

If people don't have used /clearinventoryconfirmtoggle then them can example sell unlimited items due the shop is not able to remove the items

**Comment by SupaHam** [comment]
If you run the command as console and on a player it bypasses confirmation entirely. Run the command as console, not as player.

**Comment by DrFallen** [comment]
They are talking about command blocks. When you stand on a pressure plate and execute the command via @p it will not work as it reads "Only in-game players can use clearconfirm."

**Comment by FlippantCactus** [comment]
@SupaHam Can you add some documentation for the confirmation as I can't see anywhere to globally turn it off, or a permission node possibly should be added.

**Comment by mdcfe** [comment]
@TWSSYesterday EssentialsX has no mechanism for globally disabling this. You can find an unofficial solution [here](https://github.com/EssentialsX/Essentials/issues/1735#issuecomment-354455235), but we will not be supporting users with this build.

**Comment by DrFallen** [comment]
@md678685 Why was it changed though? I'm using b526 and it works fine without the confirm.

**Comment by FlippantCactus** [comment]
@md678685 Will there be any reason to have it added? Seems odd how it isn't part of the plugin when it seems quite core to usage. It's not game-altering enough to make me ditch the proper branch and go over to a one off though.

**Comment by ScuroK** [comment]
can you please add a config option to disable all the confirm fuctions please??? i need this to fix some bugs.

If i WOULD give permission for minecraft.command.clear players could clear other players aswell right?

**Comment by ScuroK** [comment]
@TWSSYesterday or can we just have a persmission for the toggle command and make it off by default. this would solve it aswell

**Comment by DrFallen** [comment]
They don’t really seem that intrested in fixing this tbh

**Comment by ScuroK** [comment]
typical old minecraft plugin devs... Ermm naaah its not important hmmm i will se if i find time hmm...

**Comment by DrewAMitchell** [comment]
@ScuroK Taunting them won't further your cause any further, I'll be proposing a PR soon to have the default value of confirmation configurable.

**Comment by mdcfe** [comment]
@DrFallen @ScuroK We've had a lot of private discussion on what the best option is for us, as all of them have tradeoffs. Some of these options include:

## Disable confirmations by default
Exactly what it says on the tin, but this defeats the point of having the feature as not many people will notice that it exists, and so few people will actually benefit from it.

## Remove confirmations
It technically *would* make `/pay` and `/clear` easier to deal with, but this is obviously a regression and restores the original problems.

## Have a server-wide setting instead of a per-user one
This would allow server admins to disable confirmations, but wouldn't allow individual users to toggle them on or off.

## Have per-user toggles, and a server-wide default
This would allow servers to choose whether `/pay` and `/clear` confirmations are on by default for each user, but still allow users to manually enable or disable confirmations for themselves as desired. This may be useful if server admins can't be bothered to set up their server in a way that works for them.

## Leave as-is
This is the most likely at the moment. If you absolutely *must* be able to bypass confirmations, I would suggest creating a `commands.yml` alias that runs `/pay` or `/clear` twice and use it for *one-off occasions* (menus set up via another plugin, NPCs etc.).

**Comment by DrewAMitchell** [comment]
@md678685 I think the 2nd to last option (Have per-user toggles, and a server-wide default) is the best option... the server owners should have the choice for the server wide default, as the responsibility will fall on them if the users lose their items over it. It's just that the confirmation aspect is unexpected for most, and they're so used to it. I propose that the default (in config.yml) be confirmation enabled, but that it be configurable while the users can select what they feel comfortable with.

**Comment by mdcfe** [comment]
@Drkmaster83 I was in favour of that option as well, however it encourages server owners to take the lazy route and entirely disable a useful feature due to a single quirk that they're not used to, instead of deciding on a balanced solution to the problem.

In the case outlined in the OP, the balanced solution would be the one I gave at the bottom: create an alias that just runs `/pay` or `/clear` twice (such as `/autopay` or `/autoclear`), then use **that alias** when including it in a shop menu or some other automated means of running commands and use the **original command** when manually running them as players. That way, the server has the useful confirmation feature when players try to use the commands manually while retaining the ability to use `/pay` and `/clear` in shops, NPCs, command blocks and other automated systems.

If it's such an issue to toggle the confirmations off, then servers should be making users aware that they can disable the confirmation.

**Comment by DrFallen** [comment]
Wouldn't it just be possible to separate the two in the config one for users and one just for command blocks as I see why confirming it for users would be useful that's not the issue I have. It's just the server side even with the alias that wouldn't solve the user issue would it. You'd still end up with a null after the first clear wouldn't you?

**Comment by mdcfe** [comment]
@DrFallen I don't understand what you mean. If there's an alias that runs the command twice, it will run twice.

**Comment by DrFallen** [comment]
@md678685 I'm not even sure anymore the builds seem so weird I've had issues where it didn't understand the player. I'm not even sure if the plugin is working as intended as I updated to 569 and it didn't seem to need the confirm at all. I've not added an alias either.

**Comment by Techno3600** [comment]
Hey, I just checked out this thread and I think that it would be a good idea to make an option in the configuration.

**Comment by drtshock** [comment]
Yes we are going to add one before we post a release.

**Comment by drtshock** [comment]
Keeping the discussion here, I think having a server wide setting is the way to go with this. Perhaps we could add per user after we get some feedback of people using it.

And yes a PR would be great for this. If someone can PR it and have it default to false.

**Comment by LaxWasHere** [comment]
Here you go @drtshock https://github.com/AwesomePowered/Essentials/commit/55f622907543245675afcf26cc4b445c738bf12f

**Comment by mdcfe** [comment]
You can now [enable and disable confirmations](https://github.com/EssentialsX/Essentials/blob/7d7c58fa7c1a8e566807d4fdca2b8b1c9226b87f/Essentials/src/config.yml#L519-L523) as of the latest version of EssentialsX.
