### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by Dreadmomma** [EssentialsX/Essentials#1673]
Hi,

I am getting "WARN §4Version mismatch! Please update all Essentials jars to the same version."
 in the console of my Spigot server for Minecraft 1.12.

These are the Essential plugins I'm using:

![image](https://user-images.githubusercontent.com/34141720/33453411-7d33cc9e-d5e3-11e7-95c0-c553db70eb22.png)

Can someone please tell me what I need to do to fix this? I'm using Beastnode and it keeps going to 100% CPU Java Load so I'm trying to find things in the Console that might be causing this.

I am new to managing a Minecraft Server - I am trying to do it for some children at a local club. So if you can please give me advise for someone with no coding experience and no server managing experience, that would be great.

Thanks!

EssentialsX version (`/essentials`): 

Server software (`/version`): 

EssentialsX config (if applicable):

**Comment by NJDaeger** [comment]
When you update one jar, you should probably update the rest. I bet what you did was update EssentialsX, but not the other jars. (Chat, GeoIP, etc.). Download all the most recent versions of each plugin and the error should go away.

**Comment by Dreadmomma** [comment]
Hi - Thank you for replying so fast! I actually downloaded them all the same day / time for the first time. So they should all be the same. This is a brand new server I am trying to get up and running. It hasn't been around long enough to need updating - I only downloaded them all within the last week or so. Also, they all show being at 2.0.1 which appears to be the latest version?

**Comment by smmmadden** [comment]
2.0.1b is the version (confusing I know).  What you want to look at is the build you are using.  That has to be the same build for each of the EssentialsX plugins.

You will see the same version mismatch if you have the EssentialsExtras plugin as this is managed by a different team.  The version of that one is not going to match the EssentialsX versions so it can be ignored because the validation is checking for Essentials* to make sure they are all the same.

EssentialsExtras is an extension to homes, kits and warps to provide a GUI and multiple of each so it has a dependency of EssentialsX.

What may help you keep this straight being a new server owner, when you download the plugins, add the version or build details to the jar file (EssentialsXChat-2.0.1b546.jar) so you'll always know by looking at it if they are the same or most recent one available. :-)

**Comment by Dreadmomma** [comment]
Thank you so much! I have them all up to date and the same now.
