### ISSUE TITLE
/break and /unlimited bugs

### ISSUE THREAD

**Issue by jsgunman** [EssentialsX/Essentials#1675]
EssentialsX version (`/essentials`): 2.0.1-b488

Server software (`/version`): Spigot 1.12.2

First issue is, /break seems to be broken, as it throws NoSuchMethodError to the console. The other issue is, /unlimited is not functioning as it should, it yields 2 finite items, instead of 1 infinite item.

**Comment by wyatt-herkamp** [comment]
/break is broken. I can agree on that build. 
/unlimited does give two items? I don't think that is a major problem.
https://github.com/EssentialsX/Essentials/blob/db47460a7949c5686222b16feb3c5f4be2a8376f/Essentials/src/com/earth2me/essentials/commands/Commandunlimited.java#L71
It might be intentional to prevent a lack of items. and when re adding the item it goes to the same place every time.

**Comment by LaxWasHere** [comment]
You are running an outdated version, please download the latest essx version at https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild/

**Comment by wyatt-herkamp** [comment]
I would like to add that it works in this build. 
https://ci.akpmakes.tech/job/EssentialsX/550/
This is the latest version.
Please close the Issue so we start lessening the problems. Thank you!
