### ISSUE TITLE
About Essentials AntiBuild

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#1712]
- [x] I know this questions will mark me as a retarded, but i still want to ask though :( *prepare to facing truth*
I saw that Essentials AntiBuild got permission 
'- essentials.build.interact.<'id>
Now i change the <'id> to
'- -essentials.build.interact.54 (chest)
1/Will the player be prevented from opening chest?
For the harder question, i change it to
'- -essentials.build.interact.408 (hopper_minecart)
2/Will the player be prevented from opening hopper minecart?
For the hardest question... I use ID of entity *poker face*
'- -essentials.build.interact.103 (llama) :-1: 
3/Will the player be prevented from interacting llama? :-1: 
Hic if it's not for both 2 questions, what plugin do i need to prevent player from interacting entity?
P/s: I know i retarted :-1: don't blame me :(

**Comment by LaxWasHere** [comment]
yes

**Comment by mdcfe** [comment]
Don't worry - I wasn't too sure about how AntiBuild worked until I looked into it.

As far as I can tell:
* `-essentials.antibuild.interact.54` **will** prevent players opening a chest, as chests are blocks.
* `-essentials.build.interact.408` and `-essentials.build.interact.103` **will not** prevent players interacting with hopper minecarts or llamas, as they are both entities.

I'm not sure what plugins exist that prevent interacting with entities - perhaps a global flag in WorldGuard may be useful.

**Comment by smmmadden** [comment]
There may be some that do that for you.  Take a look at the spreadsheet I manage for many plugins [here](https://docs.google.com/spreadsheets/d/1phbsKtVQ-3Eoa422uLi7xqPIK6c9yNsSJXjmwpeavZA/edit#gid=0).  Specifically around the LWC (entity locking).

**Comment by mdcfe** [comment]
@smmmadden I purposely didn't mention the LWC entity locking fork (as well as GriefPrevention) as its behaviour is not what the OP appeared to be looking for - it allows individual players to claim and protect specific blocks and entities, while AntiBuild is intended to allow for server-wide blocking, and the OP appeared to be looking for AntiBuild-like entity interaction prevention. As it turns out, WorldGuard doesn't appear to have flags to block interaction with specific entities either.

**Comment by mdcfe** [comment]
Closing due to lack of response. If you have any further questions about AntiBuild, feel free to reopen the issue.
