### ISSUE TITLE
Suggestion for command-cooldowns

### ISSUE THREAD

**Issue by ArtelGG** [EssentialsX/Essentials#1715]
**[SUGGESTION]**
Make the command cooldowns (`command-cooldowns:`) have an option to continue through death.
*(As of right now the cooldowns are reset on death)*

Perhaps something like:
```
command-cooldowns:
  feed: 10:true # Boolean being "carry-through-death"
```

EssentialsX version: Latest development build (2.0.1-b553)
Server version: TacoSpigot 1.8.8 b28

**Comment by mishyy** [comment]
It does not appear that cooldowns are at all reset upon death, and there have been no changes relating to cooldowns between your version and the latest source (which I am testing and comparing against).
As it turns out, it appears all cooldowns are stored until they expire or the server shuts down (unless cooldown persistency is enabled in the configuration file).

**Comment by drtshock** [comment]
so not an issue <3
