### ISSUE TITLE
Enchants

### ISSUE THREAD

**Issue by SeruhioX** [EssentialsX/Essentials#1738]
EssentialsX version (run `/essentials`): 

2.0.1-b560

Server software (run `/version`): 

PaperSpigot 1.12.2 #1244

EssentialsX config (`plugins/Essentials/config.yml`): 

https://hastebin.com/omaropiyot.coffeescript

Details:

I recently upgraded to a version of EssentialsX (the latest), since I had not updated it since August.

I have a problem with the enchantments, and that was before they worked as follows:

/give player 276 1 name:&6Sword lore:&bA sharpness:5 durability:3 fire:2 looting:3

But now the enchantments do not work and you have to put them in front of the tag "name:", this causes lots of obsolete configurations that use "give"

**Comment by mdcfe** [comment]
For the moment, you need to put `lore` at the end of item metadata in kits and `/give`, due to a recent fix for a kit-related bug.

If you're repeatedly using predefined `/give` commands, I would recommend moving them to a kit, which will make them much more maintainable in the long run as they can be easily edited with minimal hassle, as well as allowing for meaningful and memorable names.
