### ISSUE TITLE
individual jail permissions for /togglejail

### ISSUE THREAD

**Issue by fisho0** [EssentialsX/Essentials#1751]
i would like be able to give /togglejail permissions for individual jails, rather than all of them:  something along the lines of essentials.togglejail.jail01 .  from my own research and confirmation in the essentials irc channel, it seems this is not possible.

would u consider adding this?

it would be great to allow jail permission per player group on an individual map, allowing players to take control over their area, with jails, and not have blanket perms across an entire jail system.

i hope u will consider this addition.

#fishsurvives

**Comment by pop4959** [comment]
Someone made an attempt to address your issue, but it turns out it was complicated, and also didn't really fully cover your use case. I don't think this is something that is likely to make its way into Essentials, especially with the breaking changes that are effectively required for permissions, and also the complexity of controlling this per region when Essentials doesn't currently have any support for that built-in. Not sure if you are still looking for something like this (as it has in fact been 2+ years), but I would advise finding another plugin, or simply restrict jail features to moderators, as the command is intended.
