### ISSUE TITLE
REQUEST: Offline support for /Whois and a question.

### ISSUE THREAD

**Issue by Remski01** [EssentialsX/Essentials#1766]
I have a request. 

Can offline support be added on /whois? So that we can look players up that are offline.

And also. 

What the permission to bypass 

    # Prevent the spawning of creatures.
    spawn:

If there is not, Can this be added or just something that can bypass it.

Note: I know. This is not an Issue. But i dont understand how "Pull request" works. Sorry

**Comment by mdcfe** [comment]
No worries about posting it here - "Issues" are GitHub's name for support tickets, so feature requests, bugs and questions are all accepted here.

Regarding the first suggestion, that's a valid feature request and we'll look into it when possible.

---

Regarding a bypass permission for EssentialsX Protect:

EssentialsX Protect blocks certain actions and events as configured, including spawning of specific mobs. However, this does not take into account the reason for the mob being spawned, as Bukkit doesn't provide a way for us to tell who spawned the mob, so we can't run any permissions checks to allow the mob to spawn.

The only feasible way to allow this that I can think of at the moment is to add metadata including the player's UUID or username to the mob before spawning it (for example, in `/spawnmob`), then check for that metadata before cancelling the spawn in EssentialsXProtect.

**Comment by caojohnny** [comment]
I'm quite sure that you can use interact event to check mob spawns yea?

**Comment by mdcfe** [comment]
@AgentTroll PlayerInteractEvents aren't fired alongside the spawning of the mob unless a player interaction caused it, so only spawn eggs would be caught here.

**Comment by TheLittleYH** [comment]
I know this is old but I want the /whois offline player support too, is it coming anytime soon?

**Comment by mdcfe** [comment]
@TheLittleYH We're not working on it right now, but it may be added in the future. Others are welcome to PR this.

**Comment by pop4959** [comment]
@Remski01 What did you want to see out of `/whois`? There has been discussion about it lately, although many features of the command are not possible to do for offline players are the moment... but some may be able to be incorporated into `/seen`. If you can give more specifics, that would be great. I'll also take no response as meaning you're not interested in this anymore.

**Comment by I-Knight-I** [comment]
@pop4959 Obviously I'm not the OP but, since it's possible he might not reply, thought I'd add my suggestions:

- Nick
- UUID
- Logout Location
- Playtime
- Money
- IP Address
- Last Login
- First Login
* (Maybe) Jail
* (Maybe) Muted

All those would be greatly appreciated and, I think, possible to fetch for the offline player. I don't think health, hunger, godmode, flying, etc is necessary or feasible with offline players. 

The (Maybe) ones I've included because, if I recall correctly, those are stored in the player's userdata folder within EssentialsX so should be easy to add. Correct me if I'm wrong.

**Comment by Chew** [comment]
> Location
> Logout Location

Probably don't need both, they're the same thing, right? Otherwise should be feasible. Not sure if we store first login though.
AFK doesn't matter, they're not on. Jailed and muted sound good too since that survives longer than they're on.

**Comment by I-Knight-I** [comment]
Yeah, I have no idea why I put both logout location + location lol. Same for AFK. 

I think I did /seen on myself and wrote what I saw without thinking too much into it. 
First login would be appreciated though. I feel like I have seen that somewhere but maybe I'm getting confused with another plugin.

**Comment by Remski01** [comment]
Hello.

Going to be honest, we dont use EssX anymore. So i myself have no interest in this anyways anymore. **However**, Adding support of offline lookups should always be added. 

As note, i have unsubbed from the ticket.

**Comment by pop4959** [comment]
There was already a PR open for this but I found that adding offline player support to /whois was not great, not because it was necessarily a bad idea, but because as @B-Knight49 correctly re-evaluated, not everything that /whois displays can be supported for offline players. This makes it extremely confusing to use, since some information is only shown for online players, and some information is only shown for offline players.

The better option here is to add more information to the /seen command, which is intended to be used only for offline players (whereas /whois is intended to be used only for online players). I think keeping that separation would be ideal, since otherwise there is really no purpose in keeping both commands.

Feel free to create a new issue suggesting for additional information to be added to /seen. I will be closing this one to avoid further confusion.
