### ISSUE TITLE
/lightning bug

### ISSUE THREAD

**Issue by Draevon** [EssentialsX/Essentials#1828]
whenever you run the /lightning command it brings up errors. I'm using a fresh install of essentials and spigot. The link shows the logs needed:
https://gist.github.com/anonymous/d08392f089fda80252c4137c3d38cede

**Comment by LaxWasHere** [comment]
Please download the latest EssentialsX builds at https://ci.ender.zone/job/EssentialsX/

**Comment by Draevon** [comment]
I do have the latest version. Downloaded from that site

**Comment by LaxWasHere** [comment]
No you do not. Please update.

**Comment by Draevon** [comment]
So why on the spigot page do you not have the correct download? Seems kindof counter intuitive to not have it there and have an external download.

**Comment by mdcfe** [comment]
We post stable builds on Spigot. The latest stable build has a known error, which is fixed in newer development builds, but these aren't guaranteed to be stable or to even work at all, so we do not link to these on Spigot.

If you downloaded the latest version from the build server, why are you complaining about the Spigot build?
