### ISSUE TITLE
Sky twitching

### ISSUE THREAD

**Issue by BBoyJD10** [EssentialsX/Essentials#1831]
On latest dev version the sky twitches and isnt stable

**Comment by LaxWasHere** [comment]
The issue template exist for a reason, please follow it. With that said I doubt essentials is the one causing your issue.
---
Don't put anything inside this block, as it won't be included in the issue.

If you have a question about EssentialsX, it may be more useful to join our
Discord server: https://discord.gg/F7gexAQ

You can ignore the template if suggesting a feature; otherwise, read on:
1.  Fill out the template, running the commands either in the console or 
    as a player. Don't simply put "latest" or we will ignore it.
2.  When linking files, do not attach them to the post! Paste them on 
    https://gist.github.com/, then paste a link to them in the relevant parts
    of the template. Avoid using Hastebin or Pastebin, as files are deleted
    after a period of time.
3.  If you are reporting an issue with lag, please include a timings report.
4.  If you are reporting an issue with messages or in-game behaviour, please
    include screenshots detailing the problem.
5.  Include a description and any other details that may be helpful under
    "Details:".
6.  Delete this line and all above lines before posting your issue

EssentialsX version (run `/essentials`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

EssentialsX config (`plugins/Essentials/config.yml`): 

Details:

**Comment by BBoyJD10** [comment]
EssentialsX version (run /essentials): 2.0.1-b593

Server software (run /version): Spigot 1.12.2 B1591

Server (logs/latest.log):

EssentialsX config (plugins/Essentials/config.yml):

Details: Sky twitches back and forth

**Comment by drtshock** [comment]
You still didn't fill in the info we wanted :( We want the actual server log.

**Comment by mdcfe** [comment]
This doesn't look like an EssentialsX issue.

Please **paste your server log on [Gist](https://gist.github.com)** then link it here, otherwise we can't help you.
