### ISSUE TITLE
Option to disable backing into specified worlds.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#1850]
With ```register-back-in-listener: true``` enabled, players can ```/back``` from any plugin teleport event. This includes arenas that teleport players into lounges and battlefields. Would it be possible to have an option to specify worlds players _can't_ ```/back``` into without outright disabling the listener?

**Comment by mdcfe** [comment]
I think this might be better suited to a permission.

One way could be to have a `essentials.back.listen` permission that a player needs for the listener to set their previous location (defaulting to true to prevent breakage). It could then be disabled per-context as needed (for example, in a specific world) to prevent players being able to `/back` into the world.

Alternatively, we could implement a `essentials.back.into.<world>` permission that a player would need in order to do `/back` into that world (again, defaulting to true to avoid breaking existing setups).

@SupaHam @drtshock Thoughts on this?

**Comment by drtshock** [comment]
Yeah I think that would be a good implementation if it was just that you could negate it. Otherwise, we'd be changing things pretty drastically. 

Perhaps also an option to allow /back to the same world?

**Comment by mdcfe** [comment]
We would most likely have to register the perms as enabled by default.

I'd assume that if someone wanted to disable `/back` into the same world, they would negate the respective permission for that world only.

Something else to consider is whether we should even set the back location if they don't have the permission - it would be convenient not to, but perms can change based on context.

**Comment by mdcfe** [comment]
Closing as this was implemented by #1948.
