### ISSUE TITLE
Can I actually get some help?

### ISSUE THREAD

**Issue by FlameHeroDev** [EssentialsX/Essentials#1907]
Information
Full output of /ess version:

[02:06:13 WARN]: config broken for xmpp
[02:06:13 INFO]: [Essentials] Using locale en_US
[02:06:13 INFO]: [MW] Essentials has been reloaded. Version: 2.0.1-b488
Server log (upload logs/latest.log to Gist):
https://gist.github.com/FlameHeroDev/9849dad2ebccc57668e2e7bd104183db
EssentialsX config (upload plugins/Essentials/config.yml to Gist):
https://gist.github.com/FlameHeroDev/2cce8a82c34dd65de16e3851245f3f6a

Details
Server starts, essspawn and xmpp start logging warns and errors to console, 1 minute later server crashes. It's a localhost where I'm testing servers, so don't just assume that 'I should buy plugins', they're just there for testing before I actually purchase them. And can you guys actually help fix the issue?

**Comment by mdcfe** [comment]
Evaluation isn't an excuse for piracy. Never, ever, *ever* use cracked plugins because they are modified copies of the original and may be malware, not to mention that you would be downloading an illegal copy of said plugin and depriving the hard-working author of their income. If you want to test a plugin before buying it, ask the author for an evaluation copy.

---

Did you try [reading](https://gist.github.com/FlameHeroDev/9849dad2ebccc57668e2e7bd104183db#file-gistfile1-txt-L314) your [log](https://gist.github.com/FlameHeroDev/9849dad2ebccc57668e2e7bd104183db#file-gistfile1-txt-L315-L320) and following the instructions it gives? *(Hint: if you did, you wouldn't be getting [this error](https://gist.github.com/FlameHeroDev/9849dad2ebccc57668e2e7bd104183db#file-gistfile1-txt-L994).)*

Did you look up [what each jar even is](http://wiki.mc-ess.net/wiki/Breakdown), whether you need them all or [how to use them](http://wiki.mc-ess.net/wiki/XMPP)? *(Hint: if you did, you wouldn't be getting [this error](https://gist.github.com/FlameHeroDev/9849dad2ebccc57668e2e7bd104183db#file-gistfile1-txt-L982).)*
