### ISSUE TITLE
essentials.feed/heal.cooldown.bypass permissions being ignored

### ISSUE THREAD

**Issue by mrcoffee1026** [EssentialsX/Essentials#1920]
### Information

Full output of `/ess version`:
2.0.1-b601

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
  feed: 14400 # 4 hour cooldown
  heal: 21600 # 6 hour cooldown

### Details
Permissions applied to user:
- essentials.feed.cooldown.bypass
- essentials.heal.cooldown.bypass

Describe your issue here.
User still required to sait the cooldown amounts between uses of /heal and /feed.

**Comment by caojohnny** [comment]
Sounds like a problem with your permissions plugin

**Comment by mrcoffee1026** [comment]
Then it would be the only permission that is giving luckperms problems?? I don't think so.

**Comment by mdcfe** [comment]
Run `/ess debug`, then paste the **full console output** when a player with the bypass permission runs a command with a cooldown while the cooldown is active.

**Comment by mrcoffee1026** [comment]
Well therein the problem lies, looks like its no longer checking for that permission it is instead checking for this one:
```
[15:23:21] [Server thread/INFO]: CoffeeTheMug issued server command: /heal
[15:23:21] [Server thread/INFO]: [Essentials] checking if CoffeeTheMug has essentials.commandcooldowns.bypass - false

```
Which is not good... since that permission allows bypass for other items which I wiould like  the cooldown preserved for like... repair.

**Comment by caojohnny** [comment]
Apologies, I did not have time to take a close look at this earlier.

It seems that using the `command-cooldowns` function will always check the player for that permission (see https://github.com/EssentialsX/Essentials/blob/e4a8222d48a37c71f856a4e28a66c1de292d86eb/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L492). I'm afraid it's not possible to do what you're trying to do currently.

**Comment by mdcfe** [comment]
@AgentTroll Essentials has had a separate heal/feed cooldown for long before EssentialsX added command cooldowns - those cooldowns use the [`essentials.feed.cooldown.bypass`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandfeed.java#L22) and [`essentials.heal.cooldown.bypass`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandheal.java#L24) permissions. 

@mrcoffee1026 Please post your **full config** to [Gist](https://gist.github.com) as instructed by the template.

.

**Comment by mrcoffee1026** [comment]
https://gist.github.com/mrcoffee1026/05ad1a99b0ff218c8bae1600e8cdc0fc

So far as i know there's not an "ignore essentials.feed.cooldown.bypass and ignore essentials.heal.cooldown.bypass" option in the config file, but have fun.

**Comment by caojohnny** [comment]
@md678685 yes I understand, but OP isn't using the `heal-cooldown` field, but rather the `command-cooldowns`

**Comment by mrcoffee1026** [comment]
I'm not giving everyone OP so they can achieve the old "essentials.feed/heal.cooldown.bypass" permissions, that would be insane.  These two permissions simply need to be obeyed.

**Comment by mdcfe** [comment]
@AgentTroll That's why I asked for the config - I wasn't sure which cooldown the OP was using.

@mrcoffee1026 The permissions you've set apply to the Essentials [`heal-cooldown`](https://gist.github.com/mrcoffee1026/05ad1a99b0ff218c8bae1600e8cdc0fc#file-gistfile1-txt-L82-L83) option in your `config.yml`, **not** Essentials**X**'s [`command-cooldowns` system](https://md678685.github.io/EssXDocs/#/Command-Cooldowns).

To use the bypass permissions for those two commands, comment out the commands from [below `command-cooldowns`](https://gist.github.com/mrcoffee1026/05ad1a99b0ff218c8bae1600e8cdc0fc#file-gistfile1-txt-L609-L610) and set [`heal-cooldown`](https://gist.github.com/mrcoffee1026/05ad1a99b0ff218c8bae1600e8cdc0fc#file-gistfile1-txt-L83) in your config.

---

Side note: "OP" in **uppercase** in the context of an *online discussion* can mean either "original poster" or "original post" interchangably. "op" in **lowercase** in the context of *Minecraft servers* does indeed mean "operator".

**Comment by mrcoffee1026** [comment]
Sorry I misunderstood you.  I'll try with the settings adjusted... I take it there is no "feed-cooldown" setting?

**Comment by mdcfe** [comment]
@mrcoffee1026 They are controlled by the same `heal-cooldown` setting.

**Comment by mrcoffee1026** [comment]
too bad those can't be set independently.  Thanks.
