### ISSUE TITLE
Bug with the homes

### ISSUE THREAD

**Issue by JorisPV** [EssentialsX/Essentials#2068]
Full output of `/ess version`:

![image](https://user-images.githubusercontent.com/21250318/42575521-013a3b12-8521-11e8-8972-0beb2e6536d7.png)

### Server log :

https://gist.github.com/Acenox/46299a2152d43d7adf069b99a5d1bbb2

### EssentialsX config

https://gist.github.com/Acenox/3777798d5e303c12c3f61210c16e57eb

### Details

Hello,

I encounter a problem on my server with EssentialsX quite often, because some of my players lose their home. For no reason. The problem seems to arise from time to time to random players when the user connects.

The player "eliott2003" lost his homes in the day of the latest.log I do not know if you will find some things or not.

I tried several versions of EssentialsX (recent as old) the problem is still present. So I do not know if it's because of one of my plugins or if it's an EssentialsX bug.

Thanks a lot for your help.

**Comment by md678685** [comment]
We don't support the Essentials MySQL Storage plugin, as that is a premium plugin made by another developer. The only suggestion I can make is to adjust the settings in the `plugins/EssentialsMysqlStorage/config.yml` to stop that plugin deleting Essentials files.

**Comment by mdcfe** [comment]
We don't support the Essentials MySQL Storage Extension plugin, as that is a premium plugin made by another developer. I would suggest asking @brunyman for support with the plugin, as we don't have access to a copy of it nor am I familiar with it.

**Comment by JorisPV** [comment]
Ok I understand, but what I do not understand is that this plugin is only used to store essentials money under data base and normally has no "aspect" on homes?

**Comment by Xeyame** [comment]
Because EssMySql messes with the way user files are stored, this very likely causes desyncing with essentials and the database, making user files getting overwritten occasionally, causing homes not being saved etc. I don't think it's an useful plugin anyways, cause it's not "real" SQL storage. It only stores the user files in another place when someone isn't online (and fails to correctly load/unload files sometimes). TLDR: the MySQL storage plugin touches more than the money. If you want money to be stored in MySQL, your better off using any vault compatible economy provider that can use MySQL properly (like doing actual database querys for reading out money, instead of downloading a file and uploading it on logout/login)

**Comment by mdcfe** [comment]
@Acenox As far as I can tell, the plugin copies all the data you would normally find in the `plugins/Essentials/userdata/abcdef.yml` files into MySQL. It then deletes the original Essentials data files (apparently to save space), which also deletes the homes and causes EssentialsX to have to create a new, empty file for that user when they log back in.
