### ISSUE TITLE
Essentials apparently causes towny errors see latest townys console log for more info below

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#2073]
[02:03:52 WARN]: [com.palmergames.bukkit.towny.log] Essentials detected: **The Towny authors would like to make you**
[02:03:52 WARN]: [com.palmergames.bukkit.towny.log] **aware that Essentials has been causing town and nation bank**
[02:03:52 WARN]: [com.palmergames.bukkit.towny.log] **accounts to reset. Furthermore their handling of bank accounts**
[02:03:52 WARN]: [com.palmergames.bukkit.towny.log] **has left vital town, nation, warchest and server accounts**
[02:03:52 WARN]: [com.palmergames.bukkit.towny.log] **vulnerable to exploitation. Towny has made changes to stop**
[02:03:52 WARN]: [com.palmergames.bukkit.towny.log] **these exploits from occuring but we cannot stop Essentials**
[02:03:52 WARN]: [com.palmergames.bukkit.towny.log] **Economy from reseting bank accounts. Please change to another**
[02:03:52 WARN]: [com.palmergames.bukkit.towny.log] **Essentials-type plugin as soon as you are able.**

**Comment by axemwa** [comment]
The issue hasn't been occuring for me as of yet, but I thought I'd report the issue incase it hasn't been reported yet

**Comment by mdcfe** [comment]
@LlmDl The Essentials devs have no intention of fixing Essentials, as shown by the fact they haven't made any meaningful change to the plugin in [nearly 4 years](https://github.com/essentials/Essentials). I agree that nobody should be using Essentials in 2018, since it doesn't support any version above 1.7.10 and hasn't received any maintenance since the Bukkit project died.

Please report the issues [you claim Essentials has](https://github.com/TownyAdvanced/Towny/issues/2982#issuecomment-405395540) to us so we can fix them in EssentialsX, rather than making [disparaging remarks](https://github.com/TownyAdvanced/Towny/commit/a42dff811f510783e0c84b3fd0469af5d98c814b) on the entire plugin because of one issue. If any of the Towny team had made useful reports to us, I would be able to look into them, but so far you have provided nothing useful to us whatsoever, and so it is unreasonable to pin the blame entirely on EssentialsX.

@axemwa You should always regularly back up your Essentials userdata. If you encounter any economy issues while using EssentialsX as your economy plugin, replace affected files with the backed-up copy, and if problems continue, consider migrating to a separate **economy** plugin alongside EssentialsX.

**Comment by LlmDl** [comment]
I haven't filed any tickets because I am not an EssentialsX user. I figured one of the many people with these issues would have reported them and it would be fixed. Obviously no one has made the effort.

The one that we already sorted out on our end was the ability for players to log in as a player named town_townnamehere and be able to act as the town's bank account. Our bank accounts are named on our end as 'town-townnamehere' but essentials is writing offline player files for them using _'s in place of -'s, making them not safe. Towny now blocks players from joining if their account names start with any of the possible eco accounts Towny creates.

The other issue is the resetting of banks to default values when using /reload. I'm betting it's fairly easy to reproduce and next time I see someone experience it I will tell them to file a ticket.

**Comment by mdcfe** [comment]
@LlmDl As per #2016, the sanitisation wasn't removed as it would cause every server to suddenly lose all of their Towny accounts (and any accounts that did anything similar).

Is there any chance the startup message could be revised, as it is still misleading and broad? For example, if the server is running older, unsupported versions of Essentials (any version that is below `2.15.0`, including Spigot-Essentials and old EssentialsX versions), send a message advising admins to switch plugins, while asking anyone with EssentialsX (versions 2.15.0 and above) and data loss issues to report it to us or switch economy plugins?

**Comment by axemwa** [comment]
Sorry what I meant was it hasnt affected me yet (no economy issues) I just thought I'd report it cause I seen the message in console and didn't know where else to go to report it I didn't know whether you guys were aware or not, just trying to help. 

I do regulrarly keep my data backed up thanx for the heads up tho and thanx for replying guess I'll close this issue then thought I closed it already my bad. 
Also please don't assume I'm trying to blame the plugin it would offend me that you think that. I I love this plugin and all I wanna do is help.  

EDIT - Disregard the last message from before that was in this message it was a copy paste job for another issue or I wrote the message wrong can't remember got that many tabs open atm my bad

**Comment by LlmDl** [comment]
I'd already been thinking to shorten the message at startup/remove it. I just got tired of people coming and telling me that their towny bank accounts are gone/reset and why do we do that. I'll take a crack at it when I'm back from holiday.
