### ISSUE TITLE
/ignore doesn't work

### ISSUE THREAD

**Issue by Joe7670** [EssentialsX/Essentials#2079]
### Information

Full output of `/ess version`:

22.07 02:30:12 [Server] INFO CONSOLE issued server command: /ess version
22.07 02:30:12 [Server] INFO Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-2086bb0-8cc5a7e (MC: 1.12.2)
22.07 02:30:12 [Server] INFO EssentialsX version: 2.15.0.1
22.07 02:30:12 [Server] INFO LuckPerms version: 4.1.25
22.07 02:30:12 [Server] INFO Vault version: 1.6.1
22.07 02:30:12 [Server] INFO EssentialsXChat version: 2.15.0.1
22.07 02:30:12 [Server] INFO EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.
/ignore command doesn't work
When ignoring a player, the command will output back the message normally making you think it has worked, but you will continue to see the player's messages which you have ignored. When typing /ignorelist the player you have ignored will still show up there, but it has no effect.

**Comment by mdcfe** [comment]
Could you paste a full plugin list, as well as a full server log when this happens?

For the record, `/ignore` should successfully block TP requests and private messages.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.

**Comment by Joe7670** [comment]
Change this to a request ticket then please. I would like to have the option for the /ignore command to also ignore public messages.

**Comment by pop4959** [comment]
The ignore command only affects Essentials commands, it doesn't have any effect on other chat (such as other plugins or public chat). You can, of course, turn off your chat if you want to avoid seeing any messages. If someone is being abusive, this is probably something for moderators to step in for as well, instead of just leaving it up to ignore to fix something like this. Feel free to make a new issue as a feature request instead of a bug report if you still need this, and you feel that you still have a strong argument for why this should be a thing (or a similar command to fully "block" users).

**Comment by Joe7670** [comment]
Yes, I still would like a command that gives the ability to a player to ignore other players' public chat messages. Please, if you don't mind, keep this open as a feature request and change the title if need be.

1. Moderators aren't always online
2. Sometimes it could be something personal. The "bad" player may only be bad for a certain other player, so muting/kciking that player for the sake of just one player is unreasonable.

Of course it could be a separate command or as part of /ignore if enabled in the configuration for example.
