### ISSUE TITLE
Prefix Color Issues

### ISSUE THREAD

**Issue by MsDemonicRaven** [EssentialsX/Essentials#209]
I believe i found a bug. My colors for my prefixes are not working. My owner prefix (im using group manager) is supposed to be yellow but it is aqua. I have plugin called Simple Prefix, and when i would enable it, my colors would work. but, when i disable it, my owner prefix is aqua. I went on the irc and was helped by lol768 (give that man/woman a cookie. they were very nice) but its odd that it isnt working on its own. I now have to do &3&e[Owner]. I know you wont do groupmanager, but its a little odd to me. If this bug is in essentials, please try to fix it :)
For the test, i had my prefix as &3[Ownertest].
I will have links to pics i have sent in the irc network.

With the simple prefix plugin: https://imgrush.com/yOtcA1VD7XFU

Without the simple prefix plugin: https://imgrush.com/xlwmvQZ3wjPU

Thank you for reading this

**Comment by lol768** [comment]
**Logs:** https://korobi.io/network/esper/channel/drtshock/logs/2015/09/27/#L178-380

This issue I found pretty confusing. It might well be caused by another plugin, but it seems that the first colour code in the prefix/display name gets automatically stripped out in chat lines somehow. No idea if EssentialsChat would ever do something like this (https://github.com/essentials/Essentials/blob/ad13062117b0867073b76380503900245a4618ee/Essentials/src/com/earth2me/essentials/User.java#L297 might be relevant) - if not this issue can probably be closed and we can assume it was caused by another plugin I guess.

> I went on the irc and was helped by lol768 (give that man/woman a cookie. they were very nice)

Aww, thanks <3

**Comment by drtshock** [comment]
Can you paste the relevant section of the essentials config showing your chat settings? Or are you just setting the prefixes with groupmanager?

**Comment by lol768** [comment]
Yeah, they're setting the prefixes with GM (which does actually work, the displayName is set correctly - it just seems to get modified when the player sends a chat message).

**Essentials config:** https://gist.github.com/anonymous/faa75f3861cdefda2c5a

**GM config:** https://gist.github.com/anonymous/41b06ef40c0e5d8ed390

**Comment by MsDemonicRaven** [comment]
Its just odd to me that a plugin was making the colors work. :/
