### ISSUE TITLE
Better TPA

### ISSUE THREAD

**Issue by CaszGamerMD** [EssentialsX/Essentials#2099]
add a "restricted world" section to allow server ops to list worlds that both sender and receiver must be in for the tpa to work.

RestrictedWorlds:
-Limited

**example:

BobDaBuilt enters /tpa Phillycheese
bob is in world, and phil is in Limited,
returns msg to bob, "Phillycheese is in a Restricted World."

**Comment by mdcfe** [comment]
This is a somewhat limited problem, and the proposal also seems to be a fairly limited solution. I'm not convinced this belongs in EssentialsX rather than being implemented in a separate plugin.

I'd propose something similar to #1850, which is that the permission `essentials.teleport.to.<world>` is required to teleport to another player in `<world>`. The permission should default to true, and then server admins can take advantage of it by disabling it globally then re-enabling it for individual worlds.

**Comment by pop4959** [comment]
Should probably be handled by a custom plugin or a multi-world plugin. Fully agree with MD that this is far too specialized to include in the plugin.
