### ISSUE TITLE
1.13.1 - /weather storm doesn't trigger an actual thunderstorm

### ISSUE THREAD

**Issue by tsiedsma** [EssentialsX/Essentials#2160]
### Information

Full output of `/ess version`:/es
Server version: 1.13.1-R0.1-SNAPSHOT git-Spigot-0ede7d0-c88ae6b (MC: 1.13.1)
EssentialsX version: 2.15.0.45
PermissionsEx version: 1.23.4
Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXChat version: 2.15.0.45
EssentialsXSpawn version: 2.15.0.45

### Details

Using /weather storm doesn't actually trigger a thunderstorm.  Also, Vanilla 1.13.1 now has the same command with different options.  /weather thunder will trigger a thunderstorm in vanilla but with EssX it set the weather to sun.

The expected behavior:
/weather storm or /weather thunder should trigger an actual thunderstorm which it currently does not.

**Comment by tsiedsma** [comment]
I can use /weather storm or /storm and /thunder but I want players to be able to use a [weather] sign to trigger a thunderstorm and that's not working.

**Comment by mdcfe** [comment]
Thanks for filling out a bug report, and apologies for the long delay in responding to this ticket.

---

Could you clarify what the issue is? Your second message seems to contradict the first.

`/weather thunder` is not part of EssentialsX's `/weather` command - only `storm` and `sun` are valid subcommands. In addition, only the aliases `/storm`, `/estorm`, `/rain` and `/erain` will cause a storm.

On a `[Weather]` sign, only `Storm` and `Sun` are valid options on the second line.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
