### ISSUE TITLE
Feature request: nick <-> username translations even if player is offline.

### ISSUE THREAD

**Issue by Magnum97** [EssentialsX/Essentials#2211]
The kids on my server change names so often it is hard to keep track of. It would be helpful to have a way to translate nick and ign. 
Currently I can use /realname to find the ign of a nickname if player is online or /whois to show the nick of an ign if they are online. It would be great to have these translate names while player is offline.

**Comment by pop4959** [comment]
Not really sure that this feature is all too necessary -- nicknames are only relevant when players are online, and if you aren't sure who logged off with a particular nickname you can just check your server console.

In addition, since searching for a particular nickname would probably require reading all userdata files, which would be slow.

Will keep the "open to PR" tag in case someone knows / finds a sane way to implement this, and wishes to do so, but I don't think it'll happen.
