### ISSUE TITLE
/clear command not working in 1.13.1

### ISSUE THREAD

**Issue by axemwa** [EssentialsX/Essentials#2213]
/clear (player) (item) (amount) to be specific
error report here - https://pastebin.com/iP8fXWxr

**Comment by Haileykins** [comment]
Verified. Also, axe, be a bit more specific here. The clear command itself works, when wiping the entire inventory, however when trying to take a certain number of a certain item or just a certain item from yourself or someone else. Same error as above. Shown here https://hastebin.com/ucowugipuv.md. 

You can replicate this by giving yourself some items, then attempting for example /clear (your name) (item)

The bug also happens when attempting /clear (your name) (item) (amount)

**Comment by axemwa** [comment]
thats why I didn't say the /clearinventory command doesn't work lol cause it does

**Comment by mdcfe** [comment]
This should be fixed by #2204.

**Comment by axemwa** [comment]
Thanks! I'm using the built in /minecraft:clear command for now

**Comment by mdcfe** [comment]
Closing as item support (including a fix for this bug) is now part of the 1.13 branch and [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental).
