### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by TEighteen** [EssentialsX/Essentials#224]
i have set up a new server with the use of the essentials nodes. but i noticed that users don't have access to them even though they are in the permissions.yml for each group. the OP users (Admins and Owner (me) ) can use all the commands perfectly fine. i know this isn't an issue with the Permissions Plugin im using as this is only happening to the essentials commands. For example. anyone from Member-Expert can not use /help, /home, /list etc... even though its in the permisions.yml. (i have provided the the permissions below) users can not use ANY essential commands.

https://gist.github.com/fb152e70e45469a1b385.git

**Comment by SupaHam** [comment]
Can you please delete all of that and paste it into a paste service such as http://pastebin.com or http://gist.github.com

**Comment by TEighteen** [comment]
done :)

**Comment by SupaHam** [comment]
Hey @Chris4418 Thanks for the info. If you look at your permissions config you'll see that you define certain permissions such as

```
- home
- sethome
```

Under `Guest.permissions`. You've defined the command names rather than the permission nodes themselves. Have a look at [The command reference at ess3.net](http://wiki.ess3.net/wiki/Command_Reference) for information on each command's permission node. You can use the search bar located at the middle right of your screen to search for commands by name, and later click on the command to find its permission nodes.

Edit: the permission nodes for `home` and `sethome` would be `essentials.home` and `essentials.sethome` respectively.

Edit 2: Related to this issue at hand, your default group is called Guest, but in Novice you refer to it as Member, that could cause inheritance issues since Member does not exist as a group.

**Comment by TEighteen** [comment]
i tried that and still the same problem. i will try once more and i will get back to you
