### ISSUE TITLE
essentials gets stuck saving .yml

### ISSUE THREAD

**Issue by Roshanxy** [EssentialsX/Essentials#2265]
https://hasteb.in/cacogipu.md 
### Details

**Description**  
My server crashes daily with the same error, seems like it gets stuck saving .yml files

**Steps to reproduce**  
no clue, it happens randomly, check the link above ^

**Expected behavior**  
it working normally and not crashing my entire server

**Comment by mdcfe** [comment]
Thanks for opening a support request. In the future, please use [Gist](https://gist.github.com) to attach text files to the ticket, as Hastebin limits what support we can provide.

---
This is occurring when a player disconnects. Could you see whether it is always caused by the same player disconnecting?

It's entirely possible that this is an issue with SnakeYAML itself and not something we can easily fix.

**Comment by triagonal** [comment]
Closing due to lack of response. Please comment on this issue if you still require support.
