### ISSUE TITLE
Command day,night,rain,sun separated permission

### ISSUE THREAD

**Issue by TheNety** [EssentialsX/Essentials#2332]
### Feature request

**Feature description**

I would like to suggest separating permissions for /day and /night + /sun and /rain command.
Like essentials.day and essentials.night instead of essentials.time.set.

**How the feature is useful**

People then can't spam these command and do the sky blinking :smile:

**Comment by kennyrkun** [comment]
I think this is a good idea, but they should be `essentials.time.day`, `essentials.weather.rain` and such for extra clarity and organisation.

**Comment by mdcfe** [comment]
While I agree with `sun`/`rain` having permissions (under `essentials.weather` as suggested by @kennyrkun), `day` and `night` are more complicated as players could technically run `/time 3892` to set the time as a number. A solution to this is to always check if the player has the permission `essentials.time.<arg>` where `<arg>` is just whatever argument they provided. This would allow server owners to enable `/time day` but not `/time 0`.

In addition, whatever permissions we add will need to have a `config.yml` option so that they are disabled by default, as this is breaking behaviour that not everyone will want or need.

**Comment by pop4959** [comment]
In general, I'd consider this to be a more moderator/administrator level command, not something that players are normally given. This doesn't seem like it would be a problem if you trusted the people using these commands. Although extra permission nodes never hurt anyone, if they work.

**Comment by JRoy** [comment]
Extra permission nodes would require the separation of the time commands as they could be overridden due to them sharing a common time command. This seems like something extremely niche and for one specific use case. Would recommend a separate plugin for this.
