### ISSUE TITLE
Allow specifying amount in /more

### ISSUE THREAD

**Issue by LaughNgamez** [EssentialsX/Essentials#2342]
Make "/more" have an input string for the amount you want.

For example "/more 10" would give you 10 of whatever you're holding.

**Comment by kennyrkun** [comment]
i have attempted to implement this feature in my fork of essentials.

i made a mistake and did it in the 2.x branch, but I believe if we merge it directly onto the 1.13 branch it will work fine because I implemented the changes from the 1.13 branch. 

i don't really know how branching and merging and pull requests work so I haven't opened a PR yet.

**Comment by triagonal** [comment]
This feature has been implemented in 1a6ad2f and is present in versions `2.17.2.158` and above. Download the latest build [here](https://essentialsx.net/downloads.html).
