### ISSUE TITLE
Permission/Option to allow items with durability to be worn as hats

### ISSUE THREAD

**Issue by lw9244** [EssentialsX/Essentials#2385]
**Feature description**
Permission/Option to allow items with durability to be worn as hats

**How the feature is useful**
I make use of the durability to create custom hat textures using items like tools but with the current system, there's no way to allow items with durability to be worn as hats at all.

**Comment by pop4959** [comment]
This may be fixed by the recent PR that added permissions per item for hats. Although I'm not sure if that applies here, since it might also be blocked for good reason. Wearing hats that have durability will take damage when worn. In your use case, this would also not make much sense since the texture will change when the player takes damage.

If you absolutely need this functionality, you could also use `/minecraft:replaceitem`. That should be able to do exactly what you're looking for.
