### ISSUE TITLE
[Signs] A sign shop [Buy:Sell] || Command Costs

### ISSUE THREAD

**Issue by D4RKKNIGH7** [EssentialsX/Essentials#2395]
### Feature request

**Feature description**

- Add another sign for Buying and selling with a single sign.

=== Sign Text ===
[Buy:Sell]        - Sign Identifier
1                    - Quantity
Stone             - Item
B:$50 S:$10    - Buy price is $50, sell price is $10

The player can then use Left Click to BUY and Right Click to Sell
If the player holds CROUCH it will buy a stack the size of the stack you are holding (Same as a buy sign)
If the player holds CROUCH it will sell the stack the player is holding.

Also have the ability to have a [Buy:Sell] sign with ONLY sell or ONLY buy on it.
EG:
=== Sign Text ===
[Buy:Sell]        - Sign Identifier
1                    - Quantity
Stone             - Item
B:$50              - Buy price is $50, No selling of this item

ANOTHER THOUGHT:
- Have the ability to sell ALL items in the players inventory
- The ability to automatically add a Itemframe with the item on the sign in it (Probs a bit hard)

ON ANOTHER TOPIC:
- Have a warning for players before charging them to use a command, right now it will just take the money out if they have it, or tell them they don't have enough. 

Example:
Type /back
Returns a message "This will cost $xxxx, retype the command to accept"
Type /back
Player gets ported back and costs them $xxxx

**How the feature is useful**

This will make sign shops smaller and more tidy.

**Comment by mdcfe** [comment]
Thanks for opening a feature request.

> Add another sign for Buying and selling with a single sign.

I don't see the problem with just having two separate signs? If you use the existing signs, players will already know how to use them. Adding a new sign that does two totally different things is confusing, especially when there are already two incredibly well-known signs that you could use.

> Have the ability to sell ALL items in the players inventory
This already exists: give players the permission `essentials.sell.bulk` and then they can do `/sell inventory`.

> The ability to automatically add a Itemframe with the item on the sign in it

This is beyond the scope of Essentials signs. Signs are individual signs, not an entire shop building. You can use another plugin for this, or just, you know, put item frames next to the signs.

Overall, I don't see how any of the proposed sign features are at all useful to anyone, because there is no easy way to make these useful or accessible to the average person.

---

> Have a warning for players before charging them to use a command, right now it will just take the money out if they have it, or tell them they don't have enough.

We'd need to refactor the command confirmation system for this.

In addition, this is a completely unrelated feature. Could you open a separate feature request for it?
