### ISSUE TITLE
Support currency names through Vault

### ISSUE THREAD

**Issue by SkytAsul** [EssentialsX/Essentials#2401]
### Feature request

**Feature description**
I'd like you to add two fields in your config menu : _currencyName_ and _currencyNamePlural_, who'll can ben hooked to Vault to allows other plugins to use it. Currently, we cannot get economy symbol via Vault API and it's quite annoying...

**How the feature is useful**
This will be very useful for developers, instead of creating money name fields in our own plugins...

**Comment by pop4959** [comment]
This should be added to Vault instead of Essentials. The entire point of Vault is to provide a common interface between plugins, so it makes no point to add this directly to Essentials if this is your intention. If it is added, let us know and Essentials can use Vault instead for this (and so can every other plugin).

**Comment by SkytAsul** [comment]
It _is_ present in Vault. Essentials is one of the only plugins which don't implement this feature.

**Comment by pop4959** [comment]
Ah I see. I thought when you said "this will be very useful for developers", that the request was for Essentials to handle this because Vault didn't. This makes more sense. Sorry for the confusion.
