### ISSUE TITLE
Improve new /r behaviour

### ISSUE THREAD

**Issue by Kakifrucht** [EssentialsX/Essentials#248]
I was messaged by a player, whom I wanted to answer with /r, but since /r was locked to my old conversation partner, who was offline by then, it showed me that I have nobody I can reply to. Would this be possible to check if the player it "locked" to is still online, and if not, get the next best (in that case, the last person messaging me)?

**Comment by EvilOlaf** [comment]
I thought about this could happen earlier, but I didn't mentioned it, because I think it is an unlikely scenario and would make the new `/r` feature even more complex.

IF this would be realized then the receiver of the private message should get a warning that `player $1 went offline, switching reply to $2` or something similar.

I prefer the solution as it is for now ;)

**Comment by Kakifrucht** [comment]
Well you are right, I just had the case where I messaged a player, then send a message to another player, wanted to respond to the second player with /r, he went offline immediately and it would have been bad if the message went to the first Person. But I guess there is still room for some behavioural improvement.

**Comment by EvilOlaf** [comment]
Sure, there always is. I just like to share my two cents with others :)

**Comment by SupaHam** [comment]
With this new behaviour, if your reply-recipient is offline, it notifies you, if someone messages you during that time, they become your new reply-recipient, as if you never had one to begin with. If someone did not message you and your old reply-recipient logs on again, they still remain your reply-recipient.
