### ISSUE TITLE
Update to 1.14-spigot version

### ISSUE THREAD

**Issue by miladesign** [EssentialsX/Essentials#2508]
Can you update this plugin for 1.14 spigot version?

**Comment by Eutherin** [comment]
probably not until an official 1.14 spigot jar is out.

**Comment by triagonal** [comment]
EssentialsX is currently in the process of being updated to 1.14. There is no confirmed release date as of yet. 

When 1.14 support is added, there will almost certainly be a new release posted in the Releases section of the repository, so you could click the "Watch" button at the top of the page and select "Releases only" to be notified when a new release is posted.

Alternatively, you could join the [MOSS discord server](https://discord.gg/PHpuzZS) and keep an eye on the #updates channel in the EssentialsX category.

**Comment by Tsoccerguy3** [comment]
java -jar BuildTools.jar --rev 1.14

compile against the 1.14 API

**Comment by Xeyame** [comment]
@Tsoccerguy3 It's not that easy sadly

**Comment by miladesign** [comment]
> probably not until an official 1.14 spigot jar is out.

there is 1.14 spigot version in spigot website!

**Comment by miladesign** [comment]
its work on 1.14 version!
but signs and shop not work.

**Comment by smmmadden** [comment]
This will be an iterative process to update everything to 1.14 since Mojang renamed a lot of blocks and added a ton of new ones.  That's just the block side.  I'll be setting up my test server this weekend to see how well buildtools.jar build 101 is with the latest EssentialsX and some other plugins to provide some feedback to the devs.

**Comment by mdcfe** [comment]
You can keep track of 1.14 progress in #2510.
