### ISSUE TITLE
Thunder Defaults to being disabled even when enabled

### ISSUE THREAD

**Issue by tierghan** [EssentialsX/Essentials#2526]
### Information

Full output of `/ess version`: 2.16.1.154

/thunder true 15m: Error: For input string: "15m" 

**Server log:** <scriptsrc="https://gist.github.com/tierghan/aa0b0073b3337afafdf20fb93834db8c.js"></script>

**EssentialsX config**<scriptsrc="https://gist.github.com/tierghan/1c1ac61ed06659a608e270f5b4bf29e0.js"></script>

### Help request

**Problem**
When ever i go to use the channeling enchantment useing a trident, the lightning never comes when it is suppost to. When i use /thunder true, it fixes it for a bit then disables itself again.

**What I have tried**
Ive looked through the config and online for others who have had problems. When i try to settle for haveing to redo the command for a year at a time, it gives me the error from above.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/50425512/57407428-270fae80-71b1-11e9-814a-20337fda5b4e.png)

**Comment by mdcfe** [comment]
Cannot replicate on 1.14.1 with experimental builds (which do not change tridents/enchantments at all).

```
[12:35:37 INFO]: CONSOLE issued server command: /ess version
[12:35:37 INFO]: Server version: 1.14.1-R0.1-SNAPSHOT git-Paper-43 (MC: 1.14.1)
[12:35:37 INFO]: EssentialsX version: 2.16.1.181
[12:35:37 INFO]: Vault is not installed. Chat and permissions may not work.
```

After running `/storm`, shooting a Trident with the Channelling enchantment at a mob correctly spawns a lightning bolt.

If you can provide clearer instructions on what the issue is, I'll reopen this, but I can't see any issues here.
