### ISSUE TITLE
the files won't unpack

### ISSUE THREAD

**Issue by Joseph0430** [EssentialsX/Essentials#2543]
I have an issue where when i put the plugin in the plugins folder and I restart the server, the Essentials plugin will unpack and turn into a folder, but all the other files like EssentialsAntiBuild, EssentialsChat, EssentialProtect won't unpack.
![Screen Shot 2019-05-14 at 9 32 15 AM](https://user-images.githubusercontent.com/14146247/57664555-38324280-762b-11e9-8add-84b86d3663cf.png)

**Comment by triagonal** [comment]
The only jarfile that generates a folder is EssentialsX, the other modules are controlled through the `config.yml` in the `plugins/Essentials` folder.

Also, I'm not quite sure if you've renamed your jar files or not, but it seems like you might be running Essentials instead of EssentialsX. This GitHub repo is for EssentialsX, so you should swap over if you require further support.

edit: GeoIP and XMPP also generate their own plugin folders, but the rest of the modules do not.

**Comment by Joseph0430** [comment]
i've changed it to essentialsX, but the folders in creates also include GeoIP. is this normal?
![Screen Shot 2019-05-14 at 10 48 33 AM](https://user-images.githubusercontent.com/14146247/57667384-e0e59f80-7635-11e9-9249-a88733926c56.png)

**Comment by triagonal** [comment]
Ah, yes. Apologies, GeoIP and XMPP both also generate their own folders, but all of the other modules do not.

**Comment by Joseph0430** [comment]
ok, thanks
