### ISSUE TITLE
Kit Command Delay

### ISSUE THREAD

**Issue by Fix3dll** [EssentialsX/Essentials#2641]
When i run command in kit like tellraw, tellraw command working before kit given message. I want to firstly see given message after this my tellraw message. What should i do?
![Screenshot_1](https://user-images.githubusercontent.com/10743391/60383601-b469d380-9a7b-11e9-94fd-102510f1c934.png)
![Screenshot_2](https://user-images.githubusercontent.com/10743391/60383602-b6cc2d80-9a7b-11e9-96db-b3c595908e7c.png)

**Comment by pop4959** [comment]
The order of the messages depends on how long the commands take to execute. I don't think this is a bug in EssentialsX as kits are not intended to be used in order to execute arbitrary commands (like chat), but to give items.

You may be intending to use [functions](https://minecraft.gamepedia.com/Function_(Java_Edition)) instead.

**Comment by mdcfe** [comment]
To clarify: the command will always run before the kit given message. The kit hasn't been given until all the items have been given and all the commands have been run, so this is intended.
