### ISSUE TITLE
Task: EssentialsPlayerListener$1DelayJoinTask(Single)

### ISSUE THREAD

**Issue by Terrifical** [EssentialsX/Essentials#2654]
### Information

**Full output of `/ess version`**:

```
> [19:46:53 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)
> [19:46:53 INFO]: EssentialsX version: 2.17.0.0
> [19:46:53 INFO]: LuckPerms version: 4.4.1
> [19:46:53 INFO]: Vault version: 1.5.6-b49
> [19:46:53 INFO]: EssentialsXChat version: 2.17.0.0
> [19:46:53 INFO]: EssentialsXSpawn version: 2.17.0.0
```

**Server log**
https://pastebin.com/nRyJqmhn

**Description**  
Task: EssentialsPlayerListener$1DelayJoinTask(Single) is cuasing ping delay (77ms)

**Screenshots**  
http://prntscr.com/oarmbq

**Comment by montlikadani** [comment]
EssentialsX has nothing to do with ping, because ping indicates the strength of the network that the server owner has opened the server and that server is available to everyone, generally. You must execute `/tps` command, which displays the server Ticks Per Speed.

Otherwise, we still need the **full timings** it has reported, so we can check which plugins can cause the problem.

**Comment by mdcfe** [comment]
In addition, you're using Spigot. If you're concerned about performance, we recommend switching to Paper - it has many more optimisations than CB and Spigot, is fully compatible with Spigot plugins and has a much more useful version of Timings.

**Comment by pop4959** [comment]
This is likely an issue with your server and not the plugin. Timings v1 is notorious for displaying lag indirectly associated with an event. For example, most teleportation plugins will appear to be laggy because world loading/generation is laggy, and it is indirectly caused by teleportation of a player.

Upgrading your server hardware or using a faster software implementation like Paper (which also has the more accurate Timings v2) may yield better results.
