### ISSUE TITLE
Buy, Sell Sign Problem

### ISSUE THREAD

**Issue by Fix3dll** [EssentialsX/Essentials#2658]
/ess version:
http://prntscr.com/ob35fq

lastest.log is clear.

config.yml:
http://prntscr.com/ob362c

Problem:
http://prntscr.com/ob36kk sign is not working. When its working its going blue. When i write wrong going red. But its just black.

**Comment by mdcfe** [comment]
Could you run `/ess debug`, create a sign then post the full console output?

**Comment by Fix3dll** [comment]
I didnt understand but it work with clean setup. https://pastebin.com/z2wFeGM4 Its my config. Whats wrong?

**Comment by mdcfe** [comment]
Please do the following in order:

* Run `ess debug` in your server console.
* Create a `[buy]` sign.
* Paste the `logs/latest.log` file on Paste in and give us a link.

**Comment by Fix3dll** [comment]
https://hasteb.in/uruxavut.md

**Comment by Goreator** [comment]
I have the same problem but with the newest bukkit and minecraft 1.14.3

**Comment by Scremonetu** [comment]
[buy]
1
Dirt
$1

^^^^ Add $

**Comment by Fix3dll** [comment]
@Scremonetu i try this before. Same result.

**Comment by Fix3dll** [comment]
@md678685 @Goreator have some problem. What should we do for help?

**Comment by Fix3dll** [comment]
When i remove my lang file and use default lang file, signs working. I check my file and looks okey for me. Console and debug didnt give me error. Do you have any idea? @md678685

**Comment by Fix3dll** [comment]
We solve this. I change signFormatTemplate from lang file. Thank you very much for everythink: @triagonal

**Comment by triagonal** [comment]
As stated above, the culprit was `signFormatTemplate` in the user's messages file. Changing this entry effects what the user must type in order for a sign to be created. This user's `signFormatTemplate` key was set to something other than the default `[{0}]`, and so caused the issue when attempting to create signs.

For any other users encountering this issue, double-check that the message you've set for `signFormatTemplate` can be entered ingame and that you're entering the correct format for the sign to be recognized.
