### ISSUE TITLE
EssentialsX XP Command Error

### ISSUE THREAD

**Issue by Dhenier** [EssentialsX/Essentials#2684]
### Information

**Full output of `/ess version`**:

Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-137 (MC: 1.14.4)
EssentialsX version: 2.17.0.5
Vault version: 1.7.2-b107

XLRewards-2.2.6 is also installed

**Server log**: https://gist.github.com/Whist34/49f0a760a1282308cddbd8eb164123c5

**EssentialsX config**: https://gist.github.com/Whist34/bef5b12a24aa53eb653eaa269d279e15

### Details

**Description**  
XLRewards provides ability to claim rewards through an ingame gui. You open the gui click on the reward to claim.
This reward is time based and gives you xp.
I have already discussed the issue with the author of XLRewards and after testing found that the error occurs even when XLRewards is not installed.
Issuing the command: "/xp add Dhenier 30000" results in an EssentialsX error with the result that the player does not receive any experience. 

More info: I am in the process of adding Essentials to an existing server. On the existing server this command works as intended without EssentialsX installed.
Xp command as described on the Minecraft Wiki: https://minecraft.gamepedia.com/Commands/experience

**Steps to reproduce**  
Login.
Console issues command: /xp add <username> 300
Error -> No experience

**Expected behavior**  
Login.
Console issues command: /xp add <username> 300
Player receives experience

**Screenshots**  
I have screenshots of the XLRewards GUI interface, but I do not think they are necessary because all of the debug information is included in the server log.
Please let me know if you want me to add those.

**Comment by Dhenier** [comment]
After more testing I have found if I use "/experience add Dhenier 300" Then the player receives the experience. But shouldn't the xp command still work? Or would it need to be a command like minecraft:xp?

**Comment by triagonal** [comment]
Essentials overrides a lot of the default vanilla commands. `/xp add ...` is not an Essentials subcommand, and so its default behaviour is to display the XP statistics of the first argument - it tries to search for a player named `add`, which of course, doesn't exist.

If you wish to continue using the `/xp` command as in vanilla, then you need to use `/minecraft:xp` to explicitly specify that you want the game to use the vanilla command. Otherwise, you can switch your command usage to the Essentials syntax, which in this case is `/xp give <player> <amount>`.

You can refer to [this page](https://essinfo.xeya.me/index.php?page=commands) for all Essentials commands and command syntax.

**Comment by Dhenier** [comment]
I changed to using /experience as the command. I'm going to close this issue. Thanks for the help.
