### ISSUE TITLE
Item glow

### ISSUE THREAD

**Issue by mareksipos93** [EssentialsX/Essentials#2689]
### Feature request

**Feature description**

I would like to spawn glowing itemstacks with Essentials X - but without any enchantment.

**How the feature is useful**

By item-glow admins could mark items with special purpose - like custom consumable items. They could do it simply by adding any enchantment - however with new Minecraft ability to disenchant any item this could lead to free XP.
That's why spawning item without any enchantment would be very useful and fancy.

Thank you

**Comment by pop4959** [comment]
I don't believe it is currently possible within the game to spawn itemstacks that have this property without enchantments. As such, this may not be feasible to add currently.

**Comment by mareksipos93** [comment]
> I don't believe it is currently possible within the game to spawn itemstacks that have this property without enchantments. As such, this may not be feasible to add currently.

I don't know if something changed in terms of enchantments in 1.14.4, but I've seen items with glow but no enchantments on several servers running on 1.14.3.

**Comment by mdcfe** [comment]
I believe it is possible for the game to display stacks as glowing, but we need to look into what methods Bukkit provides for this.

**Comment by dashaw92** [comment]
ItemMeta has a method `addItemFlags` which allows you to customize how an itemstack is rendered by the client (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#addItemFlags-org.bukkit.inventory.ItemFlag...-)

It would be trivial to add a command that adds/removes `ItemFlag.HIDE_ENCHANTS` to/from an itemstack. This flag removes the enchantment name and level from the lore, but keeps the enchantment glow visible for clients. 

Not sure when this method was added, so that should be checked before moving forward with this.

**Comment by pop4959** [comment]
If that is the case then wouldn't an item still need an enchantment in order to have a glow? OP seems to indicate they want an item that does not have an actual enchantment and cannot be disenchanted for xp.

**Comment by JRoy** [comment]
This is possible but not only is this too niche and not essential, but it would also create edge cases the EssentialsX team wouldn't have any interest in supporting.
