### ISSUE TITLE
Big lag caused by Essentials teleportation.

### ISSUE THREAD

**Issue by Weasel-Beans** [EssentialsX/Essentials#2701]
### Information

```
Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-152 (MC: 1.14.4)
EssentialsX version: 2.17.1.0
LuckPerms version: 4.4.1
Vault version: 1.7.2-b107
EssentialsXGeoIP version: 2.17.1.0
EssentialsXSpawn version: 2.17.1.0
```
**Config:** https://pastebin.com/WrFp5XLK

**Timings:** https://timings.aikar.co/?id=4eea6e41977b440a939cdccf90b892dc#plugins
### Details

**Description**  
Lag caused by essentials teleportation, made obvious by the timings report.

**Comment by pop4959** [comment]
This is probably not a problem with Essentials, but with your server. If you look carefully, you can see that the lag is caused not by Essentials, but by "chunkAwait" within the MineCraft server itself. In other words, the lag is indirectly caused by the loading and unloading of chunks in the world. You can see the same issue for any other teleportation plugin such as HorseTpWithMe which also displays in your timings as being laggy. There is probably not any way for this to be "fixed" except for disabling the tp commands on your server if it can't handle them.

**Comment by mdcfe** [comment]
To add to @pop4959's comment:

Paper 1.14.4 doesn't have the same chunk loading inprovements as it did in 1.13.2 yet. Some of these improvements are being [tested and refined](https://github.com/PaperMC/Paper/pull/2308) currently, but there isn't anything we can do to improve world loading performance right now.

**Comment by Weasel-Beans** [comment]
It almost seems like it's been getting a lot worse lately. But ok thanks for the help, maybe I need to slowly start reducing teleportation in my server.
