### ISSUE TITLE
KeepInventory (essentials.keepinventory) is broken since build #2531

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2706]
[deleted]

**Comment by mdcfe** [comment]
> essentials.keepinventory

`essentials.keepinventory` doesn't exist - it's `essentials.keepinv`.

> Also sometimes it duplicates opped players' items on death.

This issue was introduced by Spigot on 26th July (merged into Paper in build 152+). EssentialsX 2.17.1.0 and up fixes this.

> nobody should have essentials.keepinventory by default anyways 

We explicitly disable `essentials.keepinv` by default for everyone, including OPs:
https://github.com/EssentialsX/Essentials/blob/1ff73b383749ff8548c579039cce8bd6d9d8e35e/Essentials/src/plugin.yml#L556-L558

However, PermissionsEx just ignores this and gives all OPs all permissions unless set otherwise. We don't support PEX and there's nothing we can do about it - you should use [LuckPerms](https://luckperms.github.io) instead.

**Comment by ricolay** [comment]
Alright thanks. I went off of the assumption that it's essentials.keepinventory because the feature suggestion said essentials.keepinventory. Sorry.
