### ISSUE TITLE
Vanilla keep inventory still not working, duplicating items

### ISSUE THREAD

**Issue by blankstaticscreen** [EssentialsX/Essentials#2707]
### Information

**Full output of `/ess version`**: 
Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-152 (MC: 1.14.4)
EssentialsX version: 2.17.1.0
LuckPerms version: 4.4.26
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.1.0
EssentialsXSpawn version: 2.17.1.0

**Server log**: [*truncated; see here*](https://gist.githubusercontent.com/md678685/85c0201f38b3e59a6b2b7736f31bf8cd/raw/4838dc2e6fc857afa76db7d6e40f24ae8ef1c1ed/aHR0cHM6Ly9wYXN0ZWJpbi5jb20vTXE1TktuZXk=.log)

**EssentialsX config**: https://pastebin.com/kFFbC9wA

### Details

**Description**  
So I read that 2.17.1.0 fixed the duplication bug, but it seems like it's still happening for me? Our server has keepinv on through vanilla, but when someone dies it kind of "rolls back" their inventory. For example, I died, and my inventory returned to what it was about 30 minutes prior.

**Steps to reproduce**  
Played the game, died, and my inventory changed.

**Expected behavior**  
Should have the same inventory as when I died.

**Screenshots**  
None necessary

**Comment by mdcfe** [comment]
EssentialsX doesn't interfere with the vanilla `keepInventory` gamerule, and I can't replicate this on Paper 154 (no changes to keepinv since 152).

Does this occur with every player?

In addition, could you do the following:
* Take a screenshot of your inventory
* Use `/suicide` to force your own death
* Take a screenshot of your inventory after respawning

**Comment by blankstaticscreen** [comment]
Hi!

It seems like it's not happening with every player. I asked a different
admin to take the screenshots but nothing changed for her. For me, though -
this is right before and after a death by lava btw, I can try a /suicide
later, here's what happens. (See attachment sorry I'm on mobile)

So I had dropped off my shulkers, used some cobble, and also lost lots of
durability on my armor. When I respawned, it was all back.

Let me know if you need any more info!

**Comment by mdcfe** [comment]
Thanks for the update, but it seems like GitHub doesn't include email attachments when you respond by email, so whatever you attached is missing 😕

Is there any chance you could upload it to an image-sharing site (or even upload it in the desktop version of the GitHub website)?

**Comment by blankstaticscreen** [comment]
Sorry about that!! Here you go
http://imgur.com/a/gIL5VFO

**Comment by pop4959** [comment]
I recommend updating EssentialsX if you haven't already, and also make sure you have disabled the `essentials.keepinv` permission on your account (I have not seen this suggested yet on this thread, but if your account is the only one doing this, then maybe it is the problem). There is not enough information to be able to look into this issue, and it seems no one else has reported similar issues for  about a month or two.

Closing this for now, but let us know if you are still looking to resolve this issue (we can reopen it). Although, I may recommend trying the Discord support server for EssentialsX instead since there are many people there who are able and willing to help with configuration problems.
