### ISSUE TITLE
/Deletekit

### ISSUE THREAD

**Issue by RainDropped** [EssentialsX/Essentials#2709]
**Feature description**

a /deletekit command

**How the feature is useful**

you don't have to reload or restart your server to go in your config
and manually delete the line of a kit you dont want

**Comment by montlikadani** [comment]
To do this, there is a Bukkit problem:
The problem is that when we save the configuration, the comments disappear, so we don't know what to do in the configuration.
Alternatively, if the configuration contains comments only in the header, we can fix `config.options.copyDefaults(true);` which prevents comments from disappearing from the header.

**Comment by mdcfe** [comment]
@montlikadani Since EssentialsX 2.15.0, kits have been stored in a separate `kits.yml` file. This file only has one comment and it is the header, so this doesn't matter.

**Comment by mdcfe** [comment]
This has now been implemented - you can download the latest version from the [here](https://essentialsx.netlify.com/downloads.html).
