### ISSUE TITLE
Clear Chat suggestion

### ISSUE THREAD

**Issue by Exxian** [EssentialsX/Essentials#2720]
### Feature request

**Feature description**

A command to clear the chat. EX: /Chatclear
**How the feature is useful**

This would be useful for staff on servers to clear the chat after a spam attack, advertising, or various other annoying chat "attacks". I'm not sure on the best way to implement, but that's why I'm not a dev lol. Thank you for reading this.

**Comment by josh-tf** [comment]
Could be a useful feature, most implementations I've seen on this (usually in chat or ban/punishment plugins) just spam the chat with blank messages to 'clear' the chat

**Comment by pop4959** [comment]
I don't agree with adding this, because as josh mentioned, most implementations just spam the chat with empty lines. This is a rather hacky solution to the problem, and you can already find many other plugins that do this if you absolutely need it.

BTW although this does not force clear the chat for all users, there is indeed the F3+D debug key which will actually fully clear your chat window. Works on all servers, requires no permission as it is client-side.
