### ISSUE TITLE
is there a limit of commands? i wanna know how to increase that limit

### ISSUE THREAD

**Issue by khalidnecron** [EssentialsX/Essentials#2724]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by pop4959** [comment]
no

**Comment by mdcfe** [comment]
Could you elaborate?

**Comment by pop4959** [comment]
Not sure why this issue is still open, but due to lack of response, in addition to providing absolutely no information on the issue, this will now be closed.

Feel free to create a new issue if you plan on putting some effort into it. We cannot help you if you do not describe your question or problem appropriately.
