### ISSUE TITLE
Command "/give @p player_head{skullowner:USERNAME}" doesn't work

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2731]
Hey there,
whenever I try to use the _/give @p minecraft:player_head{skullowner:USERNAME}_ command, the command block output says _"Unknown item name"_ which doesn't happen without EssentialsX.
Version: 1.14.4

![2019-08-10_01 56 31](https://user-images.githubusercontent.com/28489473/62814658-397fe800-bb12-11e9-9813-07357f61dddb.png)

**Comment by mdcfe** [comment]
`/give` is overridden in EssentialsX. If you want to use the vanilla `/give` syntax, you have two options:
* [Add `- "give"` to the `command-block-overrides` in `commands.yml`](https://bukkit.gamepedia.com/Commands.yml#command-block-overrides) (makes command blocks always use the Mojang version of the command)
* Change every command block to use `minecraft:give` instead of `give`

You can also use the Essentials syntax for giving skulls: `/give @p player_head 1 owner:GreenBulldog22`, but you might need to install a plugin like [PsudoCommands](https://www.spigotmc.org/resources/psudocommands-add-the-target-selector-to-plugin-commands.56738/) before command selectors work.

**Comment by Astro-gram** [comment]
its got to be /give @p minecraft:player_head{SkullOwner:"GreenBulldog22"}
