### ISSUE TITLE
Bed problem

### ISSUE THREAD

**Issue by ZdendasYT** [EssentialsX/Essentials#2775]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

When users click on bed, It will instantly set day, I want to deny that permission.
**What I have tried**

**Screenshots**

**Comment by cavernist** [comment]
i have this issue too. i have set "sleep-ignores-afk-players:" to false and it still turns to daytime instantly and doesn't require other players to sleep before making the time change. I am OP on my server, and my one other friend playing with me is too.

**Comment by triagonal** [comment]
This will occur if all players on the server have the permission `essentials.sleepingignored`.

For your situation @cavernist, since both yourself and your friend are opped, you both inherit the permission above. You can negate that permission using a permissions plugin to stop the behaviour.

**Comment by pop4959** [comment]
It seems this question has been answered; I'm going to go ahead and close it now. If there are still any concerns, please let us know and we can re-open the issue.

**Comment by Tresswa** [comment]
This issue seems to be present even without the essentials permission "essentials.sleepingignored".

It does seem to be related to the afk function though.
- As soon as a player becomes 'afk' either by the config time or when a player flags themself as "/afk", the afk as it relates to sleep does not seem to stop when the player resumes activity and is no longer flagged as afk.
- The above occurs even if the player does not have the "essentials.sleepingignored" permission.
- - The instant-sleep issue persists even when there is no permission plugin.
- This afk instant sleep issue will not stop until the server has rebooted.
- The config and the permission website say that the auto-afk will only start if the player has the permission "essentials.afk.auto". However, this permission does not seem to be required for the auto-afk feature to apply.

When setting the config "auto-afk" to "-1" it does seem to disable the afk feature, and this issue no longer persists. However, that is now how this feature seems like it should work.

I have been testing the above as the only player on a server, with op, without op, with permission, without permission, without permission plugin, and by removing the essentialsx plugin. This only occurs when
