### ISSUE TITLE
TPS drop to 15 when doing /warp

### ISSUE THREAD

**Issue by NoFace851** [EssentialsX/Essentials#2777]
### Information

**Full output of `/ess version`**:

```
<!-- [19:19:19 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-177 (MC: 1.14.4)

[19:19:19 INFO]: EssentialsX version: 2.17.1.11
[19:19:19 INFO]: PlaceholderAPI version: 2.10.3
[19:19:19 INFO]: PermissionsEx version: 1.23.4
[19:19:19 INFO]: Vault version: 1.7.2-b107
[19:19:19 INFO]: ChestShop version: 3.10-SNAPSHOT (build 151)
[19:19:19 INFO]: You are running unsupported plugins! -->
``` 

**Server log**:  https://gist.github.com/NoFace851/790c44fb56635d1ac3fd500ae91b06d3 

**EssentialsX config**:  https://gist.github.com/NoFace851/4743ba53d7a26172c8ee964b4e83499c

### Details

**Description**  
 So, essentials X is causing a lot of TPS drop when doing /warp as you can see in timings

**Steps to reproduce**  
 Open minecraft, open a server with essentials, do /warp, change worlds (with multiverse), do /warp again, then you got a lot of TPS drop

**Expected behavior**  
 Not to have this much TPS drops. I didn't find where to place timings, so i'm gonna write it here: https://timings.aikar.co/?id=28ddbc95fe2c45c490fd5e96e5723c71

**Screenshots**

**Comment by NoFace851** [comment]
Anyone? This is really annoying

**Comment by pop4959** [comment]
Not able to replicate. Interestingly, in your ALL tab you have about 75% load with 1 player online. I've got about 30% for 10-15 players, and specs for the machine aren't even noteworthy. I'm running many fewer plugins in general, however. Consider that this issue may be caused by other plugins, or the server you're trying to run this on.

```
[CHAT] Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-642 (MC: 1.13.2)
[CHAT] EssentialsX version: 2.17.1.11
[CHAT] LuckPerms version: 4.4.1
[CHAT] Vault version: 1.7.2-b107
[CHAT] EssentialsXGeoIP version: 2.17.1.11
[CHAT] EssentialsXChat version: 2.17.1.11
[CHAT] EssentialsXAntiBuild version: 2.17.1.11
[CHAT] EssentialsXSpawn version: 2.17.1.11
[CHAT] EssentialsXProtect version: 2.17.1.11
```

![image](https://user-images.githubusercontent.com/17698576/65285443-50423300-daf1-11e9-9467-10484748f9ab.png)

**Comment by pop4959** [comment]
Closing due to lack of response
