### ISSUE TITLE
Local/global chat option

### ISSUE THREAD

**Issue by Salty4Daddy** [EssentialsX/Essentials#2789]
### **Feature request**

**Feature description**
Put /local and /global chat option with configurable radius for local chat. There are many plugins who do this, but I like EssentialsXChat more for its simplicity and this feature should come very handy on bigger servers

**How the feature is useful**
Group of players could comunicate in local chat without bothering everyone on the server. Only full global (radius 0) or very limited chat (set radius) just isnt enough.

**Comment by mdcfe** [comment]
You can set the local chat radius for local chat, and then add `!` or `?` to the start of your message to broadcast it globally.

I don't see why players should be able to set their own chat radii. This would be confusing since not everyone would have the same radius - if you send a message, you're not guaranteed to hear the response even if neither side moves.

**Comment by pop4959** [comment]
EssentialsXChat doesn't need to support every little feature from every chat plugin. That's why you have options. It's a bit contradictory to say that you like the simplicity of EssentialsXChat, but then go on to ask for something that makes it more complicated to use / understand. I'd say, don't be afraid of trying other chat plugins, if they offer features that you feel you need on your bigger server.
