### ISSUE TITLE
Feature Request: essentials.ext.others

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2796]
### Feature request

**Feature description**
Instead of having essentials.ext allow for players to run the command on anyone by default, add an additional node (essentials.ext.others) to allow for players to run it on anyone.

**How the feature is useful**
Gives us more control over this permission and allows for this to be an additional perk to who this permission is granted to.

**Comment by mdcfe** [comment]
> possible purchasable rank command

Be advised that allowing players to purchase the ability to extinguish themselves appears to be a direct violation of Mojang's [Minecraft Commercial Use Guidelines](https://account.mojang.com/terms#commercial).

**Comment by ghost** [comment]
@md678685 Amended the post accordingly. I just want more granular control over permissions, I guess I should've put that as the use case in the first place.

EDIT: But, after reading the guidelines it seems that lots of popular servers break the guidelines. From what I read, it sound like any server that sells a rank that provides users a better kit, or access to additional commands is going against the guidelines. All beacause it provides an unfair advantage.

**Comment by pop4959** [comment]
Server monetising has definitely been a somewhat grey subject, however as far as I've experienced, it comes down to how reasonably free users are able to obtain the perk. If paid users can buy a non-aesthetic perk, that free users can never obtain, it is a clear violation. Where this becomes interesting is when perks are still made available to free users (ie. kit rotation, more difficult to obtain through regular game play), which is what many partnered servers seem to do. Either way, most servers are probably in the clear anyways, because I think Mojang isn't intent on strictly policing, and mostly wants to discourage the extremes ($100 pay to win ranks, etc) that have plagued the game in the past.

Anyways, to avoid continuing to derail this issue, I think splitting the permission would make a lot of sense. Most other commands support this. :smiley:
