### ISSUE TITLE
StoredEnchantments, need help asap !!!

### ISSUE THREAD

**Issue by Kurlzz** [EssentialsX/Essentials#2801]
I've got a problem adding enchanted books into the items.csv file and I don't know what I'm doing wrong.
I used b_protectioniv,403,0,{StoredEnchantments:[{id:0,lvl:4}]} in the file which did not work, and the item meta page of essentials did no good to help
I need to know the right syntax asap. Thx

**Comment by Kurlzz** [comment]
With /i 403 0 {StoredEnchantments:[{id:0,lvl:4}]} it works and gives me the right item but I want to make a [Buy] sign which gives this book to the players

**Comment by mdcfe** [comment]
What version of Minecraft are you using? `items.csv` isn't used on 1.13 or above.

**Comment by Kurlzz** [comment]
1.12.2

**Comment by pop4959** [comment]
The command you used looks correct, but I'm not sure that it's possible to use on a sign since it is quite long. I recommend trying to ask on the Discord server if anyone's tried anything similar. Most likely, it's just not supported, so you might need to find another way to give the item (perhaps using a paid kit, or along the lines thereof).
