### ISSUE TITLE
/hat doesn't seem to work.

### ISSUE THREAD

**Issue by CastorDarkHeart** [EssentialsX/Essentials#2821]
Every time I try and use the hat command, regardless of if its a helmet or anything else. I've not been able to find anything else on it that's helped so far and I'm not sure what all could be causing issues with it either. 
https://gyazo.com/26515bb0e2ea160d71c40b8a83fcd192

My List of Plugins

Clearlag
EssentialsX-2.17.1.12
EssentialsXChat-2.17.1.12
EssentialsXProtect-2.17.1.12
EssentialsXSpawn-2.17.1.12
GriefPrevention
GroupManager
Multiverse-Core-4.0.0
Simple Sit
Vault
worldedit-bukkit-7.0.1-rc2-dist

**Comment by darbyjack** [comment]
Keep in mind, the latest update implemented a blacklist now. It's now perm based. I'd refer to the wiki for the list of permissions!

**Comment by CastorDarkHeart** [comment]
> Keep in mind, the latest update implemented a blacklist now. It's now perm based. I'd refer to the wiki for the list of permissions!

I've got that all fixed in my permissions xD
First thing I looked at.

**Comment by triagonal** [comment]
This sounds very similar to #2763 - are you sure you've **negated** the correct permissions? Granting yourself OP or a wildcard like `essentials.*` will cause this to happen.

**Comment by CastorDarkHeart** [comment]
> This sounds very similar to #2763 - are you sure you've **negated** the correct permissions? Granting yourself OP or a wildcard like `essentials.*` will cause this to happen.

I never had an issue with previous versions of Operators not being able to use /hat before. 
All of the permission nodes seem to be set up as they should be?  Being an operator or not being an operator doesn't seem to fix anything.

The fix from that topic didn't work unfortunately. Would sending my permissions list help at all?

**Comment by pop4959** [comment]
This was changed in 2502f5e6f216d3b6f0bd1cdb98e971e7847e408b. If you have a wildcard permission (eg. `*`, `essentials.*`) and/or op, you will automatically have the permissions that prevent users from using certain blocks as hats. This is why it is generally frowned upon to use these, as it *will* cause weird issues with plugins, and you granting permissions that you don't even know exist.

**Comment by CastorDarkHeart** [comment]
> This was changed in [2502f5e](https://github.com/EssentialsX/Essentials/commit/2502f5e6f216d3b6f0bd1cdb98e971e7847e408b). If you have a wildcard permission (eg. `*`, `essentials.*`) and/or op, you will automatically have the permissions that prevent users from using certain blocks as hats. This is why it is generally frowned upon to use these, as it _will_ cause weird issues with plugins, and you granting permissions that you don't even know exist.

Here's how the permissions are set up
global permissions: https://pastebin.com/rsh6RstU
world based permissions, this is for my main world: https://pastebin.com/wRcetg79

The only permissions that I have that utilize the * in them, is the one for the signs. Would that cause interference?

**Comment by triagonal** [comment]
So, in this file https://pastebin.com/wRcetg79 at line 98 you'll see you've added `'*'` as a permission for the owner group, which I'm assuming that you're a member of. By doing so, you've also had that group automatically inherit the permission `essentials.hat.prevent-type.*`, **which disallows the use of every single item as a hat.** You need to **set that permission to false**, or "negate" it, in order to restore functionality.

In the context of your permissions plugin, "negating" a permission means adding a negative sign in front of it. Additionally, most permissions plugins require that the negation be declared before any wildcard permissions. So, your owner group should instead look like:
```
  Owner:
    default: false
    permissions:
    - -essentials.hat.prevent-type.*
    - '*'
    - -vanish.effects.*
    - +vanish.effects.toggle.all
    inheritance:
    - admin
    info:
      prefix: '&4&l'
      build: true
      suffix: ''
```
Also, in your `g:essentials_builder` group, you've accidentally (?) added the permission `essentials.hat.prevent-type.*` as true instead of negating it (which would force this behaviour for any group that inherits that it) and in your `g:essentials_admin` group you've set `essentials.*` to true (which will have the same consequence as stated at the beginning of this post).

**Comment by CastorDarkHeart** [comment]
I was attempting to follow another someone's suggestion that lead me to another page. I'm not always good at figuring out how to work through this stuff xD
I'll try and fix that when I get home from work.

**Comment by CastorDarkHeart** [comment]
Triagonal, that fixed it! 
Thank you much for the help!
