### ISSUE TITLE
Select entities (@a, @p, ...)

### ISSUE THREAD

**Issue by Kisuu** [EssentialsX/Essentials#2834]
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**
Can't select entities (@a, @p, ...) when the plugin is on in 1.14.4 version but the plugin work well with no error message on the console.

**What I have tried**
I tried to launch my server with craftbukkit, spigot and spigot but same problem. It doesn't work in game, in the command block and the console

**Error message**
It just say in the command block and the console, that "can't find the player" when I try something like /kill @p.

**Comment by pop4959** [comment]
As far as I know, EssentialsX has never explicitly supported selectors in commands, and so it's not a bug (and you will have seen no out-of-the-ordinary error messages). It was provided by Spigot prior to 1.14, but for whatever reason it's not anymore. Not much can be done about that other than using an older version of the server. If possible, consider using Minecraft commands instead of EssentialsX if selectors are absolutely needed. For example, /minecraft:give can be an acceptable alternative for /essentials:give.
