### ISSUE TITLE
Vanish on join

### ISSUE THREAD

**Issue by charleywolf** [EssentialsX/Essentials#2839]
I have the perms/op. Is there a way to completely remove the feature of vanish on silentjoin?

**Comment by pop4959** [comment]
Use your permission plugin. Permissions are listed on https://essinfo.xeya.me/index.php?page=permissions.

**Comment by charleywolf** [comment]
Is there a way of completely removing this?

When I use uperms and negate the perms it does not work.

(My perms are * and -essentials.silentjoin.vanish)

**Comment by pop4959** [comment]
You may want to try without * or op (since neither of those are good practice, nor recommended), or use a modern permission plugin such as [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) which is known to work. This is not a bug with Essentials, so I suggest trying both of those things to find out what isn't working.

If you're still having trouble, I recommend visiting the [Discord support server](https://discord.gg/PHpuzZS), where there are thousands of people that may potentially be able to help you configure it correctly. :smiley:
