### ISSUE TITLE
Unicode Turkish charachter problems

### ISSUE THREAD

**Issue by unwillexist** [EssentialsX/Essentials#2845]
Turkish charachters like ğĞ ıI iİ öÖ üÜ çÇ şŞ are doesn't look properly when you use it in locale file. Since I added corrected Turkish locales with Turkish charachters all Turkish messages doesn't render properly, but I saw that all Ukrainan, Russian, German locales works perfectly.

My temporary solution is

ğ – \u011f
Ğ – \u011e
ı – \u0131
İ – \u0130
ö – \u00f6
Ö – \u00d6
ü – \u00fc
Ü – \u00dc
ş – \u015f
Ş – \u015e
ç – \u00e7
Ç – \u00c7

Using these chars like this as unicode numbers.

**Comment by pop4959** [comment]
Perhaps the file is being read in the wrong file encoding? Have you tried utf-8?

**Comment by mdcfe** [comment]
Due to an issue with Java, `.properties` files don't support UTF-8 by default. We're planning to work around this in a future update. For now, you can use a [converter](https://www.mobilefish.com/services/unicode_escape_sequence_converter/unicode_escape_sequence_converter.php) that should allow the file to load.

**Comment by unwillexist** [comment]
Thank you.
