### ISSUE TITLE
Better /baltop

### ISSUE THREAD

**Issue by AyItsJayy** [EssentialsX/Essentials#2849]
### Feature request

**Feature description**

Better /baltop formatting - Being able to display on /baltop the displayed name as in the essentialsxchat part of the configuration file of offline players

**How the feature is useful**

Currently, when someone does /baltop it only shows plain white text for those offline. For server owners and players, seeing the ranks of those at the top can help to push players to work harder if they see that a member has the top balance spot as opposed to a VIP player.

**Comment by pop4959** [comment]
I'll leave this marked as an enhancement, but this is currently not feasibly possible because of how Spigot exposes player display names (they must be online). I will say it's not a bad suggestion, and if it was possible it would probably already be done like this instead. Sorry for any disappointment.

Future interested readers: if it becomes possible to get a display name for an offline player, feel free to make a pull request suggesting these changes.

**Comment by AyItsJayy** [comment]
Thanks for explaining it @pop4959! I'm starting to get into programming so sorry if I misunderstand this but would it be technically possible to have some sort of cache / storage of player names once they join that can then be displayed forever? Like a text file or some type of storage where once they log in, their displayname is stored there?

**Comment by pop4959** [comment]
@AyItsJayy No problem, I'm happy to explain anything within my understanding. To answer your question, yes it is of course it should be possible to cache players' display names, but that would have to be managed entirely on the side of Essentials. It would still not be able to show players who have not been cached yet.

Now the question inevitably may be: "Why don't you just do this then?". The main reason would be that the core developers have lives outside of the project and only have so much time they can dedicate to implementing new features. Much of the time goes to general maintenance of things that are already in place. The main person handling things right now is md678685, and he's been busy all week. It's not likely that there is time for a minor feature request like this since there are much bigger ones to tend to (such as fixing bugs or implementing features with greater impact).

Even so, let me remind you once again that we do regularly consider pull requests. Regardless of what the issue may be, we usually do not turn down contributions for things that are reasonable changes. This of course means that (usually) some developer other than the person who suggested it deemed that change important enough to put in the time to implement it.

You mentioned you are getting into programming, so if you want you could give it a shot. If not, I could add an "open to pr" tag to this issue. Although, if you want that, I would just suggest making the title less vague / ambiguous, since otherwise people might scroll past it.
