### ISSUE TITLE
How to disabled module of economy ?

### ISSUE THREAD

**Issue by Crazzoxx** [EssentialsX/Essentials#2903]
in title

**Comment by triagonal** [comment]
You can't disable the Essentials economy - however, Essentials will make an effort to use other economies instead of its own, provided that the user has Vault installed and that the alternative economy is compatible with Vault.

After this happens, you can then use Essentials economy commands to control the alternative economy. If you would rather this didn't happen, simply do not give permissions to any player to use the economy commands, or add them to the `disabled-commands` section of the config.

**Comment by maheshprog** [comment]
GemsEconomy is not getting picked up by Vault, so EconomyShopGUI is only using EssentialX's economy.
