### ISSUE TITLE
/replytoggle simply not working

### ISSUE THREAD

**Issue by Burchard36** [EssentialsX/Essentials#2911]
### Information

**Full output of `/ess version`**:

```
[18:08:49 INFO]: Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-31 (MC: 1.15.1)
[18:08:49 INFO]: EssentialsX version: 2.17.1.11
[18:08:49 INFO]: Vault version: 1.7.2-b107
[18:08:49 INFO]: EssentialsXChat version: 2.17.1.11
[18:08:49 INFO]: PlaceholderAPI version: 2.10.4
```

**Server log**: https://gist.github.com/Burchard36/f3b7d052c56db53d1b75c9de46833c91

**EssentialsX config**: https://gist.github.com/Burchard36/fe5e7af446ce6d861aa3b0726136f47d

### Details

**Description**  
There is not much to this bug, no error/anything and get the generic "reply toggle is enabled" when
typing /replytoggle

**Steps to reproduce**  
Simply type /tell <player> hi then type /replytoggle 

**Expected behavior**  
Instead of typing /r each time when you pm someone in chat it auto does /r for you when attempting to talk

**Screenshots**  
None needed, no output of any errors and just say "Reply toggle has been enabled"

**Comment by triagonal** [comment]
That isn't what the `/replytoggle` command does. The `/replytoggle` command switches between whether your replies go to the last person that messaged you, or the last person you messaged. 

It's useful if other people tend to message you in the middle of a conversation but you still want to reply to the last person that you messaged, instead of the last person that messaged you.

**Comment by pop4959** [comment]
This is off-topic but: Wait this is a command? I remember when that was changed but I didn't know there was a toggle command for it!

But yeah no, there isn't any command that will automatically type things for you. There is auto-complete, but you need to press TAB for that!
