### ISSUE TITLE
Teleporting to home bed and falling through the void using carpet

### ISSUE THREAD

**Issue by Badcraft** [EssentialsX/Essentials#2918]
### Information

**Full output of `/ess version`**:
![image](https://user-images.githubusercontent.com/40553947/71640026-411e6580-2c48-11ea-94b9-ee2b5578786a.png)

**Console output**
Error: Only in-game players can use home.

**Server log**:
https://gist.github.com/Badcraft/3bf8227f51d86d5b1a193d68eb228048

**EssentialsX config**:
https://gist.github.com/Badcraft/eb37cca303ac8a0fd3b6ffde8e71e676

### Details

**Description**  
The bug works with having a bed 5 blocks at blocks at or below when players try to teleport to their home bed they would get sent below bedrock into the void if carpet is around their bed if the chunk is unloaded

**Steps to reproduce**  
(**1**) Place carpet every side around your bed
(**2**) Run far away to unload the chunk
(**3**) Do _/home bed_

**Expected behavior**  
It is supposed to just teleport players to their bed spawn

**Screenshots**  
Not possible as it won't be giving the best example if you like I can record a video

**Comment by Badcraft** [comment]
This bug also has happened on the default config of essentials X
Video of the bug: https://www.youtube.com/watch?v=oBOMkyKaq2s&t=2s

**Comment by pop4959** [comment]
Unable to replicate on the version below using the exact method in the video.
```
[00:37:34 INFO]: Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-32 (MC: 1.15.1)
[00:37:34 INFO]: EssentialsX version: 2.17.1.47
[00:37:34 INFO]: LuckPerms version: 4.4.1
[00:37:34 INFO]: Vault version: 1.7.2-b107
[00:37:34 INFO]: EssentialsXChat version: 2.17.1.47
[00:37:34 INFO]: EssentialsXGeoIP version: 2.17.1.47
[00:37:34 INFO]: EssentialsXAntiBuild version: 2.17.1.47
[00:37:34 INFO]: EssentialsXSpawn version: 2.17.1.47
[00:37:34 INFO]: EssentialsXProtect version: 2.17.1.47
```

From the video (in particular, at 1:06) it appears that the player is teleported to the correct location, but then falls. This is almost certainly an issue with client or server-side lag, rather than with Essentials, especially considering that the player had to unload the chunks for this issue to occur. For that reason, I am going to close this issue now (although if other servers report having this issue as well we may look into investigating it further). Thank you!

**Comment by pop4959** [comment]
This issue may have some merit. Still not an EssentialsX bug (we cannot fix it), but it seems like it may be related to [MC-153463](https://bugs.mojang.com/browse/MC-153463).

**Comment by snurre0** [comment]
Too bad this can not be worked around in EssentialsX :\
I understand that it can't, it's just a big issue on our server, where we've had to replace inventories several times already.
From what I have seen, it's indeed related to teleporting to unloaded chunks, or at least happens more often then.

**Comment by pop4959** [comment]
@snurre0 Do your best to work around the issue until it is fixed by Mojang. You can, with confidence, tell your players that this is a bug in the game, and not your server. Perhaps post a PSA linking MC-153463 to spread awareness. Whatever the case, don't worry too hard because it isn't something anyone can fix right now except for Mojang (and perhaps Spigot/Paper if the decide to pursue the bug on their end). :sweat_smile:

**Comment by snurre0** [comment]
Well yeah, that is true. And we do our best :)
I don't really worry, but we do have to replace inventories when it happens, which is a pain to do manually by cross checking nbt data in old backups (because you know, players do lie about their stuff).
Looking into some inventory backup plugin now.

Thanks for the quick reply! ;)
