### ISSUE TITLE
/createkit gives an 

### ISSUE THREAD

**Issue by Dinoosawruss** [EssentialsX/Essentials#2924]
### Information

**Full output of `/ess version`**:
```
>.... [05:49:04 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-237 (MC: 1.14.4)
>.... [05:49:04 INFO]: EssentialsX version: 2.17.1.0
>.... [05:49:04 INFO]: LuckPerms version: 4.4.1
>.... [05:49:04 INFO]: Vault version: 1.7.2-b107
>.... [05:49:04 INFO]: EssentialsXGeoIP version: 2.17.1.0
>.... [05:49:04 INFO]: EssentialsXSpawn version: 2.17.1.0
```

**Server log**: https://gist.github.com/Dinoosawruss/30067ade4919c27ae556b1040c769160

**EssentialsX config**: https://gist.github.com/Dinoosawruss/0cfb406bf8a19ca35b91511e6f6fa6d6

### Details

**Description**  
When I use /createkit to make a kit the item given when the kit is collected has a different NBT tag to the item that was used to create it. This means that the crate keys I give in a kit do not work with a villager trade setup on the server as the real crate keys have NBT tag 4 but the ones given by the essentials kit have NBT tag 3

**Steps to reproduce**  
1. Get an item with an NBT tag 
2. Run /createkit (name) (delay)
3. Attempt to get the kit
4. See bug (Items will have 2 different NBT tags)

**Expected behavior**  
The items should have the same NBT tags

**Screenshots**

**Comment by mdcfe** [comment]
`/createkit` is a convenience command - it is not a full replacement for manual kit creation. Capturing NBT data would require direct access to NMS/OBC code which EssentialsX avoids, and we'd need to include code to detect every single possible type of NBT that is used in vanilla to avoid duplicating that information.

If your crates plugin has a command to give the user a valid key, you can add it to your kit under the items section. Otherwise, if it integrates with EssentialsX by providing an item resolver, you may be able to use a shortcut (though I'm not sure if any crate plugins do this).

You can also add the NBT tags to the end of the item entry if you know what they are, assuming this doesn't cause issues with your crates plugin (it may break tracking of unique keys, for example).
