### ISSUE TITLE
Bypass command cost

### ISSUE THREAD

**Issue by Subilan** [EssentialsX/Essentials#2976]
It’s my fault to ask such question on GitHub without looking through the wiki content, sorry!

**Comment by pop4959** [comment]
You should read through <https://essinfo.xeya.me/permissions.html> carefully, because that already exists with the `essentials.nocommandcost` nodes as described there.

For questions about plugin usage, please visit the [Discord server](https://discord.gg/PHpuzZS) instead of using Github. It's generally much faster and easier.
