### ISSUE TITLE
/hat command couldn't have op or all permissions player wear hat.

### ISSUE THREAD

**Issue by flandretw** [EssentialsX/Essentials#2991]
Details

Output of /ess version

Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-76 (MC: 1.15.2)
EssentialsX version: 2.17.1.54
GroupManager version: 0.3.0
PlaceholderAPI version: 2.10.4
Vault version: 1.7.2-b107
Citizens version: 2.0.26-SNAPSHOT (build 1813)
EssentialsXChat version: 2.17.1.54
EssentialsXProtect version: 2.17.1.54
EssentialsXGeoIP version: 2.17.1.54
EssentialsXAntiBuild version: 2.17.1.54
EssentialsXSpawn version: 2.17.1.54

Description
Player have op or all permissions group can't wear hat and it say "You cannot use this item as a hat!"

Video Link
https://www.youtube.com/watch?v=7aFuVHtmAG4

**Comment by DeleteMetaInf** [comment]
This is because there’s a permission to prevent a certain item from being used as a hat:
_essentials.hat.prevent-type.<item-name>_

Since OPs have all permissions, they also have _essentials.hat.prevent-type.*_, meaning they can’t use any item as a hat. It’s a bit silly, but that’s just how it is.

To fix this, simply negate this permission for the group that has all permissions.
Example, if you’re using [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/):
`/lp group owner permission set essentials.hat.prevent-type.* false`

**Comment by DeleteMetaInf** [comment]
This is because there’s a permission to prevent a specific item or block from being used as a hat:
_essentials.hat.prevent-type.\<item-name\>_

Since operators have all permissions, they also have _essentials.hat.prevent-type.*_, meaning that they can’t use _any_ item as a hat. It’s a bit silly, but that’s just how it is.

To fix this, simply negate this permission for the group that has all permissions.
Example (if you’re using [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/)):
`/lp group owner permission set essentials.hat.prevent-type.* false`

This will let players of that group use any item or block as a hat. You don’t have to do this for the regular player group as that group doesn’t have all permissions.

**Comment by Nevrai** [comment]
This is because there’s a permission to prevent a specific item or block from being used as a hat:
_essentials.hat.prevent-type.\<item-name\>_

Since operators have all permissions, they also have _essentials.hat.prevent-type.*_, meaning that they can’t use _any_ item as a hat. It’s a bit silly, but that’s just how it is.

To fix this, simply negate this permission for the group that has all permissions.
Example (if you’re using [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/)):
`/lp group owner permission set essentials.hat.prevent-type.* false`

This will let players in that group use any item or block as a hat. You don’t have to do this for the regular player group as regular players don’t have all permissions.
