### ISSUE TITLE
Unsafe offline player data lookups

### ISSUE THREAD

**Issue by Einsfier** [EssentialsX/Essentials#3014]
### Information

**Full output of `/ess version`**:

```
Server : 1.15.2-R0.1-SNAPSHOT git-Paper-105 (MC: 1.15.2)
EssentialsX : 2.17.1.60
LuckPerms : 5.0.78
Vault : 1.7.2-b107
Citizens : 2.0.26-SNAPSHOT (build 1792)
EssentialsXProtect : 2.17.1.60
EssentialsXGeoIP : 2.17.1.60
EssentialsXChat : 2.17.1.60
EssentialsXAntiBuild : 2.17.1.60
EssentialsXSpawn : 2.17.1.60
WorldEdit : 7.1.1-SNAPSHOT+4871-f752b01
```

**Server log**: https://gist.github.com/povsister/7ecf63dea360dfdfba33ae6441f6b077

**EssentialsX config**: https://gist.github.com/povsister/432300acf822a218493618d55214f8d5

### Details

**Description**  
Unsafe offline player data lookups intercepted by Luckperms
which cause huge ERROR log output. (more than 300MB per hour)

**Steps to reproduce**  
Probably by using worldedit with command //brush apply sphere 4 item sand
I am not 100% sure of this. If this is a WE bug. pls close the issue.😂
(See the console output)

**Expected behavior**  
No error should occur.

**Screenshots**  
![image](https://user-images.githubusercontent.com/11040951/74599270-200bba00-50ba-11ea-8b7d-f92f238bb9aa.png)

**Comment by pop4959** [comment]
This error is not a bug in Essentials. Also, Essentials does not provide any support for servers running offline. Secondly, the error was thrown by LuckPerms. Please read carefully and follow the instructions written there, as it looks like you may be able to fix this on your own.

**Comment by Einsfier** [comment]
> This error is not a bug in Essentials. Also, Essentials does not provide any support for servers running offline. Secondly, the error was thrown by LuckPerms. Please read carefully and follow the instructions written there, as it looks like you may be able to fix this on your own.

Indeed, this ERROR is not thrown by Essentials. But it happens during passing BlockPlaceEvent to ESS anti-build.
Luckperms who throw this ERROR indicates that this is a "unsafe" lookup intercepted and it should be fixed in the plugin who make the "unsafe" operation.
So that's why I am here seeking for troubleshooting.

By the way. Mojang sold the copyright to Netease in China mainland. but Netease almost f**k up everything. Secondly, causing the deal mentioned above, Mojang didn't  deploy any authentication server or CDN node in China which results in very unstable authentication service. People who lives in China even need a VPN to access Mojang International for changing their name or skins.
So that's why most of cutting-edge servers in China are running offline mode for both Mojang players and cracked players. If this annoyed you, I apologize.

Anyway. Thank you for your patience and effort.

**Comment by pop4959** [comment]
I see, thanks for the explanation. I mean no disrespect. I see you appear to have good reasons for wishing to play in offline mode. However, the Essentials team generally does not look into issues caused by servers operating in offline mode. This "unsafe" lookup error is almost certainly caused by this, as far as I'm aware.

Although, to help with your troubleshooting, I have the following advice. The way I see it, you have these options to choose from:

1) Test for this problem on a server running in online mode, with only EssentialsX, EssentialsXAntiBuild, Vault, and LuckPerms installed. If it persists, please create a new issue with relevant information, and state exactly what you are doing to cause it to happen (step by step, if possible). This would allow the Essentials team to look into the issue further.

2) Change the setting in the configuration of LuckPerms as described in the error. It warns that there may be a slight performance hit, however I think you should be fine.
>Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
in the LP config, but should consider the consequences (lag) before doing so.

3) Replace EssentialsXAntiBuild, and use a different plugin for your offline mode server. Perhaps there is something else that will suit your needs better.

**Comment by Einsfier** [comment]
Thanks for your advice.
I already have LP re-configured as you described above.
And I have kept monitoring the server for a while. It looks fine till now.

Also, I'll try to migrate my server from offline to online to see if the problem still exists.

Again, Thanks for your explanation and Essentials Team's effort.

**Comment by mdcfe** [comment]
If EssentialsX AntiBuild is causing LuckPerms to try and lookup perms for offline players, then something has gone horribly, *horribly* wrong in your server setup. The "offline players" that LP is referring to are not offline-mode players, but instead they are players who LuckPerms thinks aren't logged into the server. If you're using any offline-mode authentication plugins, we can't help beyond recommending you remove them, and we have no facility to test NetEase authentication so it is impossible for us to test this.
