### ISSUE TITLE
/paytoggle <Player> on/off

### ISSUE THREAD

**Issue by TKwSni** [EssentialsX/Essentials#3087]
### Feature request

**Feature description**
/paytoggle <Player> on/off

**How the feature is useful**
Allow admins take control of who can receive payments if they dont have permissions to use the /paytoggle command

**Comment by TKwSni** [comment]
Essentials /paytoggle exists but it cannot run from console and it doesnt know if it's on or off, having a command that let me choose between on/off state would be better, same function as the essentials command   /msgtoggle [player] [on\|off]

**Comment by AMDBartek** [comment]
I agree with @Blackyvk that the syntax of the `/paytoggle` command should be the same as the syntax of the `/msgtoggle` command. This would be good change because it would allow you to `/paytoggle` other players.

**Comment by pop4959** [comment]
@Blackyvk Ah I see. Didn't even know that command already existed. Thanks for the clarification, but can you describe more what "it doesnt know if it's on or off" means? Depending on your response, I may re-open this issue since it's starting to sound more reasonable (although for future reference please create issues with as much detail as possible, to avoid being seen as lazy/incomplete).

Right now if I understand correctly we have a `/paytoggle [on/off]`, and you are suggesting changing it to `/paytoggle [player] [on/off]` (effectively just suggesting to add a player target to the command). Correct me if I'm wrong. Also it would help if you can describe a situation for which the old command doesn't work, where your suggestion would be a benefit.

**Comment by TKwSni** [comment]
The command `/paytoggle ` exists without [on/off] but, that's it, it's a player command that whenever you run it it just changes the status from on to off automatically depending of the past saved state.

what I'm suggestins  is that `/paytoggle [player] [on/off]` so console or admins can run the command for the player, benefits are that:

 Console and OP can run the command for the player. if you run the command for the player you are sure that you are toggling it on or off.

**Comment by pop4959** [comment]
Well, I mean, that is pretty much the definition of what "toggle" means. But yeah, let's keep this open for now until someone can look into it and/or make a pull request.
