### ISSUE TITLE
/pweather can be used to make the trident "Riptide" effect when it's not actually raining.

### ISSUE THREAD

**Issue by DataNull8** [EssentialsX/Essentials#3118]
Hello, my players have recently found a bug involving tridents and /pweather on our server, we recently decided to give everyone /pweather on the server and we found this out. Basically when you put Riptide on a trident, do /pweather storm when it's not actually raining or is a storm, you can use the Riptide effect to fly around everywhere and abuse the glitch to use the effect forever. This is pretty overpowered and might cause us to disable pweather.

**Comment by pop4959** [comment]
Both pweather and ptime change how players perceive the state of the server client-side. So actually for them it is "actually raining", regardless of what the weather actually should be for them. I would say this falls into expected behavior of the command, and is not a bug. You can disable the command if you do not want players controlling their weather.

**Comment by DataNull8** [comment]
Yeah but like you can literally infinitely fly around when it's not raining for anybody else using a trident, so infinite fly time for tridents, pweather is supposed to be local to your player when flying around in tridents infinitely is not local and seems more like a bug and not the expected behavior

**Comment by mdcfe** [comment]
From what I recall, riptide is done client side and the server doesn't validate whether they're in a world that is actually raining.

For now, the solution is to only allow players you trust to use `/pweather`.
