### ISSUE TITLE
Nickname Addon Feature Request

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#3130]
**Feature description**
I suggest adding an option in the config to allow people to hover over a person's nickname ign
and it would show the actual player's name with an option in the messaging to change the color of the placeholder preview of the person's name

**How the feature is useful**
Sometimes some ban plugins cannot read usernames so by the time let's say i /realname that person and ban them, that's enough time for them to complete that action, that being hacking, spamming and advertising

**Comment by ghost** [comment]
I think this kind of feature would be better suited to another plugin. For example, I use deluxechat which handles hovering over the player and also supports PAPI.

Just saying this because esschat is a relatively simple chat plugin and adding hover functionality seems out of the scope.

**Comment by pop4959** [comment]
I don't think this is possible at the moment either due to lack of support for chat components in Essentials. Check out discussion #2391 for details on how this is planned to be improved in the future, and feel free to leave your comments there and ideas.

Also, as kadenscott mentioned, you should be able to easily get another plugin to do this. It can probably even work alongside EssentialsChat (if it doesn't replace it). This is a fairly niche feature that I'm not sure is "essential" for most server owners.

By the way, for your original problem, maybe get a better ban plugin. It sounds like a complete joke if you need the person's display name to ban them. Some display names can be totally unreadable. You should be able to ban by username. Also, consider getting a logging plugin.
