### ISSUE TITLE
[Suggestion] A few moderator tools

### ISSUE THREAD

**Issue by iCyberHD** [EssentialsX/Essentials#315]
Just wanted to leave a few suggestions since this is an amazing project <3

-/warn (player) (reason) - Warns the player with the given reason
-/freeze (player) - Toggles if the player can move and gives the player a message such has "You have been frozen by {moderator name}!
-Some way to check a players past usernames even if that player has never logged into your server

**Comment by Someone-NEW** [comment]
nice idea

**Comment by Dooleylabs** [comment]
I know you can set the players speed to 0 to achieve the same effect as freeze, but the warn command is a feature I'd definitely like to see integrated with essentials.

**Comment by iCyberHD** [comment]
@Dooleylabs If your speed is 0 you can sill jump around. :P

**Comment by drtshock** [comment]
/warn can be done by just messaging the player..
/freeze - we have /jail
Checking a name isn't something we will do since we don't want to be adding lots of queries against Mojang.

**Comment by Someone-NEW** [comment]
O nice i have a suggestion to be possible in some world feature make so that can be enabled or disabled /broadcast  /bc in some world only in one wordl and chose in witch worlds will be globaly and witch separate or a make a group for broadcasting ans will be possible this group enable/disabel in config.yml this is by me realy usefule beacause some game use broadcasting and is seeing in all worlds but not need to be more spam from there. So when you can will be realy cool feature. nice work man thank you.

**Comment by drtshock** [comment]
Can you make separate tickets for separate suggestions please.
