### ISSUE TITLE
Implement RTP or Wild Command/Feature

### ISSUE THREAD

**Issue by sharkaholic** [EssentialsX/Essentials#3154]
### Feature request

**Feature description**
**Add a /RTP or /Wild Command to EssentialsX!**

**How the feature is useful**
**RTP Plugins are a pretty common download for most server owners. It gives their players the ability to teleport to a random location in the world and begin exploring! The plugins are few and far between, often with problems or left unmaintained. It'd be nice to see it added to EssentialsX as you guys are pretty awesome at maintenance!**

**Comment by JRoy** [comment]
I'll do this once #3102 is merged that way I don't have to write the logic sync then rewrite the logic async again.

**Comment by sharkaholic** [comment]
Fantastic, thank you guys for your quick replies! Very happy with EssentialsX. Made my life a lot easier!

**Comment by pop4959** [comment]
I had actually been thinking about this recently as well (@triagonal can attest to this 😛). I was wondering why there hasn't been an issue or PR made for this before now.  A random teleportation command is extremely standard on most current survival servers and I could definitely see it being included in the Essentials suite of commands.

One possible concern I had (which I'm sure is shared among the maintainers) is that people have widely different expectations of what random teleportation should entail. In my opinion, Essentials could provide a simple implementation, providing for safe teleportation from a configured location (e.g. spawn) within a certain distance range. It would be up to server owners to decide whether that is enough for them, or if they need a more sophisticated random teleportation plugin.

Also I agree with @JRoy that we should probably get proper support completed for async teleportation with Paper before working on this, since it is so highly reliant on Essentials' teleportation methods. Let's also keep this up for discussion for a while regardless so more people can give their feedback on what they'd like to see.

I would also suggest that this be named `/tprandom` or `/tpr` as that would coincide well with Essentials' teleportation command naming scheme. It would also reduce conflicts with servers already using another random teleportation command, which typically use `/randomtp`, `/rtp`, `/wild`, etc. Users could always add these as aliases or override other plugins with the commands.yml file.

**Comment by ghost** [comment]
I like the idea! From the suggestions of @pop4959 I would also like to add to the suggestions list about this topic, an option to disable it. It would be very helpful for most of servers since most of them use them, but for specifics servers that already have a very detailed RandomTP plugin installed, they won't need it so maybe it can save them some cpu if they disable that future idea. Other than that, I really like this idea and would love to see it on Essentials.

**Comment by mdcfe** [comment]
@Tomi010817 
> an option to disable it

FYI, all commands in EssentialsX can be disabled through a permissions plugin. They will not consume any CPU cycles unless someone runs them, and if you disable them in your permissions plugin, they can't be run so they will have effectively no impact on your server at all.

---

This is waiting on #3102 - once that PR is merged, an async version of this can be implemented.

**Comment by triagonal** [comment]
The random teleport feature has been implemented in 76e511a and is present in versions `2.17.2.158` and above. Download the latest build [here](https://essentialsx.net/downloads.html).

**Comment by in2gaming-com** [comment]
Hi i cant find the rp command

**Comment by Chew** [comment]
It's /tpr, please avoid commenting on old posts and ask us on the MOSS Discord instead.
