### ISSUE TITLE
Condense wont work with named items?

### ISSUE THREAD

**Issue by Disorbs** [EssentialsX/Essentials#3158]
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-155 (MC: 1.15.2)
11.04 17:50:32 [Server] INFO EssentialsX version: 2.17.2.43
11.04 17:50:32 [Server] INFO PlaceholderAPI version: 2.10.5
11.04 17:50:32 [Server] INFO LuckPerms version: 5.0.72
11.04 17:50:32 [Server] INFO Vault version: 1.7.2-b107
11.04 17:50:32 [Server] INFO Citizens version: 2.0.26-SNAPSHOT (build 1815)
11.04 17:50:32 [Server] INFO EssentialsXSpawn version: 2.17.2.43
```

**Description**  
Condense wont convert 64 diamonds that are renamed?

**Steps to reproduce**  
Get any item that can be condense and rename them anvil/give
and when you try to /condense it doesn't work

Also: how come shock said any item that is a 2x2/3x3 recipe will work but melon slices dont?

**Comment by mdcfe** [comment]
This is intended behaviour. `/condense` converts items that have a 2x2 or 3x3 **reversible** recipe. That means, the result of the recipe must be able to be converted back to the original item by putting it in a crafting grid on its own. `/condense` will not convert renamed items as this can't be reversed through vanilla recipes to get the previous renamed item. Similarly, melon blocks cannot be put back into a crafting grid to get melon slices, so `/condense` will not convert melon slices to melon blocks. This is to prevent players losing items through accidentally condensing items that can't be reversed easily.

Since `/condense` is completely based on the recipes loaded into the world, you can add a melon block -> 4 slices recipe through a plugin or data pack and `/condense` should detect this and start converting melon slices.
