### ISSUE TITLE
EssentialsX teleport cause lags

### ISSUE THREAD

**Issue by mlegok12** [EssentialsX/Essentials#3163]
I'm using Tuinity (For for paperspigot)
1.15.2
Latest version of EssentialsX + Essentials Spawn]
When i use teleport commands like /tpaccept, /spawn /warp and etc it causes lags.
https://timings.aikar.co/?id=2b35b2f89eba41d5a94b173dfc6092f0

**Comment by pop4959** [comment]
Good job with your timings, they look very good! Essentials doesn't appear as if it should be causing any noticeable lag on your server. It's true that it's displayed on the lag tab, however if you look at the count and avg ms per, you can see that it's only skipping one or two ticks about 5 times in the hour. Players generally are not going to notice this, and your server's TPS should stay at 20 due to catch-up ticks. Don't let it cause you undue stress.

Essentials teleportation can sometimes be a bit on the slow side due to the fact that it currently uses Spigot's chunk loading (sync) to load the one chunk that players directly teleport to to check for teleportation safety. The timings for teleportation tasks may be reduced once #3102 is merged (which you can download and test now if you wish). This aims to move things over to use Paperlib to load the chunk async before teleporting the player (which will be handled by the server, also async).
