### ISSUE TITLE
Homes don't translate from my 1.7.3 server to essentialsx after uuid conversion

### ISSUE THREAD

**Issue by Nukley** [EssentialsX/Essentials#3172]
When I was converting my old essentials beta 1.7.3 server to my essentialsx 1.15.2 server, it did convert player files to uuid, which is fine, but then i noticed that homes did not translate over, and after comparing the original playername files to the new uuid files, i noticed the format for homes are identical, excluding some indenting and the ordering of tags. My question is, why can't this be done? 
You could just say to manually convert them over, but I have 147 user yml files, so that might take a while. The server was in offline mode, for both pre and post conversion

Image attached shows the homes list of the same user, pre and post uuid conversion.
![image](https://user-images.githubusercontent.com/26724236/79397972-762b9b00-7f4d-11ea-9844-57cc6115ed6c.png)

**Comment by pop4959** [comment]
EssentialsX only supports servers running MC 1.8.8-1.15.2, and also does not support offline mode servers. So this issue will probably not be looked into. Even considering that, going from Essentials for MC Beta 1.7.3 straight to EssentialsX for MC 1.15.2 is quite a jump. Most likely one of the Essentials versions in-between changed the format. You might want to try hopping through a few of those versions. If that doesn't work, you can do it manually (or automatically with a third party JSON processing tool).

**Comment by mdcfe** [comment]
I'd recommend upgrading via CraftBukkit 1.7.10 and Essentials 2.14.3 - these versions have a better chance of migrating properly since they were UUID transitional versions. After that, you can try the latest version of EssentialsX on a 1.15.2 server.

FYI, your server's performance will probably suffer if you move your world straight from Beta 1.7.3 to 1.15.2 - you might want to consider running `--forceUpgrade`s on 1.15.2 to help with this.
