### ISSUE TITLE
Error with quickshop

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3182]
Hello I use quickshop(4.0.2.1) and essentialsX 2.17.2.61

I have an error the developer of quickshop told me to come and report the bug to you
https://pastebin.com/xr7hbnT9

**Comment by pop4959** [comment]
This appears to be a bug with QuickShop, because it is passing in null (nothing) as the username for a player. That is completely bogus, and that should be prevented from happening from within the other plugin. We can't do anything about it except to tell you to report back to the author of that plugin to fix it, or suggest that you use a different plugin.
