### ISSUE TITLE
Setting to set barrier as a safe block to teleport

### ISSUE THREAD

**Issue by TheNety** [EssentialsX/Essentials#3184]
### Feature request

**Feature description**

Hey, so I have the same issue as in https://github.com/EssentialsX/Essentials/issues/3041 and  https://github.com/EssentialsX/Essentials/issues/2464 - I want players be able to teleport on a top of barrier, but I don't want to disable teleport-safety check. So would it, please, be possible to add there some blocks whitelist, which would be considered as safe, or just a option for barriers?

**How the feature is useful**

Teleport safety check can be turned on, but players can teleport on top of a barrier, when turned on.

**Comment by pop4959** [comment]
As mentioned in the other issues, this is by design. Essentials teleport does not place you onto non-opaque blocks. I think it's a dumb idea to make additional config options for every exceptional circumstance where server owners may wish players to be able to teleport onto a specific unsafe block, however perhaps the safety exception list / whitelist you mentioned could be a general enough solution for this kind of problem. Another possible (but probably unlikely) solution would be if new API was added to Bukkit which defines "solid" blocks (those with collision, which players can stand on) instead of opaque/transparent (which Essentials uses instead to get a rough estimate for if a spot is safe). I would like to defer the decision on this to @md678685 as to whether we want to look further into this, as it looks like I already closed the previous two issues and perhaps I'm biased about this.

It would also be helpful if you could explain what your use case for teleporting onto barriers is though, because as far as I can think of, there's still no reason you shouldn't be able to easily get around this by 1) not using a barrier block, or 2) using a non-Essentials command to teleport people.

**Comment by TheNety** [comment]
Well, I know I've run into some issues with it in past months. For example having barrier on top of the 1v1 arena, on top of the spawn, maze etc., also players then report it as bug if they want to teleport someone to them and they're on barrier. I mean ye, it's pretty rare issue, not happening so often..
