### ISSUE TITLE
/invsee, /tpaccept and /msg problems

### ISSUE THREAD

**Issue by Elric02** [EssentialsX/Essentials#3185]
### Information

Full output of `/ess version`:

Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-185 (MC: 1.15.2)
EssentialsX version: 2.17.2.0
PlaceholderAPI version: 2.10.5
LuckPerms version: 5.0.72
Vault version: 1.7.2-b107
Citizens version: 2.0.26-SNAPSHOT (build 1852)
EssentialsXChat version: 2.17.2.0
ChestShop version: 3.10.1 (build 174)
EssentialsXSpawn version: 2.17.2.0

**Server log:** No log related on command, or on startup and shutdown

**EssentialsX config:** https://pastebin.com/btK3xujC

### Help request

**Problem**
I actually got 3 problems, but it might be related, as I started experiencing them on 1.15 & essentials 2.17.2 update, I had nothing before.
- /invsee : I can't take any item from my self inventory, not even with shift+click. However, I can modify and take items from the inventory I'm looking in
- /tpaccept : (Happens only sometimes, we didn't understand exactly when ; we've tested with command aliases, some tricks like accepting twice, nothing proved) When a player asks to tp to another with /tpa, the only player accepts with /tpaccept (or /tpyes) but it says "no pending request. The first player doesn't cancel the tp request
- /msg (Happens also sometimes, no idea when ; tested with command aliases too, and still no idea) When a player sends something to another, the command displays correctly on the console, but the destination player doesn't receive anything

Thanks by advance

**Comment by pop4959** [comment]
Unfortunately we can't do much about these issues unless you have a way to reliably reproduce them on the latest version. It would also help if you could make one issue per problem (so that it can more easily be tracked). If you have a way to confirm that these problems are not a plugin conflict or permission issue on your server, please make another issue reporting it as a bug, with a clear description of how it occurs.
