### ISSUE TITLE
/suicide death message

### ISSUE THREAD

**Issue by piperwillow** [EssentialsX/Essentials#3189]
# Feature request

**Feature description**
When using the /suicide command have the death type be 'suicide' instead of 'custom'.

**How the feature is useful**
So that plugins such as Death Messages Prime can have custom messages that don't overlap with other plugins.

**Comment by pop4959** [comment]
~~Feel free to ask the author of Death Messages Prime to make a pull request on Essentials. If it is a plugin conflict that can be resolved without any awkward side effects by making this change, we could probably consider adding it.~~

Yeah no, it happens to be an actual issue with the suicide commands. I've made a PR to fix this.

**Comment by mdcfe** [comment]
The way `/suicide` works is... odd. It looks like the command sets the damage cause before it actually damages the player, and I'm not sure if this is how this is supposed to be implemented or not. I've also noticed that the DamageCause is usually CUSTOM rather than SUICIDE, so it seems like something's up with how this command is implemented.

https://github.com/EssentialsX/Essentials/blob/b72d822f9453e368a5fab60af01b8e86beb22185/Essentials/src/com/earth2me/essentials/commands/Commandsuicide.java#L17-26

**Comment by triagonal** [comment]
This has been fixed in EssentialsX versions `2.17.2.140` and above. Download the latest build [here](https://essentialsx.net/downloads.html).
