### ISSUE TITLE
Add cmds for stonecutter, loom...

### ISSUE THREAD

**Issue by Melvout** [EssentialsX/Essentials#3195]
### Feature request

Hi !

**Feature description**

Is it possible to add several commands that provide an access to the stone cutter, loom, grindstone ( and others ) interfaces such as the actual **/workbench** command.

**How the feature is useful**

This feature is just to be consistent with the fact that the **/workbench** already exists and the version 1.14 added new blocks to interact/craft with.

**Comment by editid1** [comment]
wouldn't work bcs essentials supports versions before 1.14

**Comment by pop4959** [comment]
@editid1 On the contrary, it's entirely feasible, however such commands would only work on versions that support the features. See: `/beezooka`.

**Comment by pop4959** [comment]
Apparently I was just kidding last time. It's not feasible right now for Essentials because there is no API for these crafting interfaces. If this were to be added, support needs to be put into Bukkit first. This is probably not going to happen for the foreseeable future. If you still need this functionality, is seems that [this](https://www.spigotmc.org/resources/portable-crafting-inventories-completely-customizable.61045/) plugin is specialized in doing what you want, and is updated for 1.15.

If for some reason Bukkit actually adds API for these in the future, this is still a pretty reasonable feature that could be included in Essentials, given the existence of similar commands like `/workbench`.

**Comment by JRoy** [comment]
Reopening because this is simplish with reflection and I may PR something to Paper to make it a single method.

**Comment by Srborjaa** [comment]
Hi! I've seen that 1.15 objects' interfaces cannot be used with a command, but it could be possible to add an **/anvil** and **"/enchantment"** command (ench. table), for example? I think their interface exists since time ago and can be used, like the workbench and enderchest.

**Comment by pop4959** [comment]
Makes sense, thanks for bringing that up.

**Comment by 100petr** [comment]
Up
I would appreciate these things
