### ISSUE TITLE
Enchantments Again please don't close it.

### ISSUE THREAD

**Issue by Rohanm0121** [EssentialsX/Essentials#3234]
Server log:

EssentialsX config

Help request
Problem

I enchant my leather helmet to unbreaking 30 but it isn't working properly at all... Instead it says unbreaking 30 on the armour piece but in reality it's using enchantment unbreaking 3 I need Enchantment unbreaking 30 not 3... however swords enchants work just fine. Like I know in the picture it says Unbreaking 30 but it isn't... it's actually only working like unbreaking 3 I really need help on how to fix... if you must come on the server so be it please!

What I have tried

Nothing, as I'm not sure how to fix it.

Screenshots

![4c4a8e5378c9e3c81c5ec1fdf3ea76eb](https://user-images.githubusercontent.com/56348680/81108849-210df400-8f11-11ea-90a0-3645b3075812.png)

**Comment by Rohanm0121** [comment]
We can go on the server and test this out please!

**Comment by pop4959** [comment]
Please do not keep creating new issues for the same problem. We will re-open your other issue if we deem it something worth looking into. This is not a bug. If you need help using the plugin, join the [Discord server](https://discord.gg/PHpuzZS) and visit the Essentials support channel. Thank you.

**Comment by mdcfe** [comment]
This is out of our hands.

All EssentialsX does when you turn on unsafe enchantments is save the enchantment data to the item stack. Once that's done, it's down to Minecraft itself to figure out what to do with a "level 30" enchantment. Since these enchantments aren't proper enchantments you can get in vanilla, Mojang hasn't written any special code to deal with these particular enchantments, so they won't work properly. EssX doesn't hack or alter any other part of Minecraft to make these work - the whole point is that we don't get involved beyond the process of adding the enchantments to start with.

If you want to use custom enchantments beyond what vanilla provides, you should look into a custom enchantment plugin. There are free and paid options out there, though it's not really my area of expertise so I can't recommend any.
