### ISSUE TITLE
Cant sleep with Essentialsx

### ISSUE THREAD

**Issue by MCTTV06** [EssentialsX/Essentials#3241]
I keep searching but never find a solution I can never sleep with essentialsx I deleted all my plugins and I can sleep as soon I put essentialsx I cant sleep. I tried being op and unop and nothing works any help?

**Comment by pop4959** [comment]
Please see the response to #2775

**Comment by MCTTV06** [comment]
What I meant was that it dosent turn day when someone sleeps it stays night

**Comment by pop4959** [comment]
It should still change to day if all players sleep on your server. Essentials doesn't do anything about that. The permissions for sleep should only exempt you from needing to sleep (so less than all of the players need to sleep for time to change).

If you are still convinced that this is Essentials and want to file this as a bug report instead of a question, feel free to make a new issue and provide all of the information requested, and someone will can check it out.

**Comment by supreme-idiot** [comment]
but it doesnt
