### ISSUE TITLE
Command block issued server command

### ISSUE THREAD

**Issue by gameslp** [EssentialsX/Essentials#3289]
## Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**
I installed EssentialsX and now i get this "CommandBlock at -25,3,26 issued server command: /tp @e[r=6,type=armor_stand] ~ ~ ~ ~0.8 ~" every second

**What I have tried**
reinstalling, setting command block output to false on each world

**Screenshots**

**Comment by JRoy** [comment]
There is a command block issuing that command. If you want the command block to use the Minecraft version of the `/tp` command replace the `/tp` with `/minecraft:tp`

**Comment by gameslp** [comment]
Thanks for that, but i cant find the command block i looked on every world


pt., 15 maj 2020 o 18:15 Josh Roy <notifications@github.com> napisał(a):

**Comment by JRoy** [comment]
That's not Essentials' problem but it literally tells you it's at `-25, 3, 26`

**Comment by triagonal** [comment]
If that's appearing there is definitely a command block somewhere on your server like @JRoy said. Try taking another close look. Perhaps teleport to those coordinates on each world and make sure there's definitely nothing there.

Otherwise, if you just want to pretend it's not happening, you could just set `log-command-block-commands` to `false` inside `config.yml`, which will stop the message from appearing at all.
