### ISSUE TITLE
Optional hide AFK message

### ISSUE THREAD

**Issue by foxi69** [EssentialsX/Essentials#3309]
#### Feature request

**Feature description**
I would like to see a config option where I can disable the AFK "spam" message, but still wanna use it, but only on Tab list.

**How the feature is useful**
It would be useful for the servers where plays a tons of players.

![kép](https://user-images.githubusercontent.com/2604798/82601896-8835d480-9bb0-11ea-9ef7-71917575961b.png)
[AFK] on tablist but remove afk message from chat.

**Comment by pop4959** [comment]
Could probably be addressed with an afk notify permission

**Comment by foxi69** [comment]
I think it would better if it can be switched to turn on off because for OPs we can't use negated permission.

**Comment by pop4959** [comment]
> I think it would better if it can be switched to turn on off because for OPs we can't use negated permission.

If you use any modern permission plugin, you can easily negate it. A permission would be better here because it would let server owners determine who to send the message to. Configuration would only allow you to enable or disable it globally (which might work for your use case, but won't for others).

**Comment by foxi69** [comment]
yes sure, but would it be difficult to include both?
I am using PEX and the ops always has every permissions, and can i negate after * permission?

**Comment by pop4959** [comment]
We would not include both because that adds bloat to Essentials. Only one is needed, and the better option would be chosen. It should be possible to negate the permission in PermissionsEx, even after OP and wildcards, however I recommend switching to a modern permission plugin as LuckPerms, since PermissionsEx is old, and unsupported. It should be much easier as well.

**Comment by pop4959** [comment]
On second look, seems like what you want to do is get rid of the message entirely right (only use it in tab)? See "Disabling Messages" on the [wiki](https://essentialsx.cf/wiki/Locale.html) for how to do this.
