### ISSUE TITLE
Players can die on join when fly is disable.d

### ISSUE THREAD

**Issue by MrFlacko** [EssentialsX/Essentials#3312]
If you have fly to be disabled on join, players will fall out of the sky and die if they are high enough.

There could be either an opion for invincibility on join for 30 seconds or so. Or maybe it will teleport the player to the ground automatically if they are high up with fly disabled.

**Comment by JRoy** [comment]
Grant users with fly `essentials.fly.safelogin` which will auto-enable fly on startup.

**Comment by MrFlacko** [comment]
> Grant users with fly `essentials.fly.safelogin` which will auto-enable fly on startup.

I know, but if you want the fly disabled for a user when they log back on it will kill them.

**Comment by pop4959** [comment]
As JRoy mentioned, the permission is meant to fix this problem. It will auto enable fly for the user when they log in. If they do not have access to fly, then they fall, as you would expect for someone who doesn't have fly. If you are giving temporary fly to players, this may be more of a user awareness issue rather than a problem with Essentials. You'll want to make it clear to your players that when they log back in, they will no longer be flying.
