### ISSUE TITLE
Vault: Implement an adapter for economy

### ISSUE THREAD

**Issue by mastercake10** [EssentialsX/Essentials#3344]
Currently, there is no adapter for Vault's economy contained within Essentials. Instead, there is an [ancient Adapter](https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/economy/plugins/Economy_Essentials.java) contained within the Vault plugin, but apparently that's not the appropriate way. 

I originally opened an issue (https://github.com/MilkBowl/Vault/issues/805) on the Vault repository to fix Essentials's Exception handling when depositing money. According to the author,  that adapter code is no longer maintained. So creating an own implementation for the Economy Adapter is inevitable for fixing future issues in the economy adapter, such as the issue mentioned above.

**Comment by pop4959** [comment]
This issue is phrased as more of a feature request, but it sounds like you are having some issues with the current economy implementations. It might be helpful if you put in a corresponding bug report, with all of the details necessary for a developer to look into the problem better.

**Comment by mdcfe** [comment]
Related: #1853, #2401, #3085

I've been planning to do this for a long time, but this has been delayed due to compatibility issues with the original Vault provider and the risk of data loss for NPC bank accounts. I'll look into this soon.

Vault doesn't have any interest in maintaining their own providers any more, but also doesn't make it particularly easy for us to replace theirs - we can't register on the same priority as Vault's adapter since ours will get ignored, but we also can't register on a higher priority without risking breaking other economy provider plugins, so we'll need to actively disable their economy provider instead.
