### ISSUE TITLE
Night skips. Instant sleep. Bed problem.

### ISSUE THREAD

**Issue by slayerOO7** [EssentialsX/Essentials#3354]
Full output of `/ess version`:

[12:36:25] [Server thread/INFO]: Starting minecraft server version 1.15.2
[12:37:24] [Server thread/INFO]: [Essentials] Loading Essentials v2.17.2.0

EssentialsX config: https://gist.github.com/slayerOO7/5e3d17b639b6ccda572dc27ff2e71acf

Information:

Night instantly skips. Unlike singleplayer, or without EssentialsX, I don't wait in bed for the night to skip at all. It just skips.

They say it's a permission feature. I've tried deop-ing myself. Still didn't work. I've tried changing the sleep-ignores-afk-players: true, to false. I then restarted the server, still didn't work. 

The most detailed and similar post I've looked at:
https://github.com/EssentialsX/Essentials/issues/2868

**Comment by pop4959** [comment]
This issue is easily fixed by changing the `essentials.sleepingignored` permission node to `false` in your permission plugin. If you do not have a permission plugin, then that is your problem.

Solution is to get a permission plugin and apply the correct permission node, or (coincidentally) update to the latest version of EssentialsX [here](https://essentialsx.cf/downloads.html) which has this disabled by default. It is still recommended not to use OP, however.

**Comment by slayerOO7** [comment]
Oh, I forgot to include that I already negated the nodes for all groups. So, I'm still kinda stuck, haha. I'm running the server on Aternos, so unfortunately I can't download and use the latest version of EssentialsX, as the plugins sources come only from spigotmc and dev.bukket.

**Comment by pop4959** [comment]
Negating the nodes should work fine. Your `ess version` output doesn't contain a permission plugin however. Make sure you are using a modern permission plugin such as LuckPerms. Can't do anything about you not being able to access the latest changes -- this is solely your problem to deal with.

**Comment by slayerOO7** [comment]
Do you think LuckPerms would be better than Group Manager? I was looking into that just before you said that lol, thinking that Group Manager perhaps had some errors.

**Comment by pop4959** [comment]
Yes. Group manager has not been officially updated in well over 5 years (I have personally not used it since about 2013). LuckPerms is what is recommended now, and is what most people use these days. There are other permission plugins as well, but they are not as well known or not free. The choice is yours.

**Comment by slayerOO7** [comment]
Thanks for the info and quick responses. I'll try my luck with LuckPerms.

**Comment by pop4959** [comment]
No problem, hope it fairs well for you. If not, try joining the [EssentialsX support Discord](https://discord.gg/PHpuzZS) and/or the [LuckPerms support Discord](https://discord.gg/luckperms) if you are having any trouble setting things up (use whichever is most appropriate).

**Comment by slayerOO7** [comment]
I tested it out with LuckPerms and it's now working, seems like Group Manager was out of date and dysfunctional. Once again, thanks a lot!
