### ISSUE TITLE
Advanced AFK Detection

### ISSUE THREAD

**Issue by kakduman** [EssentialsX/Essentials#3371]
### Feature request

**Feature description**

An advanced AFK detection option in the config.yml which would be able to find out if players are AFK fishing and/or in an AFK pool and mark them AFK if they are.

**How the feature is useful**

Players can learn that another person is not responding to their chat messages because they're AFK. It might also be able to be used in conjunction with the /god mode while /afk feature so that people who afk fishing or are in an afk pool are protected from damage.

Server owners can reduce lag by kicking all AFK players rather than just those who are in /afk mode if they choose to. They can also remove unenforceable rules like "no AFK pools" and make it more difficult for players to avoid an AFK kick if one is set up.

Developers can incorporate this feature into their plugins. Plugins like GriefPrevention that reward players for playtime but exclude AFK players could also exclude players who are AFK fishing or in an AFK pool. Other plugins that ask the server to vote on something and default to a "no" vote from players who are not AFK (like skipping the night, for example) could disregard players who are AFK fishing or in an AFK pool from the vote. The end result is that many plugins that work closer to their intended purpose.

**Comment by pop4959** [comment]
This is not something that is reasonable to add to Essentials' AFK system. The way that it works is that players can either type `/afk` or get marked automatically as AFK after some amount of time. When a player interacts or moves, their AFK status may be toggled back to not AFK (when `cancel-afk-on-interact` and `cancel-afk-on-move` are used).

The scenarios that you are describing involve the player interacting (throwing a fish hook), or moving (in a pool), in which Essentials will "correctly" set the player as not AFK, despite you knowing better. Call it an exploit if you will, as this is not how the system is intended to work and players can abuse it. Having a server rule about this is reasonable.

If you want an "advanced" AFK system, you might want to find another plugin that handles AFK instead of Essentials, as they'll be more likely to keep on top of exploits people try to use to avoid being marked as AFK.

**Comment by kakduman** [comment]
Alright, thanks for the explanation!
