### ISSUE TITLE
disable esentials eco

### ISSUE THREAD

**Issue by Stoniasawsome** [EssentialsX/Essentials#3397]
### Feature request

**Feature description**

disable economy completely

**How the feature is useful**

it would make it possible to use other economy plugins

i need to be able to tottaly disable essentials eco from taking payments from other plugins. i removed all perms for essentials eco in my groups. i am trying to run a different eco plaugin called peconomy, but when players use the jobs plugin or bank plugins or many other plugins that deal with payments to the player from the plugin it pays them to their essentials balance not their peconomy bal. we need a way to remove essentials eco from the equation, because quite frankly essentials eco is kinda basic and drab.

**Comment by triagonal** [comment]
Essentials will automatically disable its own economy and defer to a Vault-compatible alternative economy if one is detected on the server. 

Use an economy plugin that is Vault-compatible if you wish to move away from Essentials' economy.

**Comment by CyberDudeJ** [comment]
What if i just don't want an economy?

**Comment by mbax** [comment]
If you don't want an economy, don't use the feature! Ensure users don't have permission nodes for the commands and don't use economy-based features of other plugins if you must install Vault for non-economy reasons. For further support, perhaps consider asking in the support discord instead of necroposting on an ancient issue.
