### ISSUE TITLE
EssentialsX v2.17.2.159 is generating region files

### ISSUE THREAD

**Issue by Capri205** [EssentialsX/Essentials#3493]
Hi. Version v2.17.2.159 of EssentialsX is generating region files when the spigot 1.16.1 server starts up. I have a small lobby server which has only a few region files:

r.0.0.mca  r.0.-1.mca  r.0.1.mca  r.-1.0.mca  r.1.0.mca  r.-1.-1.mca  r.-1.1.mca  r.1.-1.mca  r.1.1.mca

However when I put in EssentialsX the startup takes considerably longer and the following additional region files have been created:

r.0.0.mca    r.1.-1.mca           r.-26407.-47646.mca  r.49796.38364.mca   r.50892.-40186.mca
r.0.-1.mca   r.1.1.mca            r.3023.-23464.mca    r.-50248.36486.mca  r.50892.-40187.mca
r.0.1.mca    r.-12036.18890.mca   r.3023.-23465.mca    r.-50249.36486.mca  r.-52996.-36475.mca
r.-1.0.mca   r.-12036.18891.mca   r.-39669.-52890.mca  r.-50784.34473.mca  r.-52996.-36476.mca
r.1.0.mca    r.-26406.-47645.mca  r.4586.21361.mca     r.-50784.34474.mca
r.-1.-1.mca  r.-26406.-47646.mca  r.4587.21361.mca     r.-50785.34473.mca
r.-1.1.mca   r.-26407.-47645.mca  r.49795.38364.mca    r.-50785.34474.mca

Some of these are referring to chunks 12 million blocks out!

These extra region files/chunks adversely affect other plugins also.

Appreciate any thoughts on what you think is going on here.

Cheers.

**Comment by pop4959** [comment]
This was caused by the new `/tprandom` command which by default pre-caches several chunks on server startup to make the command a bit faster -- in hindsight, this was not a good default.

Download the latest build of essentials from <https://essentialsx.net/downloads.html> which updates the default for `pre-cache` in tpr.yml to `false` rather than `true`.

If you wish to turn it back on, you can do so by re-adding the config option to tpr.yml.

The caching stage only pulls from chunks that are inside your world border by default, if you have not made it smaller, or have not run `/settpr maxrange <value>` to reduce the range of the command. Most likely you are not making use of the vanilla world border, or you have not made it smaller, which explains why it generated chunks so far from your lobby's spawn point.
