### ISSUE TITLE
[REQUEST] about system balance

### ISSUE THREAD

**Issue by LowScarlet** [EssentialsX/Essentials#3570]
### Feature request

**Feature description**
I make limit for Max Balance to 20m
and I test
I have 2m Balance in account and if I use command /eco give Scarlet 20 000 000 , error is **this transaction would exceed the balance limit for this account** and the balance is not added

the request is, keep adding balance but set to max balance

**How the feature is useful**
This will make the balance not forfeited

**Comment by pop4959** [comment]
It wouldn't make sense for the command to be changed in the way you're describing, because now a *different* amount of money than was requested will be given to the player, which is going to be a whole lot more confusing than simply denying the transaction.

There are two ways you can accomplish what you're trying to do.
1) Give them an amount equal to the difference (between their bal and the amount you want them to have).
2) Simply use the set sub-command instead of give.
