### ISSUE TITLE
Display actual ping in `/ping` command

### ISSUE THREAD

**Issue by Octol1ttle** [EssentialsX/Essentials#3581]
### Feature request

**Feature description**
 I suggest that `/ping` command will also show the actual ping of a player, like "Pong! 150ms"

**How the feature is useful**
 It's useful because adding/writing another plugin for 1 command is quite useless, and knowing your ping without leaving the server is essential.

**Comment by montlikadani** [comment]
I'm already made a [PR](https://github.com/EssentialsX/Essentials/pull/1992) 2 years ago, but @md678685  says ([comment](https://github.com/EssentialsX/Essentials/pull/1992#pullrequestreview-117072649)):
> /ping has existed for years as it is. I don't see why we should change this when other plugins can already override and replace this command.

I would rather remove this command from Essentials. I know some plugin developers (like PlaceholderAPI, Essentials) have some joke commands or anything that doesn't make sense because it won't break anything if we remove it. These things only take up space and are only invented so that the user can do something with it, such as format. I do not see the point.

Otherwise, if this issue happens, you will need to install at least fewer plugins on your server.

**Comment by pop4959** [comment]
See the comments that montlikadani linked to for why this won't be added.

In addition I would like to add that ping (although not exact) is displayed in the [tab] / player list. This is usually good enough to see if it's good or bad (which is all you really need to care about) so there isn't a real need to duplicate this in Essentials anyways.
