### ISSUE TITLE
Auto Enable fly on login without having to be in the air on logout (safelogin)

### ISSUE THREAD

**Issue by AetherisMC-Squid** [EssentialsX/Essentials#3661]
### Feature request

**Feature description**
I am requesting that players with a permissions node like "essentials.fly.enableonlogin" or even just the existing "essentials.fly.safelogin" have their fly enabled for them on login regardless of if they are in the air when they log out.

**How the feature is useful**
It's a simple feature, but saves a little time and I would hope it's easy to implement. If you log out while standing on the ground, even if your fly mode is enabled, you'll have your fly disabled and have to use /fly to re-enable it every time you log in. For those of us who relog/swap servers often, it fixes a minor annoyance.

**Comment by pop4959** [comment]
I don't think this is a necessary addition, since players can easily type `/fly` to re-enable their fly if they choose to. Most players who are on the ground when they are logged in most likely want to be, and they are at no risk.

If you want, you can also add an alias in `commands.yml` to make the command even shorter. Another option is to make a custom plugin that automatically sets your status to flying when you log in.
