### ISSUE TITLE
Make teleportation functionality configurable

### ISSUE THREAD

**Issue by michielswaanen** [EssentialsX/Essentials#3729]
### Feature request

**Feature description**
Currently, EssentialX's teleport functionality is a bit broken. If you teleport inside a block it will teleport you to the closest air block. No problem would you think? Well..

If player Y teleports to player X (using `/tpa`) who's standing in a **door** (any type), **glass pane** (any type) or **iron bar**, it will assume that player X is inside **a solid block** and thereby teleport player Y to the closest air block.

This gives you the ability to easily break into faction bases or houses. (look at the video below).
You can reproduce this by teleport (without OP) to a player that is standing inside a door, glass pane, ...

Video (15 seconds demo): https://youtu.be/Bjwk5oXqlA4

**Feature request**: Make it an option in the config file to disable the 'safe teleport' mode.

**How the feature is useful**
A ton of players are currently abusing the 'safe teleport' mode to get inside faction bases or restricted areas in spawn.
The extra option inside the config would help server owners to choose the teleport behavior themselves.

**Comment by michielswaanen** [comment]
If you've any additional thoughts or questions please let me know.

**Comment by pop4959** [comment]
You can already disable safe teleport. Search for and disable the relevant config options. Safe teleportation does not make any attempt to check if someone is "breaking in", or anything. If it's a safe location, it is a valid place to teleport to. You can use another plugin to section off areas that you don't want players entering, so that you aren't relying on safe teleport needing to be correct for that use case.
