### ISSUE TITLE
Tab-completing /powertool causes spam in console

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#3738]
Hello.

**Steps to reproduce**  
Type "/powertool" in game chat. Press [Space] then [Tab]. Repeat last step as much as you can. See the useless trash in server console /:

**Screenshots**  
![image](https://user-images.githubusercontent.com/19989717/96870442-95196580-1479-11eb-993f-79de40c0df88.png)

**Comment by JRoy** [comment]
What other plugins do you have, this isn't Essentials doing this.

**Comment by molor** [comment]
> What other plugins do you have, this isn't Essentials doing this.

You isn't tied this?.. Or maybe it's Paper?
![image](https://user-images.githubusercontent.com/19989717/96871327-cb0b1980-147a-11eb-9ff3-57e09dbe3ba7.png)

**Comment by triagonal** [comment]
Confirmed on the following setup:
```
>.... [08:31:35 INFO]: Server version: 1.16.3-R0.1-SNAPSHOT git-Paper-195 (MC: 1.16.3)
>.... [08:31:35 INFO]: EssentialsX version: 2.18.1.28
>.... [08:31:35 INFO]: LuckPerms version: 5.1.107
>.... [08:31:35 INFO]: Vault version: 1.7.3-b131
```
Issue occurs when first argument to powertool includes an `a:`

![image](https://user-images.githubusercontent.com/10545540/96872109-e8fa6d80-14be-11eb-80f9-a5a23008f207.png)

**Comment by benwoo1110** [comment]
Looks like its caused by this area: https://github.com/EssentialsX/Essentials/blob/9cda59511e2742233123cad3be1ae1f6df04ba09/Essentials/src/com/earth2me/essentials/commands/Commandpowertool.java#L157

Then the tabCompleteCommand has a logging for some reason.
https://github.com/EssentialsX/Essentials/blob/9cda59511e2742233123cad3be1ae1f6df04ba09/Essentials/src/com/earth2me/essentials/commands/EssentialsCommand.java#L357

**Comment by Chew** [comment]
Just a debug message left in
