### ISSUE TITLE
Doesn't respawn after death at single home point

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#3788]
### Information

**Full output of `/ess version`:**

```

```

### Details

**Description:**  

EssentialsXSpawn after death spawns me at my bed location, but I have only one home point (set by /sethome) and I must

**Comment by ghost** [comment]
Server version: 1.16.4-R0.1-SNAPSHOT (MC: 1.16.4)
EssentialsX version: 2.18.2.1
EssentialsXSpawn version: 2.18.2.1

**Comment by Chew** [comment]
Please show your config.yml

**Comment by triagonal** [comment]
Closing due to author inactivity. If you would like us to look into this issue, please comment with the full output of `/ess version`, your config file (`plugins/Essentials/config.yml`), and your startup log (`logs/latest.log`). You can use [Gist](https://gist.github.com/) to supply the requested files.
