### ISSUE TITLE
Version inconsistency

### ISSUE THREAD

**Issue by SlimeDog** [EssentialsX/Essentials#3794]
### Information

EssentialsX-2.19.0-dev+5-35278c6.jar 

plugin.yml
```
version: 2.19.0-dev+2-9a23f80
```

Does that matter?

**Comment by Chew** [comment]
Finally, **the EssentialsX version string format is changing**. Future releases will use the format `<major>.<minor>.<patch>-<commit>` (eg `2.19.0-a6edf04`), while dev builds will use the format `<major>.<minor>.<patch>-dev+<depth>-<commit>` (eg `2.19.0-dev+2-5cd6a21`).

**Comment by JRoy** [comment]
seems like they're talking about the version string differing from file name the plugin.yml

@mdcfe

**Comment by SlimeDog** [comment]
I thought it was clear, but yes: JAR filename and plugin.yml:version are inconsistent.

**Comment by Chew** [comment]
Oh hmm, oopsie

**Comment by SlimeDog** [comment]
What was wrong with the MAJOR.MINOR.PATCH-BUILD versioning, using almost universally by Spigot plugins?

**Comment by mdcfe** [comment]
The inconsistency is caused by Gradle caching the `plugin.yml`, which rarely changes on disk.

> What was wrong with the MAJOR.MINOR.PATCH-BUILD versioning, using almost universally by Spigot plugins?

The new version strings give users more information about what version they're using by including the commit hash and whether or not the build is a dev build. This is reminiscent of the versioning scheme employed for years by projects such as [WorldEdit](https://builds.enginehub.org/job/worldedit). Otherwise, it provides the same information as before - major/minor/patch numbers and commits since the previous release.

**Comment by SlimeDog** [comment]
Thanks. Essentials is (now) one of two plugins, out of 160+ we test, that uses this versioning.

I've updated my automagical update checker. Feel free to close at your leisure.

**Comment by JRoy** [comment]
Thanks for your input
