### ISSUE TITLE
/skull with custom skin

### ISSUE THREAD

**Issue by marcbal** [EssentialsX/Essentials#3804]
### Feature request

**Feature description:**  
Ability to provide a custom skin when using /skull.
When you want a skull with a custom skin (for instance [here](https://minecraft-heads.com/custom-heads/decoration/33561-presents)), you have to be op to execute the provided commands, since these commands are too long to be typed in chat. Since the provided give command is full of stuff that are common for all skull, it would be great to have a shorter way to do it like `/skull 6f5c433908732b512f68461c14ef020bb2f55d96a61cd1d45ea1e7ea899f1a6b` (would give the skull at the link provided above)

*Possible inputs*:
* The argument value I suggested above represent the end part of the skin URL (64 char long), hosted on textures.minecraft.net. This is the only thing that vary between custom skulls.
* Another argument value what would be possible is the base64 (180 char long) value that contains the URL in some JSON stuff. Some skull repository may not provide the base URL, but only the base64, thus the suggestion to also accept it.

**How the feature is useful:** 
It would be useful for players/owners/map makers to have an easy way to add custom skulls in their decoration (or whatever reason) in an easier way the full `/give` commands. This would reduce the need to ask operators for the give of the skull, like the current `/skull <player>` command already does for player skulls.
The improved `/skull` command can be a light and fast solution compared to the plugin advertised on Minecraft Heads website.

**Comment by JRoy** [comment]
IMO would be very niche and not used by many players to justify its creation.

Also would be Paper only as we'd need to use their PlayerProfile API

**Comment by Luu7** [comment]
I think this suggestion is good, not only for builders and server owners, but also for player interaction. For example, to make custom crafting more easy, you dont need tu put an extra plugin just for the heads, you have essentials "/head xxx" command, that allows you to have any head you want for whatever you want. Or for treasure hunts. Or because you don't have the money to buy the plugin that is suggested on minecraft-heads.com. Maybe it's something that not everyone would use, but I think many find it useful.
