### ISSUE TITLE
Add toggleable effects, i.e. /nv for night vision, /fr for fire resistance, etc.

### ISSUE THREAD

**Issue by amongus9000** [EssentialsX/Essentials#3825]
### Feature request

**Feature description:**  

I suggest adding commands that will toggle effects on/off, for example /nv for night vision, /fr for fire resistance, etc.

**How the feature is useful:**  

Like the recent addition of /cartographytable, /loom, and similar commands, this will let Essentials replace other plugins. On Spigot, there is no plugin that does this feature aside from a couple old ones from 2016.

**Comment by imDaniX** [comment]
I think it should be implemented by replicating the vanilla `/effect` command, and then user should specify their own aliases through commands.yml - it should not be "hardcoded" into plugin.yml, just because there's might be questionable overrides of other commands.

**Comment by bcheidemann** [comment]
> I think it should be implemented by replicating the vanilla `/effect` command, and then user should specify their own aliases through commands.yml - it should not be "hardcoded" into plugin.yml, just because there's might be questionable overrides of other commands.

Do you think the alias should work the exact same as the vanilla command?

**Comment by imDaniX** [comment]
> Do you think the alias should work the exact same as the vanilla command?

Well, not exactly. `/eeffect <effect> <time> [player] [hide]` with permissions `effect` for the command itself, `effect.(effecttype)` for specific effects, `effect.(effecttype).other` for adding effects to other players. Specify -1 for <time> to make it last Integer.MAX_VALUE.

**Comment by pop4959** [comment]
I'm in agreement with what @imDaniX mentioned above. There's no reason why this should be implemented in Essentials when the vanilla command also does what you want, and you can alias each effect in however way you want via commands.yml.

There's not really a strong reason for adding this into Essentials as it's been suggested here.

BTW: The workbench-type commands were added because we already have `/craft` and `/enderchest`. Commands in Essentials are never designed specifically to replace any other plugin, and if it happens it is purely coincidental.
