### ISSUE TITLE
No damage on Trident with Riptide in /pweather

### ISSUE THREAD

**Issue by ArnoPompio** [EssentialsX/Essentials#3876]
### Information

Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-345 (MC: 1.16.4)
EssentialsX version: 2.18.2.0
PlaceholderAPI version: 2.10.9
LuckPerms version: 5.2.54
Vault version: 1.7.3-b131
Citizens version: 2.0.27-SNAPSHOT (build 2197)
ChestShop version: 3.11 (build 213)
EssentialsXChat version: 2.18.2.0
EssentialsXSpawn version: 2.18.2.0

**EssentialsX config:**

https://gist.github.com/ArnoPompio/3859614c46588d59d098d95962c44c95

### Details

**Description:**  
When a player is using Riptide* on a Trident in /pweather (rain/thunder), he gets infinite fly because the trident does not break. 

_*Tridents enchanted with Riptide can be thrown only when a player stands in water, during snowy weather in certain biomes, or during rainy weather_

**Steps to reproduce:**  
Using a Trident with Riptide in /pweather (rain/thunder)

**Expected behavior:**  
The Trident must take damages from each use.

**Comment by JRoy** [comment]
Isn't really an Essential bug, should ideally be handled by stream (Paper/Spigot) if it can. Although I think there may be no way to control this as I believe it's client side.

**Comment by pop4959** [comment]
JRoy is correct. What pweather actually does is it makes the client think that the weather is different than it actually is on the server, which obviously can lead to some hacky behavior. Tridents are a good example since the client thinks it's raining, but on the server it isn't actually raining so it doesn't consider the player having used it.

It might be able to be fixed, but not in Essentials. Try submitting a bug report to Spigot and see what they say.
