### ISSUE TITLE
preventmodify bypass

### ISSUE THREAD

**Issue by cicatrice74** [EssentialsX/Essentials#3924]
I have a single server with a survival and a creative world, i need mods to not be able to modify inventories of a user in creative world so i added essentials.invsee.preventomodify to that group in that world but i also need to add a bypass for owners like me to be able to do that.

something like essentials.invsee.preventmodify.bypass

so mods cannot do that but owners can

tnx

**Comment by benwoo1110** [comment]
Cant you just set `essentials.invsee.preventmodify` to false with your permission plugin?

**Comment by pop4959** [comment]
I don't think we are going to add something like this to Essentials, since it's too highly specific. Preventmodify permission is not really intended for what you're trying to use it for, and it sounds like the real problem here is a lack of proper separation between your worlds on the server, which is going to cause a variety of other issues as well. Fix that and all of your other problems should go away.
