### ISSUE TITLE
Notify Player Of Mail Not Working

### ISSUE THREAD

**Issue by TailedPoog420** [EssentialsX/Essentials#4260]
### Type of bug

Other unexpected behaviour

### `/ess version` output

Latest version of 1.16.5 Spigot. Latest stable version of EssentialsX, EssentialsXChat, LuckPerms.

### Server startup log

No errors for anything.

### EssentialsX config files

Default configuration for all plugins (except giving permissions for relevant EssentialsX mail and mail-send).

### Bug description

When ` notify-player-of-mail-cooldown ` in config.yml is set to 60, players are not notified of unread mail every minute, even if they have ` essentials.mail ` and ` essentials.mail.send ` permissions.

### Steps to reproduce

Give players mail/mail-send permissions. Send mail to all players via console ` mail sendall message `. Wait for configured ` notify-player-of-mail-cooldown ` time to elapse.

### Expected behaviour

If ` notify-player-of-mail-cooldown ` is set to 60, players should receive the typical "you have unread mail" message in chat every 60 seconds until they clear their mail.

### Actual behaviour

They get the unread mail notification upon their next login, then after that they receive no updates about their unread mail even upon reconnect unless new mail is received.

**Comment by triagonal** [comment]
The config option isn't a "timer" for having the unread mail notification sent repeatedly, it's a cooldown so that the message doesn't get sent to the player every single time they trigger it.

Triggers for the mail message are:
- Player joins the server
- Player runs any Essentials command (as long as they have `essentials.mail` and the command is not `/mail`)

I was able to get the cooldown to work as intended on the following, the message appeared whenever I logged in or ran an Essentials command after the cooldown had elapsed.
```
[05:25:29 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-777 (MC: 1.16.5)
[05:25:29 INFO]: Brand version: Paper
[05:25:29 INFO]: EssentialsX version: 2.19.0-dev+167-9bd35a2
[05:25:29 INFO]: LuckPerms version: 5.3.48
[05:25:29 INFO]: Vault version: 1.7.3-b131
```
