### ISSUE TITLE
Bug in nick

### ISSUE THREAD

**Issue by thiagogebrimm** [EssentialsX/Essentials#4269]
### Type of bug

Exploit

### `/ess version` output

2.19.0-dev+167-9bd35a2

### Server startup log

It is not necessary

### EssentialsX config files

It is not necessary

### Bug description

When changing the nick without having the op, the nick changes but the original nick appears in the chat

![image](https://user-images.githubusercontent.com/75040244/123220852-b74e0200-d4a4-11eb-847b-9e0eace1b655.png)

### Steps to reproduce

1- Use /nick
2- I put anything other than my nick
3- Only my old nick appears

### Expected behaviour

Appear my new nick

### Actual behaviour

Does not appear nick

**Comment by triagonal** [comment]
Do you have `change-displayname` set to `false` in your config? Essentials needs that to be `true` in order to update your displayname with the nickname. Please fill out the **entire issue form** next time, as if you had provided your config file in the first place, I wouldn't have to be asking right now.

If that didn't work, there's likely another plugin handling your displaynames and/or preventing Essentials from applying the nickname. Try again with only EssentialsX, Vault, and your permissions plugin installed.

**Comment by thiagogebrimm** [comment]
The change-displayname is true

I'll try, thank you

**Comment by thiagogebrimm** [comment]
I removed all plugins and tested and the error remains, and it's only for people without OP

**Comment by JRoy** [comment]
Please fill out all the fields in the issue template completely and your issue will be looked at

**Comment by pop4959** [comment]
Unlikely to be caused by Essentials, but we won't know unless you provide everything required in the issue template. Please include everything and request this issue to be re-opened or create a new issue if you are still experiencing this and believe it to be a bug.
