### ISSUE TITLE
Spamming errors in console

### ISSUE THREAD

**Issue by AidanTheBandit** [EssentialsX/Essentials#4547]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=8be245fdd7554cfcbe7f1bbed76dffb2

### Error log (if applicable)

https://paste.gg/p/anonymous/9497fc0aba8947aa94a50bde96627e99

### Bug description

The plugin spams stuff about player UUIDs on startup

### Steps to reproduce

1. Start server

### Expected behaviour

I dont think this is supposed to happen

### Actual behaviour

The plugin spams errors

**Comment by pop4959** [comment]
It looks like you switched your server from offline mode to online mode, which causes players' UUIDs to change even if they have the same username as they did before. This isn't an error, it is just warning you so that you can fix it as most commonly this is caused by incorrect server/proxy configuration.

**Comment by AidanTheBandit** [comment]
Ok. How do I fix this?
