### ISSUE TITLE
Make /invopen include armor

### ISSUE THREAD

**Issue by justwheel** [EssentialsX/Essentials#472]
The `/invopen` command opens a player's inventory. It contains the three lines of their inventory and the one line of their hotbar. It doesn't include their armor slots. This would be a useful addition to the plugin!

**Comment by drtshock** [comment]
You need essentials.invsee.equip. Though I think we should have it where you don't need to do /invsee all.

**Comment by drtshock** [comment]
There

**Comment by justwheel** [comment]
@drtshock++

Thanks for the ridiculously fast hotfix!

**Comment by drtshock** [comment]
Actually, that broke things. So no :c

**Comment by khobbits** [comment]
Just to clarify here:
Normal invsee, is a direct 'editing' of the players inventory, meaning you can add/edit/remove items from their inventory.
If you type: "/invsee [player] a", it creates a fake inventory 'copy' of the players armour slots.  

Adding/removing from this inventory will not effect the target players inventory, it's simply for display purposes, checking to see if a player is lying for example. This is considered an #easteregg, and not documented as it was deemed to be confusing.

There was an intention on trying to fix this, but bukkit was lacking the necessary api methods to do so.

Edit, should probably reopen this issue ;)

**Comment by drtshock** [comment]
Yes, I was just lacking the commitment to properly add that functionality.

**Comment by BluPenDragon** [comment]
yes this is a MUST for anyone running a server... PLEASE fix it

**Comment by drtshock** [comment]
See KHobbit's comment. https://github.com/EssentialsX/Essentials/issues/472#issuecomment-196002401

**Comment by aeonlamb** [comment]
why is /invsee <name> a totally undocumented?? there's so many times this would have been useful for my staff to know about...

Also, I'd like to see the offhand slot shown in /invsee as well. Why not make a chest with 6 rows, with the very bottom row showing an unmodifiable armor slots as well as offhand? Most of the time staff don't need to remove or mess with the items, just see what's in someone's inventory.

**Comment by khobbits** [comment]
@aeonlamb The main reason is due to how it's implemented.

With normal /invsee, the staff member get's to see a live window into the players inventory, it's literally a live connection between your client and the players inventory, so if they add/remove items you should also see that happen live.  No chance of duping items, or breaking anything, items only exist once.

With "/invsee a", we take a copy of the user's equipped inventory, duplicating the items the player is carrying and then create a fake chest, place the items inside, and hope the player doesn't use/abuse any chest duping techniques, or abuse features in other plugins that would allow players to remove items from the 'chest'.

This second approach is far more risky on any server that is economy related, or where admins create items with overspec'd items.  The intention was always to go back and see if it could be improved, but the Bukkit API was the main limit.  I figured it was best to make it available for people who really wanted it, and we could explain the risks too, but not just make it immediately available to everyone and risk people blaming us for destroying their server.

**Comment by aeonlamb** [comment]
Thanks for the informative answer... I feel like if you make it clear that the permission for seeing armor (and offhand?) could be dangerous then server owners will be more cautious about who they give the permission to. 

Is it not possible to have the live chest inventory shown at the same time as 4 or 5 unmodifiable, non-live item slots for the armor? And have a separate permission which handles showing these additional slots?

**Comment by JRoy** [comment]
This feature would require too much on part of Essentials syncing inventories and with all the Inventory fuckery that happened recently, it really doesn't make sense for Essentials to maintain this. We suggest using a plugin dedicated to this like [OpenInv](https://dev.bukkit.org/projects/openinv).
