### ISSUE TITLE
custom-new-username-message not working

### ISSUE THREAD

**Issue by quillincn** [EssentialsX/Essentials#4742]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=231c2345fb4d4734b39cad0730456f4f

### Bug description

Regardless from config file, "custom-new-username-message" nothing change. I put there "custom-new-username-message: "{PLAYER} is here!"", but message for new player still says "Welcome quillin to the server". Even i try put there "none", it`s dint change anything.

I restarted server every time after change settings, to be sure.

### Steps to reproduce

1. Stop server.
1. Change "custom-new-username-message" to any message.
2. Remove "playerdata" folder from world.
3. Start server and join there.

### Expected behaviour

After you change "custom-new-username-message", new player join should show message which you set in config file.

### Actual behaviour

Instead custom message, which i set, Ess show default message.

![изображение](https://user-images.githubusercontent.com/18488764/148628905-7d8f2881-6afa-46ad-8768-d193b9f9f8a6.png)

**Comment by quillincn** [comment]
Same happens at 2.19.2, stable version.

**Comment by Chew** [comment]
Intentional behavior per https://github.com/EssentialsX/Essentials/pull/4290

The config option is referring to _old_ players with _new_ usernames. The user must have joined before. As this is a first join, there is no "prior" username.

In your 2nd screenshot, the "Welcome x to the server" is actually [`announce-format`](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/config.yml#L1129) from EssentialsXSpawn.

**Comment by quillincn** [comment]
My bad! Thanks you very much!
