### ISSUE TITLE
Auto AFK does not set AFK Player List option

### ISSUE THREAD

**Issue by Puremin0rez** [EssentialsX/Essentials#481]
The option "afk-list-name" only works when a user does /afk to set themselves as AFK, but does not occur whenever essentials automatically sets somebody as AFK.

This might be intended behavior but I personally think it's a bug.

**Comment by SupaHam** [comment]
Hi, sorry for the very late reply. I have just tested this bug on the latest and it seems invalid. EssentialsX will automatically update the player's list name when the player goes AFK over time. This might have been fixed along the way.

This issue might be caused by another plugin you are using which is overriding the EssentialsX feature. This feature was not designed to override other plugins, just a simple implementation that assumes no other plugins modify the player list name.
