### ISSUE TITLE
/condense <any argument> ignores item amounts in recipes.

### ISSUE THREAD

**Issue by KermX** [EssentialsX/Essentials#4810]
### Type of bug

Exploit, Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=959a18f0b3d34275be3c2cb4a3db0c0c

### Bug description

I believe this only applies to custom crafting recipes as there are no vanilla recipes that use multiple items per slot. 
Ex. 
custom crafting recipe: 9 stacks of 64 stone results in 1 item
bug causes 9 stacks of 64 stone to result in 64 items when using /condense <any arguement>

### Steps to reproduce

1. Create crafting recipe with some custom crafting plugin (I use ecoitems) that requires 9 stacks of any item to result in 1 item
2. Use /condense <any argument>

### Expected behaviour

/condense <any argument> should either result in no item like /condense does, or it should respect the crafting recipe.

### Actual behaviour

/condense <any argument> results in item amounts in the crafting recipe not being respected and outputs an incorrect number of the result item.

**Comment by pop4959** [comment]
Recipes normally have one item in them. It looks like the plugin you're using probably does some weird magic to get that to work the way it does. You'll probably want to either adjust your recipe, or report it as an issue to the author of that plugin as unless this is something we can reproduce it is unlikely to be fixed by Essentials.
