### ISSUE TITLE
AFKing on soul sand and water won't count as AFK

### ISSUE THREAD

**Issue by WaffleBits** [EssentialsX/Essentials#4934]
### Type of bug

Exploit, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=7dce233129634db4b7ac15cc673b8d26

### Bug description

when standing on soul sand and water you will not be AFK

### Steps to reproduce

1. place soul sand
2. place water on top of the soul sand
3. stand in the water

### Expected behaviour

you should be afk after some time

### Actual behaviour

you are never afk

**Comment by osfanbuff63** [comment]
Are you sure that they have the `essentials.afk.auto` permission? If so, I'll see if I can reproduce it, based on a quick look at the dump.

**Comment by WaffleBits** [comment]
> Are you sure that they have the `essentials.afk.auto` permission?

yes it is in the default group

**Comment by osfanbuff63** [comment]
I can reproduce this on 2.19.5-dev+8-3af9317 ([`/ess dump all`](https://essentialsx.net/dump.html?id=53c77e48a98c4a9e93875cf3ee154260)), but I believe this is because in > 1.12 versions water + soul sand makes a bubble column, and so you are continuously moving up and down in it, causing EssX to not detect you are AFK, for a legitimate reason (being that you are moving). For this reason, I don't think this report is valid - but if a member of the EssentialsX team wants to pick this up, feel free.

**Comment by pop4959** [comment]
Yes this is effectively just a simple AFK machine, which is currently not a goal of Essentials anti-AFK system to detect.

It's still a problem obviously, but you will probably either want to find a more sophisticated anti-AFK plugin or simply tell your players not to create AFK machines.
