### ISSUE TITLE
Runing baltop in command block cause error

### ISSUE THREAD

**Issue by Josh65-2201** [EssentialsX/Essentials#5004]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6346379fe850473b9145136ca692dce5

### Error log (if applicable)

https://gist.github.com/Josh-65/33759a9430426f698c71c256b20a6f3f

### Bug description

I have a command block runing /baltop evey 30 seconds and for every few ran the error in uploaded gist will show. 

### Steps to reproduce

Place command block with /baltop in it
Run it every 30 seconds or so with Redstone
See error in console after a few runs of the command

### Expected behaviour

Should not have the error in console

### Actual behaviour

Has error in console. I carnt tell if the command runs for when the error appears

**Comment by pop4959** [comment]
It looks like this would be fixed by moving this logic back onto the main server thread:
https://github.com/EssentialsX/Essentials/blob/09dc49aacb702408f00ec8418b6b6c0527436924/Essentials/src/main/java/com/earth2me/essentials/commands/Commandbalancetop.java#L115

Also, does this ever happen if you don't use a command block? For example, using a plugin to schedule the command execution instead. It seems unusual that this wouldn't already be an issue otherwise.

**Comment by Josh65-2201** [comment]
When runing the command myself no. i carnt test if running it from a plugin would cause it.
