### ISSUE TITLE
essentials.silentquit does not work

### ISSUE THREAD

**Issue by Turbotailz** [EssentialsX/Essentials#515]
Giving the permission `essentials.silentquit` to people does not work as expected. It doesn't work at all. Anyone with this permission node will still be announced when they leave the server.

Ops can join and leave just fine without being being announced.

`essentials.silentjoin` works perfectly fine also.

This is the permission that's listed on the [Essentials permissions reference](http://ess.khhq.net/wiki/Command_Reference/Perm), perhaps it's something else? Or maybe it's just bugged. Either way, would be great to have this fixed.

**Comment by drtshock** [comment]
Can you paste your startup log in pastebin please

**Comment by Turbotailz** [comment]
Sorry it is a bit lengthy:
http://pastebin.com/Gi0mtTR0

**Comment by khobbits** [comment]
Bit old, but there is a config option to go with this:

```
# Should players with permissions be able to join and part silently?
# You can control this with essentials.silentjoin and essentials.silentquit permissions if it is enabled.
# In addition, people with essentials.silentjoin.vanish will be vanished on join.
allow-silent-join-quit: false
```

**Comment by Turbotailz** [comment]
> Bit old, but there is a config option to go with this

Yep, I'm aware of this, I have that option set to **true**. Anyone with **essentials.silentjoin** will join the server silently, but anyone with **essentials.silentquit** will still be announced when they leave.

**Comment by drtshock** [comment]
Can you show the server logs with debug enabled in essentialsx when this happens?

**Comment by Turbotailz** [comment]
Here are the debug logs showing my alt account that has no other special permissions on my server.

http://pastebin.com/1DwB6ZX7

We have set up a global group in GroupManager called **g:staff_silentjoin** which has the following set of permissions: 

http://pastebin.com/uM3LD2Cj

As you can see, this account didn't have any of the permissions when it first joined, but then after I added the group **g:staff_silentjoin**, it checked **essentials.silentjoin** as **true** but **essentials.silentquit** remains **false** - even though it's definitely been added as a permission.

Funnily enough, I notice it also checks **essentials.vanish.effect** as **true** _before_ I log out, but **false** _after_ I log out.

**Comment by khobbits** [comment]
Hmm, within Bukkit, users only really have permissions when a player is online.
There's a good chance the essentials.silentquit perm check happens after the user disconnect event has fired, and the permissions object is nulled.

Assuming my memory isn't failing me this feature historically only worked with permissions systems which were manually supported by Essentials, such as GM and PEX because Essentials could talk directly to the plugins rather than going via Vault/Bukkit API.  I also seem to recall one of the EssX team rewriting the perms handlers, so it might be worth a look at that (by one of the dev team).

Assuming that's not the issue, it could be related to using offline mode, or bungee, something that may confuse groupmanager so it looks up the wrong uuid, once the player has left the server.

**Comment by mdcfe** [comment]
Closing as this doesn't appear to have been replicated using supported permissions plugins.

(As a side note, I believe EssentialsX prefers the Vault permissions handler over the older plugin-specific handlers if Vault is installed, which could the reason GM isn't able to check for permissions correctly once a user has logged off.)

EDIT: EssentialsX actually uses Vault where possible and no longer has non-Vault handlers for specific plugins.

**Comment by Adam4563** [comment]
Hi. How do I set up a message for the essentials silent joint/quit?
