### ISSUE TITLE
Change the severe warning of an outdated server from Error to Warning

### ISSUE THREAD

**Issue by Jcodeerd** [EssentialsX/Essentials#5325]
### Feature description

Change the severe warning of an outdated server from Error to Warning, since Essentials will work fine when using the latest stable on 1.19.4 (and later minecraft versions)

(the "[ERROR] [Essentials] You are running an unsupported server version!" message)

### How the feature is useful

Instead of inexperienced server owners thinking that its an error that might cause trouble on their server, just tell them it's a warning to warn them that some features might not work on their version of minecraft

**Comment by mdcfe** [comment]
It's our responsibility to test the software we release and inform people about the platform versions it is (and isn't) compatible with. If we can't guarantee basic functionality on a version of Minecraft/Spigot/Paper, we want to encourage users to look for an updated version of their server software and/or EssentialsX so they have a combination we've actually tested together. This is even more pertinent now as Mojang makes larger internal changes more frequently, unlike past versions where theyheld back significant changes to the game's internals until major releases of the game; as such it's far more likely for EssentialsX to break when updating from one seemingly "minor" version of the game to the next.

In the past, without loud and clear warnings, we ended up with dozens of users finding that their outdated copy of EssentialsX doesn't work properly on a new MC version, without them even knowing they should have looked for an update. This happens *a lot*, and it's the reason we decided to show an error for any unsupported versions, regardless of whether the MC version is older or newer than the versions we support. 

Our intention is to always release a new stable build to support the latest current version of Minecraft. If it turns out that an older release works properly on later MC versions (ie 2.19.7 working correctly on 1.19.4), then that's an added bonus, but it's not an expectation we (or any other server software developers) can rely on in 2023 with so many moving pieces, and we don't want to lull users into having that expectation either. 2.20 is planned to target 1.19.4 and is still in progress, but unfortunately it has taken much longer than expected. We intend to release 2.20 soon, and after this we hope to be able to push releases much more regularly to keep up with new MC releases.

Ultimately I don't think we want to change this message to an INFO level message as proposed in #5326 - this makes it indistinguishable from most other messages in the log, and it's far more likely for a server owner to not notice the message at INFO level.

**Comment by pop4959** [comment]
Agree with @mdcfe on all of the above. My only other comment here is while changing that message from log level ERROR to INFO is a non-starter, it could probably actually reasonably be a WARN. The linked PR does not do this though.

The main takeaway is that server owners are not meant to ignore an actual warning to a potential issue. Use log filters if you want to get rid of it / remove the colored message if you are so bothered. Or, simply update.

**Comment by Jcodeerd** [comment]
Yeah, fair points, I'll close this. Thanks for the feedback!
