### ISSUE TITLE
ESSX Discord Console output doesnt filter colors. even breaks /spigot:tps

### ISSUE THREAD

**Issue by CatbotTsumi** [EssentialsX/Essentials#5445]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=33ccd4b35e004bf69b7d013b15d4323b

### Bug description

Whenever there's a color code like `&6` anywhere in console output, it will display strange characters in discord console channel instead of just removing them. 

Example image showing the usage of `/execute tps`  working well (top)
but the execution of `tps` from the console breaks.
![Example image](https://images-ext-1.discordapp.net/external/v7TIPygU9U5x3hMeb_FoGVNoivNwob_RisxyG65mzVk/https/i.imgur.com/rn8ipcF.png)
In this example the `[33m` shouldn't be there. and the `.0 .0 .0` is supposed to display `20.0 20.0 20.0`

This issue is not exclusive to that command, it happens with all console output. 
![Example image featuring random chat](https://images-ext-1.discordapp.net/external/i3DE_cAO9J5P2Qwruue1q15lkr13kZRjcJ9ssL2zfkU/https/i.imgur.com/5qxvaJ2.png)
You can see that there's a lot of `[` + number + `m` and foreign characters inserted

### Steps to reproduce

Any colored text in the console will cause the issue.
See the relayed console in discord.

### Expected behaviour

Expected behavior is to have the console in discord not show any cmd color codes or whatever they are. 
Just no colors and no characters that shouldnt be there is what is expected.

### Actual behaviour

Unexpected characters are thrown into the discord console relay wherever a minecraft color is used.

**Comment by novalue** [comment]
The issue seems to come from this line
https://github.com/EssentialsX/Essentials/blob/2.x/EssentialsDiscord/src/main/java/net/essentialsx/discord/util/ConsoleInjector.java#L95

Replacing it with the following code seems to fix the output to discord:
String entry = FormatUtil.stripPaper(FormatUtil.stripFormat(FormatUtil.stripAnsi(FormatUtil.stripLogColorFormat(event.getMessage().getFormattedMessage())))).trim();

I'm not well versed with the internals of minecraft, and I cannot tell if this is the right fix to make, but everything should be stripped in the order of priorities.
