### ISSUE TITLE
Respawn command

### ISSUE THREAD

**Issue by Wojciechgc** [EssentialsX/Essentials#5501]
### Feature description

A simple command like `/respawn <player>` for respawning a dead player using `player.spigot().respawn()`.

### How the feature is useful

**Example use**: An admin accidentally causes an AFK player to die. They won't respawn on their own because they're AFK. The admin would be able to use `/respawn` on that player to respawn them, teleport them back and give them their items back.

**Comment by pop4959** [comment]
I don't really see the use case for this, aside from the contrived example you have. I find it hard to believe that most admins run into a situation like this often enough (nor care) to need this in Essentials, though it sounds like it would be an easy enough plugin to implement for yourself if you need this.

**Comment by Wojciechgc** [comment]
It is indeed easy to implement, I did it in less than 5 minutes. However, I think that this feature could probably be useful in some other cases than the example I mentioned (mainly because of the fact that if you want to do basically anything with a player they need to be alive). On top of that, because of the fact that it's such a small and easy-to-implement feature I don't think it makes sense to have another plugin just for it when (in my opinion) it would fit very well in EssentialsX next to basic commands like `/kill` and `/tp`.

**Comment by Wojciechgc** [comment]
> contrived example

FYI, I ran into this kind of situation yesterday :)

**Comment by pop4959** [comment]
The point is that it isn't common enough to consider an "essential" feature that should be included on all servers that Essentials is installed on. `/kill` and `/tp` are not good counterexamples since those commands actually get used.

If every plugin that could be written in 5 minutes was included in Essentials there would be thousands upon thousands of commands, but the reality of it is that most of these would not be used. It just creates additional maintenance burden for us which could easily be a separate plugin for the few people that use it.

I was also reminded that the game rule `doImmediateRespawn` exists. This should also solve the issue; otherwise, I would recommend using the plugin you wrote instead. I'll go ahead and close this issue for now but if we see a large increase in requests for this type of feature, we may change our mind about it.

If the purpose of this was simply to find something to contribute to Essentials, I recommend taking a look at all issues labeled with the status "open to PR". There are plenty of places where we welcome contributions.

**Comment by mdcfe** [comment]
Just to add my two cents here:

Taking on new features isn't purely a case of "how easy is it to implement", but also "can we verify this works on every version we support", "can we verify it will work in the future" etc. In this case we'd need to add a provider that exposes this method with a fallback (even if a no-op) for CraftBukkit.

This feels like an incredibly niche feature. Most of the use cases I can imagine for force respawning a player are in custom gamemode scenarios, where you'd already have custom plugins driving the logic which can call the aforementioned function directly.

We do appreciate suggestions for features like this as it is worth reviewing suggestions on a case by case basis, but in this case I agree with pop that it's not particularly useful or relevant to include in EssentialsX.
