### ISSUE TITLE
/unwax

### ISSUE THREAD

**Issue by BogTheMudWing** [EssentialsX/Essentials#5512]
### Feature description

`/unwax`
While looking at a sign (and/or copper blocks), run this command to un-wax the block if it is waxed.

### How the feature is useful

It is currently impossible to remove the waxing from a sign in vanilla Minecraft unless the data is changed via a command.

**Comment by pop4959** [comment]
I feel this is a bit niche to consider for its own command, at most _maybe_ it could make some sense as part of `/editsign`? That would kind of open up a can of worms if it were added since it would beg the question "if we have `/editwax` why do we not have `/edit<insert any other random block data feature in minecraft here>`."

Overall probably something that you would want to cook up in a separate plugin if this specific feature is extremely important to you for some reason. I think most servers just break the waxed sign and place a new one that isn't waxed.

**Comment by BogTheMudWing** [comment]
Understood.
Thank you for the clarification!
