### ISSUE TITLE
Money duplication

### ISSUE THREAD

**Issue by Flachgummi** [EssentialsX/Essentials#5550]
### Type of bug

Exploit

### `/ess dump all` output

Don't have it (I'm just a user of a server)

### Bug description

If you make Signs to sell items and someone buys it with a full inventory, the sign will receive the money and loose the item while the buyer won't pay and doesn't get the item. -> Item gets deleted but money gets duplicated. This bug can be used to exploit whole servers using EssentialsX as a trading system.

### Steps to reproduce

Place a sell sign.
Fill someone's inventory.
This person clicks on sell sign.

### Expected behaviour

Do nothing

### Actual behaviour

Delete item and dupe money

**Comment by tekikaito** [comment]
I am the admin of the server in question.

So here is the output of [`/ess dump all`](https://essentialsx.net/dump.html?id=f6c029bece3244c69a5e5d7e08dd3b78)

**Comment by Evidentsinger14** [comment]
I am unable to reproduce the behavior, but there is a small discrepancy in this. 
Sell signs allow players to sell items to the server, and Buy signs allow players to buy items from the server. When using a sell sign, the player is never going to be paying any money, they are going to be paid *for* their items. 

If you can reliably reproduce this using the latest versions of both Paper, and EssentialsX (Latest Dev build is fine), and only running EssentialsX, Official EssentialsX Addons, LuckPerms, and Vault; please show a video of this, it will help with replicating said behavior. 
My experienced behavior following the listed criteria above is exactly as it should. if my inventory is full, i get the message saying my inventory is full
![image](https://github.com/EssentialsX/Essentials/assets/46200123/422491c0-4ac2-436d-99a3-809dded35954)

**Comment by tekikaito** [comment]
@Evidentsinger14 it's not about buy/sell signs. It's about **Trade** Signs.

![2023-10-21_21.55.14.png](https://github.com/EssentialsX/Essentials/assets/25564488/ce23255a-3705-4938-9501-46f588177ac8)

You need 2 players to reproduce the bug: 

1. _Bob_ places a Trade-Sign with those lines: (L1: `[Trade]`, L2: `<any price>$`, L3: `1 shlkshell:1`)
2.  _Alice_ fills her inventory to a point where she´s not able to pick up any shulker shell
3. _Alice_ uses the Trade sign to buy shulker shells

**Result:**
Then the trade doesn´t actually happen, but the money in the sign increases.
_Bob_ is now able to retreive money from the sign, which wasn´t actually spent by _Alice_.

**Comment by Evidentsinger14** [comment]
Confirmed, Thank you for the proper reproduction steps. I'll forward to the development team

**Comment by pop4959** [comment]
This appears to be (at least partially) an API issue. I tested this on 1.18.2 and this was not an issue, but on 1.19.4 it is an issue.

The code below deals with the transaction, and rolls it back when the payment is not possible, for example, due to the player's inventory being full. This code appears to run as intended on both versions.
https://github.com/EssentialsX/Essentials/blob/79449ef663ae778fc63a1b1597486375c252f598/Essentials/src/main/java/com/earth2me/essentials/signs/SignTrade.java#L72-L77

If you follow the logic for addAmount/removeAmount you eventually get to the `setLine` call here which actually updates the value on the sign.
https://github.com/EssentialsX/Essentials/blob/79449ef663ae778fc63a1b1597486375c252f598/Essentials/src/main/java/com/earth2me/essentials/signs/SignTrade.java#L338

The problem is that when rolling back, the line is set back to the correct value, however this appears to get ignored when the sign actually updates.

**Comment by tekikaito** [comment]
Thanks, everyone!
