### ISSUE TITLE
Last sentences of messages_nl.properties not translated.

### ISSUE THREAD

**Issue by Patrickmid7** [EssentialsX/Essentials#5695]
### Feature description

**Current text: (Line 551)**
```
itemsConverted=\u00a76Converted all items into blocks.
itemsNotConverted=\u00a74You have no items that can be converted into blocks.
mailSentTo=\u00a7c{0}\u00a76 has been sent the following mail\:
mailMessage={0}

whoisTempBanned=\u00a76 - Ban expires:\u00a7r {0}
playerTempBanned=\u00a76Player \u00a7c{0}\u00a76 temporarily banned \u00a7c{1}\u00a76 for \u00a7c{2}\u00a76: \u00a7c{3}\u00a76.
mailFormat=\u00a76[\u00a7r{0}\u00a76] \u00a7r{1}
```

**Should be translated to:**

```
itemsConverted=\u00a76Alle items omgezet in blokken.
itemsNotConverted=\u00a74Je hebt geen items die omgezet kunnen worden in blokken.
mailSentTo=\u00a7c{0}\u00a76 heeft deze mail ontvangen\:
mailMessage={0}

whoisTempBanned=\u00a76 - Ban verloopt:\u00a7r {0}
playerTempBanned=\u00a76Speler \u00a7c{0}\u00a76 tijdelijk verbannen \u00a7c{1}\u00a76 voor \u00a7c{2}\u00a76: \u00a7c{3}\u00a76.
mailFormat=\u00a76[\u00a7r{0}\u00a76] \u00a7r{1}
```

### How the feature is useful

Because we currently have some English messages in our 100% Dutch server.

**Comment by pop4959** [comment]
Hi thank you for your concern. Translations are currently handled on [Crowdin](https://crowdin.com/project/essentialsx-official), which you are welcome to make an account for and contribute the text yourself. If approved they will be merged into a future release. Otherwise, you can also wait for someone else to translate it, but this can take time depending on the number of active translators for the language.
