### ISSUE TITLE
Can't use newline in /bc

### ISSUE THREAD

**Issue by WarnDa** [EssentialsX/Essentials#5716]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=17c7aa91a1014a058b674335f153affa

### Bug description

Since newer update, it's impossible to make a broadcast with multiple lines, I tried with  **\n** or **<newline>** and it doesn't work

### Steps to reproduce

Do like on the image "/bc test \n test" and "/bc test <newline> test"
![image](https://github.com/EssentialsX/Essentials/assets/31826333/45877ee3-cdcf-4a00-aa42-70e259bc4275)
The \n just cut the sentence and do not show what is after, and <newline> add a \ but doesn't create a new line

### Expected behaviour

It should send two lines in the chat

### Actual behaviour

It only sen one line with all the text

**Comment by Tosfoy** [comment]
Same thing here, and \n won't work

The only fix I found is setting this in the message config:
broadcast=\n{0}\n

Tho, this fix is only a band-aid, because certain of our broadcasts now takes too much space
![image](https://github.com/EssentialsX/Essentials/assets/58991099/2670aa62-9387-468e-b860-f3e9904c80f6)

A support to newline or \n when writing /broadcast would be great!
