### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by danieliustt** [EssentialsX/Essentials#5786]
### Type of bug

Error in console

### `/ess dump all` output

Newest

### Error log (if applicable)

https://paste.gg/p/anonymous/fe853f7982e2472da9a024f04ce7ad6b

### Bug description

Please fix that problem with not enough money formatting
if you use for example <dark_red> then you see tags

All good with /pay but then you get error when you use [Repair] sign if you use code below

notEnoughMoney=§4⚠ §cNeturi pakankamai pinigų! §4⚠\n 

### Steps to reproduce

Please fix that problem with not enough money formatting
if you use for example <dark_red> then you see tags

All good with /pay but then you get error when you use [Repair] sign if you use code below

notEnoughMoney=§4⚠ §cNeturi pakankamai pinigų! §4⚠\n 

### Expected behaviour

Please fix that problem with not enough money formatting
if you use for example <dark_red> then you see tags

All good with /pay but then you get error when you use [Repair] sign if you use code below

notEnoughMoney=§4⚠ §cNeturi pakankamai pinigų! §4⚠\n 

### Actual behaviour

Please fix that problem with not enough money formatting
if you use for example <dark_red> then you see tags

All good with /pay but then you get error when you use [Repair] sign if you use code below

notEnoughMoney=§4⚠ §cNeturi pakankamai pinigų! §4⚠\n

**Comment by ImDarkLaw** [comment]
The value you're using for the `notEnoughMoney` key in your messages properties file is unsupported, as already stated in the stack trace found in the logs you provided via pastebin, per Essentials v2.21 dev builds. 

Instead, opt to use [Adventure](https://docs.advntr.dev/)'s [MiniMessages format](https://docs.advntr.dev/minimessage/format.html) newly introduced to the latest Essentials dev builds.  

*(As far as this issue is concerned, we'd appreciate you properly fill in the requested fields and refrain from pasting the same piece of text on multiple sections.)*

**Comment by Chew** [comment]
Closing due to the reasons above. Also, "newest" isn't a valid dump.
