### ISSUE TITLE
Infinite Trade Signs

### ISSUE THREAD

**Issue by mudkiper107** [EssentialsX/Essentials#5814]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=e6ba1beabf69441081a27b39faabdd22

### Bug description

I have setup eco signs on my server and when either me (admin) or a player create a trade sign, it is created correctly ex. 
```
[trade]
1
1 iron_ingot 10
```
name is display underneath and when interacted it charges $1 and gives 1 iron ingot however the sign does not update with the deposited money and withdrawn ingots resulting in the sign being able to be used infinitely without adding more ingots and when trying to withdraw the money it says nothing to withdraw

### Steps to reproduce

Create a valid trade sign and interact with it

### Expected behaviour

transaction should occur taking the cost from player and deposit into the sign with the sign updating to reflect this change

### Actual behaviour

the sign does not update to reflect the changes

**Comment by Osgarth1** [comment]
Hey,

This is so strange, I've been having this issue too. It started with the update to 1.21. It's exceedingly frustrating as all the players on my server have shops that have had to be destroyed otherwise they would be abused.

To add issues I've found and context to get this fixed asap:

- Signs with Currency already stored in them could be withdrawn infinitely
- Signs with items in, those items could be purchased and money taken from the user's account however, the sign would not update so the overall quantity of items in the sign would not change and neither would any currency in the sign.
- Sign creation still works as intended
- Trying to add items to a sign after it's created to increase the stock able to be sold also has no impact on the total stock of the sign

It seems like interactions with signs are still happening but the sign is not updating.

Need this fixed as soon as possible, it is causing large issues. Could not find anyone else talking about this other than you so I appreciate you've confirmed my sanity haha

Thanks,
Osgarth :)

**Comment by FrankenBobbo** [comment]
Can confirm on latest version of 1.21 Essentials, `EssentialsX version: 2.21.0-dev+102-fcf6e64`
