### ISSUE TITLE
afk reasons

### ISSUE THREAD

**Issue by Jumpy91** [EssentialsX/Essentials#590]
What do you think about the idea to add afk reasons.
So you write for example "/afk dinner" so it says in chat "\* -Playername- is now AFK: dinner" and if you dont write an reason it just says "\* -Playername- is now AFK."

**Comment by Benjozork** [comment]
/afk already takes a player param.
Would love /afkr <reason> though.

**Comment by drtshock** [comment]
why... just seems silly

**Comment by dyanakiev** [comment]
This will be great afk reasons :)
/afk im goin to poop
/afk im goin to eat...

**Comment by Sketaful** [comment]
Add this as a response when someone message a player that's afk. 
If I type "/afk Just needed to make more coffee" and someone sends me a private message that player will recieve a "This player is AFK: Just needed to make more coffee".

As staff that would help a lot since if a staffmember need to run off a short time it's possible to add something like "/afk Back before <time>" and players that login after he went afk will still know.

**Comment by SupaHam** [comment]
I've created a PR for this request. It takes out the silly part of broadcasting it to everyone by default (you can change it in locale file if you want). However, by default it will notify /msg senders why the recipient is afk, assuming the recipient has set their afk message using `/afk im not actually afk.`

**Comment by pisaiah** [comment]
dev.bukkit.org/bukkit-plugins/afk

**Comment by SupaHam** [comment]
We will not support any third party services. Please wait patiently for the PR to be accepted, otherwise please proceed with caution.

**Comment by SupaHam** [comment]
This has been added in 9dfa650d. You can grab the feature from [build 380](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Documentation can be found here: https://github.com/drtshock/Essentials/wiki#afk-message
