### ISSUE TITLE
doubled messages when teleporting

### ISSUE THREAD

**Issue by RiseV-Freakz** [EssentialsX/Essentials#5912]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9ae5c00a6bea498fb2312990565ec834

### Bug description

when teleporting it sends the teleport message multible times.

### Steps to reproduce

/tp {player} ~ ~ ~

### Expected behaviour

It should only send the message once

### Actual behaviour

/tp ...
Server messages:
Teleporting...
Teleporting...

**Comment by Slimified** [comment]
I could not reproduce this issue on my end. Could you please try this on a clean server with no other plugins, on the latest supported version of Essentials? Thank you.

**Comment by MrFadeFancy** [comment]
> I could not reproduce this issue on my end. Could you please try this on a clean server with no other plugins, on the latest supported version of Essentials? Thank you.

I also have that issue when I do /spawn (I have 5 second cool down) I am getting 2 messages when I do /spawn (or any other teleporting commands) https://prnt.sc/V8etmLTmdYi0  I have latest dev version of essentials, spawn and chat

**Comment by RiseV-Freakz** [comment]
I cleaned my servers and only put on essentials but it is still sending it doubled. Maybe it's worth to mention that I use the velocity proxy and I have a connected server which also uses essentials. But even when the other Server is offline, I am still getting doubled messages.

**Comment by Slimified** [comment]
This is strange. I am not able to reproduce this bug at all on a standalone Paper server on the latest version, using the latest version of Essentials. Can you guys please try this setup and tell me if the error still occurs? Set up a local host server, you can find out how here:
https://docs.papermc.io/paper/getting-started

and then please re-download Essentials from the official website, using the latest stable build. Then let me know if this issue still occurs. If it does not, it would appear there is something else causing this bug.

**Comment by LuaSpace-Freakz** [comment]
I created a completely new server without any other plugins or
configurations. It's not even connected with a proxy or anything. I am
running on pufferfish for performance but I don't think that this is the
cause for it.
Here is another server dump:
https://essentialsx.net/dump.html?id=bde4f0c90a8a4920a4034f22867e4315

Am Di., 20. Aug. 2024 um 19:51 Uhr schrieb Slimified <
***@***.***>:

**Comment by RiseV-Freakz** [comment]
I created a completely new server without any other plugins or configurations. It's not even connected with a proxy or anything. I am running on pufferfish for performance but I don't think that this is the cause for it.
Here is another server dump:
https://essentialsx.net/dump.html?id=bde4f0c90a8a4920a4034f22867e4315

**Comment by MrFadeFancy** [comment]
I am also using just these plugins https://prnt.sc/OE5PtmGWICGS

https://prnt.sc/x92gc-anvxaZ  /spawn command
https://prnt.sc/hMfvi_w88DL1  /top command
https://prnt.sc/HXUZmmtj9Xzp  /back command

I can't test other commands because it requires more players

please test this when you have cooldown on teleport and are deoped

**Comment by Slimified** [comment]
I see what the issue is. It looks as though you will have to edit the messages file and just get rid of the teleportation commencing message. I do not believe it is a bug, it is a feature. Essentials lets the user know that the teleportation will commence, and there is a separate message, when the teleportation is commencing, to let the user know that they are about to be teleported. You can find out how to edit these messages here:
https://essentialsx.net/wiki/Locale.html

My recommendation is to simply make the "Teleportation Commencing..." message blank, replacing it with empty "" marks. Hopefully this resolves all of your issues.

**Comment by MrFadeFancy** [comment]
thank you I set 
teleporting= ""
that works

**Comment by Slimified** [comment]
I am pleased to hear that your issue was resolved. If you have any further inquiries about this topic, please post them here. Thank you.
