### ISSUE TITLE
"Error: \<dark_red>A warp with a similar name already exists."

### ISSUE THREAD

**Issue by melaniebeedot** [EssentialsX/Essentials#5932]
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=4c132d40e3d848089639e9d7ab26c84b

### Bug description

When trying to /setwarp $5, I get the error "Error: \<dark_red>A warp with a similar name already exists."

The color code is showing, but my main concern is that I can't set the warp. Many of our warp names are similar, so I'm not sure why this one is an issue?

![2024-09-07_12 32 50](https://github.com/user-attachments/assets/86e01de7-4d3d-4efb-b02f-3fa0c24f9b08)

Here's the start of our /warps list to show what similar warp names it may be referring to.

![2024-09-07_12 33 38](https://github.com/user-attachments/assets/eff39ba6-356a-42e7-a5f4-7f5af71d1eda)

### Steps to reproduce

1. Have the latest EssentialsX and Paper .jars installed
2. Run /setwarp $5

### Expected behaviour

The warp is set.

### Actual behaviour

The warp doesn't set, "Error: \<dark_red>A warp with a similar name already exists." results.

**Comment by Evidentsinger14** [comment]
This is kind of a weird situation. it's not a bug, as it's functioning exactly as intended but at the same time it is. 
all special characters are replaced with `_`. if you look in your `/plugins/Essentials/warps` directory, you'll see `_.yml`, `_HIT.yml` and so on. the `$` is being replaced with `_` but you already have `.5` so they're trying to claim the same file name. 

#1742 is a similar problem, except it's for homes, rather than warps. 
I'm going to leave open for now as it is a problem
