### ISSUE TITLE
Broken TPA Command 1.21.3

### ISSUE THREAD

**Issue by 0x7d8** [EssentialsX/Essentials#5969]
### Type of bug

Compatibility issue

### `/ess dump all` output

https://essentialsx.net/dump.html?id=76a50bbb4368474fa2ae8d7c7b927485

### Bug description

When running `/tpa <player>`, an error is shown
![grafik](https://github.com/user-attachments/assets/2939c9e4-1b9a-4b36-8b88-e23021677640)

### Steps to reproduce

1. Run `/tpa <player>` on 1.21.3
2. Error

### Expected behaviour

The request should be sent

### Actual behaviour

Error message `Index -1 out of bounds for length 0` (no additional console logs)

**Comment by azurejelly** [comment]
This is caused because `tpa-max-requests` on your configuration file is set to `0`. It should be `1` or higher. This is the line throwing the exception:

https://github.com/EssentialsX/Essentials/blob/2ac37d8dd406d934f6017119d1e5b39cfe705118/Essentials/src/main/java/com/earth2me/essentials/User.java#L371

**Comment by JRoy** [comment]
As pointed out above, please set `tpa-max-requests` to a value above 0
