### ISSUE TITLE
Tab list customization

### ISSUE THREAD

**Issue by Turbotailz** [EssentialsX/Essentials#655]
I see there is now an option to change the style of a player's name on when they are AFK, which is great and looks awesome when I set it up, but now I'd like to be able to customize the styles of everyone's names to try and match it. I don't really want to bother with another plugin when the functionality seems to be here, just only works in a certain scenario (ie. players going AFK).

I'd also like to point out - as also mentioned in issue #481 - that only players who manually activate AFK mode with /afk will appear as AFK on the tab list.

A picture for reference on my server:

http://i.imgur.com/fgtIsZZ.png

You can see two of us are AFK, but there are in fact a few more players AFK, they just didn't type the command like we did.

**Comment by drtshock** [comment]
Please make separate tickets for separate issues.

I don't understand the scope of your request

**Comment by SupaHam** [comment]
I have tested #481 and the bug is in fact invalid as of the latest EssentialsX, you might be on an old build that has this bug that I am unaware of.

As for the feature request, it does seem a little more complicated than just the AFK feature which is currently present. That'll have to be thought out a little more to decide how the configuration should go, if at all.

**Comment by timr2000** [comment]
i have the same issue
