### ISSUE TITLE
Essentials errors

### ISSUE THREAD

**Issue by StalKlim** [EssentialsX/Essentials#684]
Hello. I have several problems with the plugin EssentialsX. Help me. http://pastebin.com/WZBg7q1y http://pastebin.com/RpPYFQ8d http://pastebin.com/Nqu77CVr

UPD: Spigot 1.8.8

**Comment by SupaHam** [comment]
Please create separate issues for each issue you have. So far the first pastebin is the only valid issue that we can investigate. The rest requires you to simply update your EssentialsX version.

**Comment by SupaHam** [comment]
So from our end it seems we're doing things just fine. We are doing things synchronously which is as error-proof as it can get from our end. This issue is being caused by Minecraft itself.

After some digging, this issue is also happening in other plugins such as Multiverse as can be seen [here](http://pastebin.com/UTXd6he1).

**Comment by StalKlim** [comment]
Wait. The last 2 pastebin can fix update. But what to do with the first? I dont have MultiverseCore in my server. The only error occurs on my server, I sent yesterday, thinking that they are associated with Essentialschat. https://github.com/drtshock/Essentials/issues/682

**Comment by SupaHam** [comment]
As I said yesterday, regarding #682. Two other plugins are causing those issues.

Regarding the issue of the first pastebin you linked: Minecraft is causing the error. You will need to **contact Spigot** and ask them for a solution, you are not the only person and this issue is being caused in other plugins like MultiverseCore. It doesn't mean you're using MultiverseCore, it just means that this issue is happening in other bukkit plugins as well.

**Comment by StalKlim** [comment]
kk. thanks.

**Comment by StalKlim** [comment]
I asked in IRC chat people about this problem. I was told that version 1.8.8 is no longer supported, and any corrections to it, too, will not. It turns out the plugin Essentials will continue to arise such a problem, including the impact on server performance?

**Comment by SupaHam** [comment]
Apparently so. Sadly, as I mentioned in my previous comment these issues are caused by Minecraft and are out of our control. I would advise updating to 1.9 or even 1.10 for the latest bug fixes if possible.

**Comment by StalKlim** [comment]
Listen. The case may be that some of the worlds of my servers were moved from 1.7.2 and earlier versions and have not been re-generated?

**Comment by SupaHam** [comment]
That can very much be the cause as the error has to do with changing the player's fly speed (which writes to the world data files), but I still cannot guarantee the solution.
