### ISSUE TITLE
AFK color code issue

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#700]
``` yaml
# Set the player's list name when they are AFK. This is none by default which specifies that Essentials 
# should not interfere with the AFK player's list name.
# You may use color codes, use {USERNAME} the player's name or {PLAYER} for the player's displayname.
afk-list-name: &7[AFK] &o{USERNAME}
```

^It claims that I can't do that when trying to make it.

**Comment by ghost** [comment]
Sorry about the massiv text

**Comment by SupaHam** [comment]
~~Can you please not use unnecessary headings like that. It is irritating.~~

Try:

``` yaml
afk-list-name: '&7[AFK] &o{USERNAME}'
```

In YAML if you start with one of many symbols, including `&` you need to actually use quotations, single or double.

P.S. the massive text is because you used `#`.

Edit: I edited your post to wrap all of the config content into code blocks using three backticks `

**Comment by ghost** [comment]
Silly me, sorry about that.
