### ISSUE TITLE
Request Vietnamese language

### ISSUE THREAD

**Issue by Banbeucmas** [EssentialsX/Essentials#741]
This is translated from Essentials, but I think EssentialsX is similar, I want to add Vietnamese (vi_VN) as one of the language of the plugin

https://www.dropbox.com/s/7aehzqmx0rr3vy9/messages_vn%20-%20Copy.properties?dl=0
Hope you agree

Edit: Updated download link (Directly from the forum)
Edit: Second time updated
Edit: Third time updated - Now its fully translated (98%)

**Comment by drtshock** [comment]
Can anyone else vouch for this translation? I only speak english and pig latin (from middle school).

**Comment by Banbeucmas** [comment]
Posted this on facebook, lots of people will want this

**Comment by huynhtancuong** [comment]
I hope it too :D

**Comment by ConHeoAnThitHeo** [comment]
"lots of people"

+1

**Comment by MiniDigger** [comment]
well, we need for ppl that can confirm that this is a good translation.

**Comment by Banbeucmas** [comment]
@MiniDigger trying to get loads of people on facebook and Vietnamese forum here XD

**Comment by sdvn** [comment]
file is not translate yet

**Comment by zFangxiang** [comment]
I see it very useful for Vietnam. I hope it is one of the language of the plugin

**Comment by Banbeucmas** [comment]
@sdvn updated link T_T now it should be translated

**Comment by sdvn** [comment]
it's not full translate  ! pls serious about this

**Comment by Banbeucmas** [comment]
@sdvn yeah, just try to convert into UTF-8 and you will see some translated *We don't need all of them
http://hastebin.com/zikukomanu.tex

**Comment by quachtridat** [comment]
@Banbeucmas oh no no no

Please be serious as @sdvn said. Generally we Vietnamese can skip translating those lines which we considered "not-necessary", but it need to be fully-translated in order to get qualified. Technically-related text may be kept untranslated, but at least there must be Vietnamese in each line of text.

![tmp](https://cloud.githubusercontent.com/assets/6735818/17188505/8c40d276-5467-11e6-9789-47c212d2eb86.jpg)
These lines are no need? Welp, just take the file back.

[@MiniDigger](https://github.com/MiniDigger) The file is still WIP.

**Comment by sdvn** [comment]
"We don't need all of them " - Banbeucmas 

WWoa , Pls , stop this shit ! "We" dont need translate this with that kind @drtshock !

He just translate 30% file

**Comment by SupaHam** [comment]
We appreciate your efforts and passion towards this, but can we stop arguing aggressively?

In order for us to accept a translation file we need others to chip in and approve of it. I'm not sure how many EssentialsX users are Vietnamese or know the language, but even if they're not EssentialsX users, their input and confirmation is still valid as long as we know they can be trusted, e.g. not spam creating accounts just to approve it.

Furthermore, if the locale file is not mostly translated, then we should hold off until it is and again, confirm with others.

**Comment by Banbeucmas** [comment]
@SupaHam nah its ok with the harassmant, I get used to it

@quachtridat @sdvn re-check
http://hastebin.com/aveceqeyah.ini

The download link has converted into Java entries so no worries about it
(2% of it cannot be translated due to preventing the console from smashing weird characters, Would previde fully if you want)

**Comment by SupaHam** [comment]
@Banbeucmas It's not about you, it's about setting an example about our community.

If the 2% messages are only being sent to the console, then that should be fine. Translation can be done over time, but it's important that the initial file have the majority translated to Vietnamese.

In order to properly proceed with this request, I must ask that you create a Pull Request. If you are unable to do that, I can create it myself with your permission to use your translations, giving you all the credit of course.

**Comment by Banbeucmas** [comment]
I don't know how to do that tho
Can you create it?

**Comment by mdcfe** [comment]
The Vietnamese translation was added in 2ced9469d78d94b4d89a7e3f1ab7047465ac163a.
