### ISSUE TITLE
[Bug] Command cooldown

### ISSUE THREAD

**Issue by Brend-Smits** [EssentialsX/Essentials#751]
Hello 
Just a small but irritating bug. 
I put the Nick command on a 24 hour cooldown. Here is what happends.
If /nick is on cooldown, doing nick after about 10 minutes resets the timer, making you wait an extended period, not just 24 hours.

Is there a way to fix this?

**Comment by SupaHam** [comment]
I'm unable to reproduce this bug. When I type a command like `/nick` and then type it once again a few seconds after, I am told of the remaining cooldown and it is always consistent. The user file is also unchanged.

I don't believe this ever was a thing since it was implemented. But just to be sure, you can update your EssentialsX version from [CI server here](https://ci.drtshock.net/job/EssentialsX/).
