### ISSUE TITLE
[request] essentials.fly.pvp

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#756]
Please, add the permission "essentials.fly.pvp" to prevent players give damage to other players during the fly. Just as it was done with "essentials.god.pvp" permission. Thanks.

**Comment by drtshock** [comment]
So make it so you can't damage other players while flying? That seems well out of the scope of this project.

**Comment by molor** [comment]
@drtshock, but why not? This is, I think, is not difficult..

Similar functionality is already implemented: now you can deny invincible players to participate in PvP, not giving them permission "essentials.god.pvp".
Why not create the permission "essentials.fly.pvp", which if you take from player, deny him to participate in PvP while flying..?

Sorry for my bad English, but this feature really need me now..

**Comment by SupaHam** [comment]
`essentials.god.pvp` can be justified because it introduces the balance for players who are in god mode and in a PVP area.

Your suggestion can be argued, but I also do not agree with it. The feature has no rational justification as far as I can see. For example, players can stop flying, damage players, and then fly again to become invulnerable.

**Comment by molor** [comment]
> For example, players can stop flying, damage players, and then fly again to become invulnerable.

hmm, Okay.
