### ISSUE TITLE
Tablist prefixes toggle

### ISSUE THREAD

**Issue by baticag** [EssentialsX/Essentials#771]
Can you add option to toggle this https://github.com/drtshock/essentials/commit/8d3d2ebd50dcd5ad510975f7628f9500134ea72b ?
Because I want to change the color of player-name in player-list but without seeing the prefix in front. So a config option for the switch between old behaviour and this would be nice :)

**Comment by SupaHam** [comment]
Are you certain you're referring to the same thing? It does not make sense to me.

That commit simply allows for longer nicknames. Instead of trimming excess characters due to behaviour prior to 1.8 it now takes that into account and allows for longer nicknames for 1.8+. So prior to that commit you would still be seeing whatever prefix because all it did before was cut off the end of the name, not the beginning.

**Comment by baticag** [comment]
Yes I think I am... Because that is the only commit I saw changing the playername in TabList...

Now my tablist looks like this: http://i.imgur.com/WhIHnss.png
Before it was without this [VIP], [Creator], [Vlasnik] prefixes, but nicknames where still in colors of prefixes, so the name of [VIP] in tablist was only &eNAME.

It changed that way when I updated EssentialsX so I am sure that it is making it show Player Name in tablist that way. I didn't change any config values, they are the same, as they were when it was working like I wanted.

change-displayname: true
change-playerlist: true
#add-prefix-suffix: false

Can you please look into it?

**Comment by SupaHam** [comment]
This has been fixed in  63b5cb9. You can grab the fix from [build 419](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
