### ISSUE TITLE
Essentials not working after server reload\ plugin reload

### ISSUE THREAD

**Issue by nicholasfd** [EssentialsX/Essentials#775]
Hi. I recently noticed that every time I had to restart my server, my Essentials plugin would completely stop working. I did /pl to get my list of plugins, and they all show up green, even know they dont work. The only way that I can get it to work is if I stop and start the server. I dont know what to do, or how to fix it.

**Comment by SupaHam** [comment]
If you're restarting the server, you're stopping and starting the server.

I'm going to assume you actually meant to say reloading the server. In that case, you should never reload, and it's been a bad bad feature since day 1. Always restart your server. If you made a change to the EssentialsX configuration file, you can instead specifically reload EssentialsX by typing `/ess reload`.
