### ISSUE TITLE
essentialsX and zpermissions not working

### ISSUE THREAD

**Issue by beerface707** [EssentialsX/Essentials#777]
hello, I am using essentialsX as this seems to be the newest essentials kept up to date. I am also trying to use Zpermissions. I can't get Zpermissions to recognize any commands for essentialsX. I have the default group set up and all that. I have tried deleting the entire "player-commands" section in essentialsX config and also changing use-bukkit-permissions to false and true, Both have done absolutely nothing. not even /help works, no commands work that should just be for the default players. please help thanks

**Comment by SupaHam** [comment]
Try installing Vault. :)

**Comment by beerface707** [comment]
I have vault installed

**Comment by SupaHam** [comment]
Please pastebin your server log.

**Comment by beerface707** [comment]
here is the pastebine link for my server log, thanks for help me by the way, i have been trying to figure this out for so long now
http://pastebin.com/HxhMDtPd

**Comment by SupaHam** [comment]
All looks good on our end. Type `/ess debug` in game and then try typing a command like `/list`. And then pastebin the server log again.

**Comment by beerface707** [comment]
ok I have just done what you said and here is the log after I did that. http://pastebin.com/JhcmHkxv

some else that is very strange, is that when I delete the essentials folder it makes in plugins to get it to generate a brand new confg file, once it makes the new config and I open it, its the same as the one I just edited and deleted.

**Comment by SupaHam** [comment]
Alright, so as it stands the issue you are having is with zPermissions and not EssentialsX. You need to make sure you are using the right commands and permission nodes.

For example, in order for `beerface707` to use /list, they must have the `essentials.list` permission. Try typing this in the console: `zpermissions player beerface707 set essentials.list`

Edit: I'm assuming the file is the same because you probably didn't close and reopen it.

**Comment by beerface707** [comment]
I will give this a go, and post the results if it worked or not. I thank you so much for you help! you sir are awesome! like I said I have been banging my head against the wall all day with this!

**Comment by beerface707** [comment]
is there a list of all the basic command/permissions for essentialsX for normal players so I just paste them into zpermissions data.yml? I also dont understand why essentialsX wouldnt just allow the default group access to the normal user commands

**Comment by SupaHam** [comment]
EssentialsX does have default player permissions setup in the config, the part which you deleted, but that only works when a permissions plugin isn't present. Otherwise, EssentialsX doesn't assume what permissions players should have by default, instead the admins (you) are left in charge of handling those details.

There's no list that you can just copy & paste, also you should use the commands provided by your permissions plugin instead of editing the file to minimize errors.

If you want a list of commands and permissions, click the wiki button at the top of the page.
