### ISSUE TITLE
How to replace number divider?

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#799]
How to replace the [NB SP] character in money output?

I mean this: $3**[NB SP]**696,67

Examples in chat of my server:
![2016-08-04_16 45 36](https://cloud.githubusercontent.com/assets/19989717/17404058/2109ae22-5a63-11e6-88bb-291a026855cd.png)
![2016-08-04_16 46 23](https://cloud.githubusercontent.com/assets/19989717/17404057/2107f5a0-5a63-11e6-821f-77500ee2c537.png)

**Comment by SupaHam** [comment]
This minor bug was introduced in 282ec81 and requires you to simply override `currency-symbol-format-locale` in the config and set it to en-US (US currency formatting). As seen [here](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L629).

Alternatively, this has been fixed in 5187be5. You can grab the fix from [build 422](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
