### ISSUE TITLE
Teleport Request (/tpa) Bug

### ISSUE THREAD

**Issue by andrescol24** [EssentialsX/Essentials#818]
Hello!!

When we installed the new EssentialsX plugin on our server the teleport request began to fail.

When I send a tpa to another player  no problem, but if the player doesn`t answer my Teleport Request with tpaccept or tpdeny, I can not send other tpa to same player including whether the time tpa ends. 
The message that come out is: "Error: You have already sent <PlayerName> a Teleport Request"

I searched any option to configure it on config.yml, but i do not find something.

**Comment by soliddanii** [comment]
I have problems too with /tpa.
My players have all the permissions nodes. One minute they can use it, the next they get "You do not have tpa request" when trying to use it. At the same time one player can use it and others don't. All same rank, same world. Weird.
I didn't create a new issue because its maybe the same.
Thank you.

**Comment by andrescol24** [comment]
Can some owner answer my issue?thanks.

How can i configure the teleport request's Time? , i tried with tpa cooldown in config.yml but that did not work

**Comment by Kakifrucht** [comment]
I can confirm this being an issue.

**Comment by SupaHam** [comment]
This has been fixed in ad94cca9. You can grab the fix from [build 444](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

**Comment by BillyGalbreath** [comment]
@SupaHam your fix broke /tpa completely now. All requests are considered timed out even if accepted within seconds of the request.

I'm not alone in this either. The two people posting after me in the discussions thread on spigot experience the exact same behavior: https://www.spigotmc.org/threads/essentialsx.76168/page-61#post-2038426

**Comment by SupaHam** [comment]
My bad. FYI `/tpaccept` is "broken", not `/tpa`.

This has now been fixed in 3c18efc4. You can grab the fix from [build 446](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Also, you're not entitled to any updates or any hours of my life, so please show us the same respect we show you by giving you software that is built on thousands of hours worth of work.

**Comment by BillyGalbreath** [comment]
Ok, rudeness.. I was just informing you of a bug. Nowhere did I treat you, or anyone with disrespect.

**Comment by SupaHam** [comment]
>Apparently they don't read the discussions thread other than to laugh at us peasants.

I don't read the thread because I don't go on spigotmc, not that it matters. Who told you we refer to our users as peasants or even that we laugh at "peasants"?

**Comment by BillyGalbreath** [comment]
I quoted it from the front page of EssentialsX, at the bottom. Not my words.

https://i.imgur.com/KHpPQkX.png

**Comment by SupaHam** [comment]
Resource page:
>Support requests in our thread will be ignored and laughed at.

Your version:
>Apparently they don't read the discussions thread other than to laugh at us peasants.

There's a massive difference between the resource page and your version. The resource page clearly states that you should not request support in the thread; so don't do it.

You have stated that we don't read the thread other than to laugh at you "peasants." That is not true. You've manipulated the official writing to make the team that writes the software you use look like a bunch of asswipes who do no good.

**Comment by Kakifrucht** [comment]
Thanks @SupaHam for your continued and free support of this software :)

**Comment by BillyGalbreath** [comment]
> You've manipulated the official writing to make the team that writes the software you use look like a bunch of asswipes who do no good.

Think what you want, man. I just calls 'em like I sees 'em. I, too, am a developer that has spent thousands of hours making dozens of plugins for the community. So dont think I am going to sit back and put you on a pedistal or praise you. You made a mistake, so I pointed it out for you to fix it. I'm sorry you took offense to my specific wording instead of rolling with it. I do thank you for fixing the issue.. but I feel those words have cheapened now with the current atmosphere.

**Comment by SupaHam** [comment]
I'm not asking for praise. But thank you regardless.

Think of it like it's your own project that you work on. Do you want people to go off the first moment you make a mistake? What was the extent of the mistake? How much damage did it cause? How hard was it to rollback to a working version? It's not advertised as a stable build so you have to use it at your own risk. With that said, we don't seek to destroy people's servers.

Thank you for reporting a bug once more, I hope it wasn't too inconvenient.

**Comment by Romaq** [comment]
I try to be funny sometimes, and I get reminded not to quit my day job.

Thank you for fixing the bug, I will do the upgrade as I noticed the same problem. I am understanding that "issues" is the correct area for dropping feature requests rather than in the Spigot forum.

I've been at upgrading for some days, sorting through problems and issues with plugins. There are "meta" issues also, tempers being frayed within the US in particular. I hope we can do something in a bug report forum that seems unusual in social media: just be cool and focus on the task at hand.

But it might help avoid misunderstandings to remove the "attempt at humor" on the bottom of the page. I know humor seems to be in short supply these days. That's why I play Minecraft.
