### ISSUE TITLE
[Request] Config option for matchplayer

### ISSUE THREAD

**Issue by Gerrygames** [EssentialsX/Essentials#830]
I would love to see a config option for disabling the matchplayer function (e.g. when a player sends a command like `/tpa gerry` Essentials automatically executes `/tpa Gerrygames`). Since the tab completion function is implemeted in Minecraft this function is pretty unnecessary and actually a real hassle when trying to program a nick plugin.

**Comment by mdcfe** [comment]
If I recall correctly, isn't this down to how the server resolves names? As far as I know Essentials only checks to make sure the player isn't hidden from the sender (ie through `/v`).

**Comment by Gerrygames** [comment]
Nope. I dont mean that it automatically completes the Name when you press tab. I mean if you send the command e.g `/tpa gerry` or even `/tpa rrygames`, you will automatically send a teleportrequest to Gerrygames. In vanilla on the other hand if you send the command `/gamemode 1 gerry` it will say that this player isnt online.

**Comment by mdcfe** [comment]
@Gerrygames I'm fully aware that's what you mean. As far as I can tell, Essentials asks Bukkit to resolve the name for it. I don't see any name matching code that could easily be made configurable without breaking things.

**Comment by pop4959** [comment]
Closing this for now. This is a fairly niche request, and it's unlikely that we'll ever get around to working on something like this, especially apparently as md mentioned it may break things.

Feel free to PR this if you still need it though. Since it's been over 3 years I wouldn't be surprised if you found some other solution by now.
