### ISSUE TITLE
Command Cooldowns

### ISSUE THREAD

**Issue by RoyalRaid** [EssentialsX/Essentials#878]
Hey,
Having a issue adding command cooldown to /fix

`command-cooldowns:`
  `nick: 30`

This is what i have set in config, but players can still use without a cooldown, i tried changing the nick to ext and cooldown worked perfectly. Thanks in advance

**Comment by SupaHam** [comment]
Because you need to indent `nick`, it's how yaml files work.

```
command-cooldowns:
  nick: 30
```

**Comment by RoyalRaid** [comment]
it is indented, its just the way it got pasted on here

**Comment by SupaHam** [comment]
Make sure they aren't bypassing cooldowns then. https://github.com/drtshock/Essentials/wiki/Command-Cooldowns#bypass

If you dont think they are, type `/ess debug`, reproduce this bug, then pastebin the server log.

**Comment by RoyalRaid** [comment]
08.09 22:00:52 [Server] INFO [Essentials] checking if lachlan7327 has essentials.commandcooldowns.bypass - false

Still was able to bypass cooldown though

**Comment by RoyalRaid** [comment]
Heres the pastebin: http://pastebin.com/rBXGSE3N

**Comment by SupaHam** [comment]
In your main issue, you write
`command-cooldowns:`
`nick: 30`

but in that log you try and execute a different command called `/fix`. When reporting an issue, the tiniest details matter. Yes, even the command you're executing.

That is your problem. I assume you put the following in your config:

```
command-cooldowns:
  fix: 30
```

That's invalid because there is no command actually called `fix` instead, there's an alias for `repair` called `fix`.

Essentials cooldowns requires that you use main command names. Please refer to the [Command Reference](http://wiki.mc-ess.net/wiki/Command_Reference) for information regarding command names.

Duplicate of #803.

**Comment by RoyalRaid** [comment]
Ahh legend! That did the trick, thank you very much!
