### ISSUE TITLE
Need to look into CanDestroy NBT flag

### ISSUE THREAD

**Issue by drtshock** [EssentialsX/Essentials#9]

**Comment by SupaHam** [comment]
Can you elaborate?

**Comment by drtshock** [comment]
I believe it was not supporting NBT tags in signs

**Comment by pop4959** [comment]
I'm going to go ahead and close this since it seems this dinosaur of an issue doesn't seem to garner much/any interest, nor is there anyone looking to implement it. I'm pretty sure most people who want to give an item with NBT tags such as CanDestroy most likely do it with alternative methods/plugins, and probably don't even think of trying to do it via signs.
