### ISSUE TITLE
Disable people paying negative values request

### ISSUE THREAD

**Issue by Elgorond** [EssentialsX/Essentials#906]
If players with the normal essentials.pay permission do /pay player -1 for instance, it will just function as /pay player 1. This isn't a big deal, but players can trick "noobs" into thinking paying negative will give them money...

**Comment by Kakifrucht** [comment]
Yes, this shouldn't be possible

**Comment by Kakifrucht** [comment]
@SupaHam since you already have the setup, could you fix this very quickly by, a) adding '-' to the regex (not replacing it) [here](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandpay.java#L30) and b) checking if BigDecimal is negative [here](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandpay.java#L37). It would also be nice if you could automatically add a replace for "," to ".", since comma is the default decimal format in many countries. I'd do it myself but it is a bigger hassle to set it up right now.

**Comment by SupaHam** [comment]
@Kakifrucht Replacing comma could introduce more issues than it would solve. By replacing comma with fullstops we would not be accommodating the greater part of the world. It would need to be discussed further.

**Comment by SupaHam** [comment]
This has been fixed in e5b5994. You can grab the fix from [build 443](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

**Comment by mdcfe** [comment]
@Kakifrucht @SupaHam Here's an idea: load the regex from the localisation file. I know that its current purpose is for custom messages, but this is something which varies greatly across the world and would benefit from being localisable.

**Comment by SupaHam** [comment]
Please discuss this in a separate issue.
