### ISSUE TITLE
[1.10] [2.0.1-b437] Spawn Egg ID's & Potion ID's

### ISSUE THREAD

**Issue by Elijeh** [EssentialsX/Essentials#921]
On 1.10, whenever you use /itemdb on a chicken egg (or any other mob egg), it will only show the item name and item ID & meta-data of the default Minecraft spawn egg (383:0).

I'm using EssentialsX 2.0.1-b434.

**Comment by Elijeh** [comment]
This applies to potions as well.

And whenever I create a kit with different potions in-game, then it will just appear as a POTION or SPLASH_POTION item when I use the kit.

Hopefully this will be fixed as soon as possible.

Updated Information:
Minecraft Version: 1.10
Plugin Version: 2.0.1-b437

**Comment by SupaHam** [comment]
As far as I can see, it will not be easy to fix this. 1.10 changed the way some items work, to no longer depend on durability numeric value, instead it now uses the item data tags to represent which mob to spawn. Due to this change, our system would need either a rewrite or a hacky fix that accounts for items like mob eggs and potions.

**Comment by pop4959** [comment]
Minecraft 1.13 and above no longer even have item IDs or damage values anymore, so this should no longer be an issue.
