### ISSUE TITLE
EssentialsX sign shop not working

### ISSUE THREAD

**Issue by 19celtic71** [EssentialsX/Essentials#955]
I have installed EssentialsX and my sign shop will allow me to build the sign but won't display any text nor will it allow me to use it. Any ideas?

**Comment by saturnux** [comment]
have you enable the functionality in the list ?

**Comment by Trickster489** [comment]
Paste configuration file, sounds like sign functionality is disabled.

**Comment by 19celtic71** [comment]
Essentials

[http://pastebin.com/UeXBAz0H]

**Comment by mdcfe** [comment]
~~To use code blocks on GitHub, wrap them with three backticks (`)~~

~~It's much easier to use a paste site like Gists though.~~

**Comment by mdcfe** [comment]
Could you paste the output of `/ess debug`?

**Comment by saturnux** [comment]
in fact if your sign is bad, the sell or buy is in red.
if nothing appear in sign it's probably another plugin in cause.

i think...

**Comment by 19celtic71** [comment]
Here is my plugin list.

http://prntscr.com/d3einy

**Comment by SupaHam** [comment]
I'm going to mark this as a duplicate of #687. Where you have needed to update your Spigot server software to fix the bug. However there's a chance you have already done this since 1.11 has been out. If I am mistaken please reply with your startup log.

Steps:

1. Open `logs` directory in server directory.
1. Find and open a file called `latest.log`.
1. Go to [www.pastebin.com](http://pastebin.com).
1. Copy all `latest.log` contents and paste into the big text area.
1. Copy & paste the URL in your browser into a reply here.
